Urbi SDK Remote: urbi::UCallback4< OBJ, R, P1, P2, P3, P4 > Class Template Reference
urbi::UCallback4< OBJ, R, P1, P2, P3, P4 > Class Template Reference
#include <ucallbacks.hh>
Public Member Functions
MKUCallBackNotifyCtr4 (, false)
MKUCallBackNotifyCtr4 (const, true)
virtual UValue __evalcall (UList &param)
Private Attributes
OBJ * obj
R(OBJ::* fun)(P1, P2, P3, P4)
R(OBJ::* funconst)(P1, P2, P3, P4) const
bool is_const_
Detailed Description
template<class OBJ, class R, class P1, class P2, class P3, class P4>
class urbi::UCallback4< OBJ, R, P1, P2, P3, P4 >
Definition at line 905 of file ucallbacks.hh.
Member Function Documentation
template<class OBJ , class R , class P1 , class P2 , class P3 , class P4 > virtual UValue urbi::UCallback4< OBJ, R, P1, P2, P3, P4 >::__evalcall (UList & param) [inline, virtual]
Implements urbi::UGenericCallback.
Definition at line 931 of file ucallbacks.hh.
References urbi::UContext::ctx_, urbi::UCallback4< OBJ, R, P1, P2, P3, P4 >::fun, urbi::UCallback4< OBJ, R, P1, P2, P3, P4 >::funconst, urbi::UCallback4< OBJ, R, P1, P2, P3, P4 >::is_const_, and urbi::uvar_uvalue_cast().
template<class OBJ , class R , class P1 , class P2 , class P3 , class P4 > urbi::UCallback4< OBJ, R, P1, P2, P3, P4 >::MKUCallBackNotifyCtr4 (false)
template<class OBJ , class R , class P1 , class P2 , class P3 , class P4 > urbi::UCallback4< OBJ, R, P1, P2, P3, P4 >::MKUCallBackNotifyCtr4 (const , true)
Member Data Documentation
template<class OBJ , class R , class P1 , class P2 , class P3 , class P4 > R(OBJ::* urbi::UCallback4< OBJ, R, P1, P2, P3, P4 >::fun)(P1, P2, P3, P4) [private]
Definition at line 946 of file ucallbacks.hh.
Referenced by urbi::UCallback4< OBJ, R, P1, P2, P3, P4 >::__evalcall().
template<class OBJ , class R , class P1 , class P2 , class P3 , class P4 > R(OBJ::* urbi::UCallback4< OBJ, R, P1, P2, P3, P4 >::funconst)(P1, P2, P3, P4) const [private]
Definition at line 947 of file ucallbacks.hh.
Referenced by urbi::UCallback4< OBJ, R, P1, P2, P3, P4 >::__evalcall().
template<class OBJ , class R , class P1 , class P2 , class P3 , class P4 > bool urbi::UCallback4< OBJ, R, P1, P2, P3, P4 >::is_const_ [private]
Definition at line 948 of file ucallbacks.hh.
Referenced by urbi::UCallback4< OBJ, R, P1, P2, P3, P4 >::__evalcall().
template<class OBJ , class R , class P1 , class P2 , class P3 , class P4 > OBJ* urbi::UCallback4< OBJ, R, P1, P2, P3, P4 >::obj [private]
Definition at line 945 of file ucallbacks.hh.
The documentation for this class was generated from the following file:
ucallbacks.hh