Urbi SDK Remote: urbi::baseURBIStarter Class Reference
urbi::baseURBIStarter Class Reference
#include <ustarter.hh>
Public Types
typedef std::list
< baseURBIStarter * > list_type
List of starters.
Public Member Functions
baseURBIStarter (const std::string &name, bool local=false)
virtual ~baseURBIStarter ()
virtual UObject * instanciate (impl::UContextImpl *ctx, const std::string &n=std::string())=0
Create an instance of the UObject.
std::string getFullName (const std::string &name) const
Return the full name to pass to the UObject constructor.
Static Public Member Functions
static list_type & list ()
Public Attributes
std::string name
bool local
Set to true to have the UObjects use a random unique name.
Detailed Description
Definition at line 50 of file ustarter.hh.
Member Typedef Documentation
typedef std::list<baseURBIStarter*> urbi::baseURBIStarter::list_type
List of starters.
Definition at line 66 of file ustarter.hh.
Constructor & Destructor Documentation
urbi::baseURBIStarter::baseURBIStarter (const std::string & name, bool local = false) [inline]
Definition at line 29 of file ustarter.hxx.
urbi::baseURBIStarter::~baseURBIStarter () [inline, virtual]
Definition at line 35 of file ustarter.hxx.
Member Function Documentation
std::string urbi::baseURBIStarter::getFullName (const std::string & name) const
Return the full name to pass to the UObject constructor.
virtual UObject* urbi::baseURBIStarter::instanciate (impl::UContextImpl * ctx, const std::string & n = std::string()) [pure virtual]
Create an instance of the UObject.
Implemented in urbi::URBIStarter< T >.
Referenced by urbi::impl::UContextImpl::bind(), urbi::impl::RemoteUContextImpl::makeRTPLink(), and urbi::impl::RemoteUContextImpl::newUObjectClass().
baseURBIStarter::list_type & urbi::baseURBIStarter::list () [static]
Definition at line 23 of file ustarter.cc.
Referenced by urbi::impl::UContextImpl::bind(), urbi::impl::UContextImpl::init(), urbi::URBIStarter< T >::URBIStarter(), and urbi::URBIStarter< T >::~URBIStarter().
Member Data Documentation
bool urbi::baseURBIStarter::local
Set to true to have the UObjects use a random unique name.
Definition at line 61 of file ustarter.hh.
std::string urbi::baseURBIStarter::name
Definition at line 59 of file ustarter.hh.
Referenced by urbi::impl::UContextImpl::bind(), urbi::impl::UContextImpl::init(), and urbi::URBIStarter< T >::instanciate().
The documentation for this class was generated from the following files:
ustarter.hh
ustarter.cc
ustarter.hxx