Urbi SDK Remote: urbi::impl::RemoteUContextImpl Class Reference
urbi::impl::RemoteUContextImpl Class Reference
#include <remote-ucontext-impl.hh>
Public Types
typedef boost::unordered_map
< std::string, std::pair
< libport::AsyncCallHandler,
UTimerCallback * > > TimerMap
typedef boost::unordered_map
< std::string, UObject * > RTPLinks
Public Member Functions
RemoteUContextImpl (USyncClient *client)
Setup to work on given client.
virtual ~RemoteUContextImpl ()
virtual void newUObjectClass (baseURBIStarter *s)
Called to instanciate the first Object of class.
virtual void newUObjectHubClass (baseURBIStarterHub *s)
virtual void uobject_unarmorAndSend (const char *str)
Send Urbi code (ghost connection in plugin mode, default connection in remote mode).
virtual void send (const char *str)
Send the string to the connection hosting the UObject.
virtual void send (const void *buf, size_t size)
Send buf to the connection hosting the UObject.
virtual void call (const std::string &object, const std::string &method, UAutoValue v1=UAutoValue(), UAutoValue v2=UAutoValue(), UAutoValue v3=UAutoValue(), UAutoValue v4=UAutoValue(), UAutoValue v5=UAutoValue(), UAutoValue v6=UAutoValue(), UAutoValue v7=UAutoValue(), UAutoValue v8=UAutoValue())
virtual void declare_event (const UEvent *owner)
virtual void emit (const std::string &object, UAutoValue &v1, UAutoValue &v2, UAutoValue &v3, UAutoValue &v4, UAutoValue &v5, UAutoValue &v6, UAutoValue &v7, UAutoValue &v8)
virtual UObjectMode getRunningMode () const
Return the mode in which the code is running.
virtual std::pair< int, int > kernelVersion () const
Get the kernel major,minor version.
virtual void yield () const
Yield execution until next cycle.
virtual void yield_until (libport::utime_t deadline) const
Yield execution until deadline is met (see libport::utime()).
virtual void yield_until_things_changed () const
Yield execution until something else is scheduled, or until a message is received in remote mode.
virtual void side_effect_free_set (bool s)
If s is true, mark the current task as having no side effect.
virtual bool side_effect_free_get () const
Get the current side_effect_free state.
virtual UVarImpl * getVarImpl ()
virtual UObjectImpl * getObjectImpl ()
virtual UGenericCallbackImpl * getGenericCallbackImpl ()
virtual TimerHandle setTimer (UTimerCallback *cb)
virtual void registerHub (UObjectHub *)
virtual void removeHub (UObjectHub *)
virtual void setHubUpdate (UObjectHub *, ufloat)
virtual void instanciated (UObject *obj)
Called by the urbiStarter after each UObject instanciation.
virtual void lock ()
Request a context lock from another thread to perform multiple operations.
virtual void unlock ()
Release lock acquired with lock().
virtual boost::asio::io_service & getIoService ()
Get the io_service used by this context.
UCallbackAction dispatcher (const UMessage &msg)
Dispatch a message on our connection.
USyncClient * getClient ()
std::string makeRTPLink (const std::string &key)
Make a new RTP link with the engine, using hash key key.
void assignMessage (const std::string &name, const UValue &v, time_t ts)
Handle an assignment request.
void evalFunctionMessage (const std::string &name, const std::string &var, UList &args)
Handle a function call.
TABLE (UTable, accessmap)
TABLE (UTable, eventmap)
TABLE (UTable, eventendmap)
TABLE (UTable, functionmap)
TABLE (UTable, monitormap)
TABLE (UVarTable, varmap)
TABLE (UTimerTable, timermap)
UValue localCall (const std::string &object, const std::string &method, UAutoValue v1=UAutoValue(), UAutoValue v2=UAutoValue(), UAutoValue v3=UAutoValue(), UAutoValue v4=UAutoValue(), UAutoValue v5=UAutoValue(), UAutoValue v6=UAutoValue(), UAutoValue v7=UAutoValue(), UAutoValue v8=UAutoValue())
UTable & tableByName (const std::string &n)
UCallbackAction clientError (const UMessage &)
UObject * getDummyUObject ()
void onTimer (UTimerCallback *cb)
Public Attributes
USyncClient * client_
bool closed_
True if we received a clientError message.
UObject * dummyUObject
TimerMap timerMap
libport::Lockable mapLock
RTPLinks rtpLinks
bool enableRTP
unsigned int dispatchDepth
bool dataSent
Detailed Description
Definition at line 20 of file remote-ucontext-impl.hh.
Member Typedef Documentation
typedef boost::unordered_map<std::string, UObject*> urbi::impl::RemoteUContextImpl::RTPLinks
Definition at line 134 of file remote-ucontext-impl.hh.
typedef boost::unordered_map<std::string, std::pair<libport::AsyncCallHandler, UTimerCallback*> > urbi::impl::RemoteUContextImpl::TimerMap
Definition at line 130 of file remote-ucontext-impl.hh.
Constructor & Destructor Documentation
urbi::impl::RemoteUContextImpl::RemoteUContextImpl (USyncClient * client)
Setup to work on given client.
Definition at line 108 of file uobject.cc.
References urbi::callback(), client_, clientError(), dispatcher(), urbi::externalModuleTag, GET, urbi::UAbstractClient::setCallback(), and urbi::UAbstractClient::setClientErrorCallback().
urbi::impl::RemoteUContextImpl::~RemoteUContextImpl () [virtual]
Definition at line 138 of file uobject.cc.
Member Function Documentation
void urbi::impl::RemoteUContextImpl::assignMessage (const std::string & name, const UValue & v, time_t ts)
Handle an assignment request.
Definition at line 499 of file uobject.cc.
References urbi::UList::array, urbi::UGenericCallback::eval(), urbi::UVar::impl_, and urbi::UGenericCallback::target.
Referenced by dispatcher(), and urbi::impl::RemoteUVarImpl::set().
void urbi::impl::RemoteUContextImpl::call (const std::string & object, const std::string & method, UAutoValue v1 = UAutoValue(), UAutoValue v2 = UAutoValue(), UAutoValue v3 = UAutoValue(), UAutoValue v4 = UAutoValue(), UAutoValue v5 = UAutoValue(), UAutoValue v6 = UAutoValue(), UAutoValue v7 = UAutoValue(), UAutoValue v8 = UAutoValue()) [virtual]
Implements urbi::impl::UContextImpl.
Definition at line 615 of file uobject.cc.
References CHECK, client_, urbi::DATA_VOID, dataSent, urbi::UValue::type, and URBI_SEND_COMMA_COMMAND_C.
UCallbackAction urbi::impl::RemoteUContextImpl::clientError (const UMessage &)
Definition at line 746 of file uobject.cc.
References closed_, urbi::impl::UContextImpl::hubs, and urbi::impl::UContextImpl::objects.
Referenced by RemoteUContextImpl().
void urbi::impl::RemoteUContextImpl::declare_event (const UEvent * owner) [virtual]
Implements urbi::impl::UContextImpl.
Definition at line 641 of file uobject.cc.
References client_, dataSent, and URBI_SEND_PIPED_COMMAND_C.
UCallbackAction urbi::impl::RemoteUContextImpl::dispatcher (const UMessage & msg)
Dispatch a message on our connection.
Definition at line 394 of file uobject.cc.
References assignMessage(), client_, closed_, urbi::DATA_DOUBLE, urbi::DATA_LIST, dataSent, dispatchDepth, enableRTP, evalFunctionMessage(), urbi::exit(), urbi::impl::UContextImpl::init(), urbi::UValue::list, urbi::MESSAGE_DATA, urbi::impl::UContextImpl::objects, REQUIRE, urbi::setCurrentContext(), timerMap, urbi::UValue::type, urbi::UMessage::type, urbi::UEM_ASSIGNVALUE, urbi::UEM_DELETE, urbi::UEM_EMITEVENT, urbi::UEM_ENDEVENT, urbi::UEM_EVALFUNCTION, urbi::UEM_INIT, urbi::UEM_NEW, urbi::UEM_NORTP, urbi::UEM_TIMER, URBI_SEND_COMMAND_C, and urbi::UMessage::value.
Referenced by RemoteUContextImpl().
void urbi::impl::RemoteUContextImpl::emit (const std::string & object, UAutoValue & v1, UAutoValue & v2, UAutoValue & v3, UAutoValue & v4, UAutoValue & v5, UAutoValue & v6, UAutoValue & v7, UAutoValue & v8) [virtual]
Implements urbi::impl::UContextImpl.
Definition at line 651 of file uobject.cc.
References CHECK, client_, urbi::DATA_VOID, dataSent, urbi::UValue::type, and URBI_SEND_COMMAND_C.
void urbi::impl::RemoteUContextImpl::evalFunctionMessage (const std::string & name, const std::string & var, UList & args)
Handle a function call.
Parameters:
name function name (should be array[1])
var where to store the result (should be array[2])
args an array which *will* shitfed by 3 to find the function call arguments.
Definition at line 532 of file uobject.cc.
References urbi::impl::call_result(), client_, and urbi::UList::setOffset().
Referenced by dispatcher().
USyncClient * urbi::impl::RemoteUContextImpl::getClient ()
Definition at line 142 of file uobject.cc.
References client_.
Referenced by urbi::impl::RemoteUObjectImpl::onUpdate().
UObject * urbi::impl::RemoteUContextImpl::getDummyUObject ()
Definition at line 148 of file uobject.cc.
References dummyUObject.
UGenericCallbackImpl * urbi::impl::RemoteUContextImpl::getGenericCallbackImpl () [virtual]
Implements urbi::impl::UContextImpl.
Definition at line 722 of file uobject.cc.
boost::asio::io_service & urbi::impl::RemoteUContextImpl::getIoService () [virtual]
Get the io_service used by this context.
Implements urbi::impl::UContextImpl.
Definition at line 219 of file uobject.cc.
References client_.
UObjectImpl * urbi::impl::RemoteUContextImpl::getObjectImpl () [virtual]
Implements urbi::impl::UContextImpl.
Definition at line 716 of file uobject.cc.
UObjectMode urbi::impl::RemoteUContextImpl::getRunningMode () const [virtual]
Return the mode in which the code is running.
Implements urbi::impl::UContextImpl.
Definition at line 170 of file uobject.cc.
UVarImpl * urbi::impl::RemoteUContextImpl::getVarImpl () [virtual]
Implements urbi::impl::UContextImpl.
Definition at line 710 of file uobject.cc.
void urbi::impl::RemoteUContextImpl::instanciated (UObject *) [virtual]
Called by the urbiStarter after each UObject instanciation.
Implements urbi::impl::UContextImpl.
Definition at line 201 of file uobject.cc.
References send().
std::pair< int, int > urbi::impl::RemoteUContextImpl::kernelVersion () const [virtual]
Get the kernel major,minor version.
Implements urbi::impl::UContextImpl.
Definition at line 193 of file uobject.cc.
References client_, urbi::UAbstractClient::kernelMajor(), urbi::UAbstractClient::kernelMinor(), and urbi::USyncClient::waitForKernelVersion().
UValue urbi::impl::RemoteUContextImpl::localCall (const std::string & object, const std::string & method, UAutoValue v1 = UAutoValue(), UAutoValue v2 = UAutoValue(), UAutoValue v3 = UAutoValue(), UAutoValue v4 = UAutoValue(), UAutoValue v5 = UAutoValue(), UAutoValue v6 = UAutoValue(), UAutoValue v7 = UAutoValue(), UAutoValue v8 = UAutoValue())
Definition at line 677 of file uobject.cc.
References urbi::UList::array, urbi::DATA_VOID, and urbi::name().
Referenced by makeRTPLink(), and urbi::impl::RemoteUVarImpl::set().
void urbi::impl::RemoteUContextImpl::lock () [virtual]
Request a context lock from another thread to perform multiple operations.
Implements urbi::impl::UContextImpl.
Definition at line 209 of file uobject.cc.
std::string urbi::impl::RemoteUContextImpl::makeRTPLink (const std::string & key)
Make a new RTP link with the engine, using hash key key.
Returns:
the local UObject name
Definition at line 136 of file uvar.cc.
References client_, urbi::DATA_DOUBLE, enableRTP, urbi::impl::UContextImpl::getUObject(), urbi::baseURBIStarter::instanciate(), localCall(), urbi::MESSAGE_DATA, urbi::impl::UContextImpl::objects, urbi::impl::rtp_id(), rtpLinks, urbi::USyncClient::syncGet(), urbi::UValue::type, urbi::UMessage::type, urbi::UValue::val, and urbi::UMessage::value.
Referenced by urbi::impl::RemoteUVarImpl::set().
void urbi::impl::RemoteUContextImpl::newUObjectClass (baseURBIStarter * s) [virtual]
Called to instanciate the first Object of class.
Implements urbi::impl::UContextImpl.
Definition at line 547 of file uobject.cc.
References urbi::baseURBIStarter::instanciate().
void urbi::impl::RemoteUContextImpl::newUObjectHubClass (baseURBIStarterHub * s) [virtual]
Implements urbi::impl::UContextImpl.
Definition at line 552 of file uobject.cc.
References urbi::baseURBIStarterHub::instanciate().
void urbi::impl::RemoteUContextImpl::onTimer (UTimerCallback * cb)
Definition at line 575 of file uobject.cc.
References client_, urbi::externalModuleTag, mapLock, urbi::USyncClient::notifyCallbacks(), urbi::UTimerCallback::period, timerMap, and urbi::UEM_TIMER.
Referenced by setTimer().
void urbi::impl::RemoteUContextImpl::registerHub (UObjectHub *) [virtual]
Reimplemented from urbi::impl::UContextImpl.
Definition at line 741 of file uobject.cc.
void urbi::impl::RemoteUContextImpl::removeHub (UObjectHub *) [virtual]
Implements urbi::impl::UContextImpl.
Definition at line 737 of file uobject.cc.
void urbi::impl::RemoteUContextImpl::send (const char * str) [virtual]
Send the string to the connection hosting the UObject.
Implements urbi::impl::UContextImpl.
Definition at line 160 of file uobject.cc.
References client_.
Referenced by instanciated().
void urbi::impl::RemoteUContextImpl::send (const void * buf, size_t size) [virtual]
Send buf to the connection hosting the UObject.
Implements urbi::impl::UContextImpl.
Definition at line 165 of file uobject.cc.
References client_.
void urbi::impl::RemoteUContextImpl::setHubUpdate (UObjectHub * , ufloat) [virtual]
Implements urbi::impl::UContextImpl.
Definition at line 732 of file uobject.cc.
TimerHandle urbi::impl::RemoteUContextImpl::setTimer (UTimerCallback * cb) [virtual]
Implements urbi::impl::UContextImpl.
Definition at line 561 of file uobject.cc.
References urbi::UTimerCallback::call(), mapLock, onTimer(), urbi::UTimerCallback::period, and timerMap.
bool urbi::impl::RemoteUContextImpl::side_effect_free_get () const [virtual]
Get the current side_effect_free state.
Implements urbi::impl::UContextImpl.
Definition at line 339 of file uobject.cc.
void urbi::impl::RemoteUContextImpl::side_effect_free_set (bool s) [virtual]
If s is true, mark the current task as having no side effect.
This call has no effect in remote mode.
Implements urbi::impl::UContextImpl.
Definition at line 336 of file uobject.cc.
urbi::impl::RemoteUContextImpl::TABLE (UTable , eventmap)
urbi::impl::RemoteUContextImpl::TABLE (UTable , functionmap)
urbi::impl::RemoteUContextImpl::TABLE (UTimerTable , timermap)
urbi::impl::RemoteUContextImpl::TABLE (UTable , accessmap)
urbi::impl::RemoteUContextImpl::TABLE (UTable , monitormap)
urbi::impl::RemoteUContextImpl::TABLE (UTable , eventendmap)
urbi::impl::RemoteUContextImpl::TABLE (UVarTable , varmap)
UTable & urbi::impl::RemoteUContextImpl::tableByName (const std::string & n)
Definition at line 176 of file uobject.cc.
References CHECK.
void urbi::impl::RemoteUContextImpl::unlock () [virtual]
Release lock acquired with lock().
Implements urbi::impl::UContextImpl.
Definition at line 214 of file uobject.cc.
void urbi::impl::RemoteUContextImpl::uobject_unarmorAndSend (const char * str) [virtual]
Send Urbi code (ghost connection in plugin mode, default connection in remote mode).
Implements urbi::impl::UContextImpl.
Definition at line 155 of file uobject.cc.
References client_, and urbi::unarmorAndSend().
void urbi::impl::RemoteUContextImpl::yield () const [virtual]
Yield execution until next cycle.
Process pending messages in remote mode.
Implements urbi::impl::UContextImpl.
Definition at line 307 of file uobject.cc.
References yield_until().
void urbi::impl::RemoteUContextImpl::yield_until (libport::utime_t deadline) const [virtual]
Yield execution until deadline is met (see libport::utime()).
Implements urbi::impl::UContextImpl.
Definition at line 312 of file uobject.cc.
References client_.
Referenced by yield().
void urbi::impl::RemoteUContextImpl::yield_until_things_changed () const [virtual]
Yield execution until something else is scheduled, or until a message is received in remote mode.
Implements urbi::impl::UContextImpl.
Definition at line 326 of file uobject.cc.
References client_.
Member Data Documentation
USyncClient* urbi::impl::RemoteUContextImpl::client_
Definition at line 93 of file remote-ucontext-impl.hh.
Referenced by call(), declare_event(), dispatcher(), emit(), evalFunctionMessage(), getClient(), getIoService(), urbi::impl::RemoteUVarImpl::initialize(), kernelVersion(), makeRTPLink(), onTimer(), urbi::impl::RemoteUObjectImpl::onUpdate(), RemoteUContextImpl(), send(), urbi::impl::RemoteUVarImpl::set(), uobject_unarmorAndSend(), yield_until(), and yield_until_things_changed().
bool urbi::impl::RemoteUContextImpl::closed_
True if we received a clientError message.
Definition at line 96 of file remote-ucontext-impl.hh.
Referenced by clientError(), and dispatcher().
bool urbi::impl::RemoteUContextImpl::dataSent
Definition at line 140 of file remote-ucontext-impl.hh.
Referenced by call(), declare_event(), dispatcher(), emit(), urbi::impl::RemoteUVarImpl::initialize(), urbi::impl::RemoteUVarImpl::request(), urbi::impl::RemoteUVarImpl::set(), urbi::impl::RemoteUVarImpl::setProp(), urbi::impl::RemoteUVarImpl::unnotify(), and urbi::impl::RemoteUVarImpl::useRTP().
unsigned int urbi::impl::RemoteUContextImpl::dispatchDepth
Definition at line 138 of file remote-ucontext-impl.hh.
Referenced by dispatcher(), and urbi::impl::RemoteUVarImpl::set().
UObject* urbi::impl::RemoteUContextImpl::dummyUObject
Definition at line 128 of file remote-ucontext-impl.hh.
Referenced by getDummyUObject().
bool urbi::impl::RemoteUContextImpl::enableRTP
Definition at line 137 of file remote-ucontext-impl.hh.
Referenced by dispatcher(), makeRTPLink(), and urbi::impl::RemoteUVarImpl::set().
libport::Lockable urbi::impl::RemoteUContextImpl::mapLock
Definition at line 132 of file remote-ucontext-impl.hh.
Referenced by onTimer(), urbi::impl::RemoteUObjectImpl::removeTimer(), and setTimer().
RTPLinks urbi::impl::RemoteUContextImpl::rtpLinks
Definition at line 135 of file remote-ucontext-impl.hh.
Referenced by makeRTPLink(), and urbi::impl::RemoteUVarImpl::set().
TimerMap urbi::impl::RemoteUContextImpl::timerMap
Definition at line 131 of file remote-ucontext-impl.hh.
Referenced by dispatcher(), onTimer(), urbi::impl::RemoteUObjectImpl::removeTimer(), and setTimer().
The documentation for this class was generated from the following files:
remote-ucontext-impl.hh
uobject.cc
uvar.cc