Urbi SDK Remote: urbi::UTimerCallback Class Reference
urbi::UTimerCallback Class Reference
Timer mechanism.
#include <utimer-callback.hh>
Public Member Functions
UTimerCallback (const std::string &objname, ufloat period, impl::UContextImpl *ctx)
virtual ~UTimerCallback ()
virtual void call ()=0
void registerCallback ()
TimerHandle handle_get ()
Public Attributes
ufloat period
ufloat lastTimeCalled
std::string objname
Private Attributes
impl::UContextImpl * ctx_
TimerHandle handle_
Detailed Description
Timer mechanism.
This class stores a callback as a class method.
Definition at line 32 of file utimer-callback.hh.
Constructor & Destructor Documentation
urbi::UTimerCallback::UTimerCallback (const std::string & objname, ufloat period, impl::UContextImpl * ctx)
Parameters:
period in milliseconds.
Definition at line 365 of file uobject-common.cc.
References lastTimeCalled.
urbi::UTimerCallback::~UTimerCallback () [virtual]
Definition at line 381 of file uobject-common.cc.
Member Function Documentation
virtual void urbi::UTimerCallback::call () [pure virtual]
Implemented in urbi::UTimerCallbackobj< T >.
Referenced by urbi::impl::RemoteUContextImpl::setTimer().
TimerHandle urbi::UTimerCallback::handle_get () [inline]
Definition at line 43 of file utimer-callback.hh.
void urbi::UTimerCallback::registerCallback ()
Definition at line 376 of file uobject-common.cc.
References ctx_, handle_, and urbi::impl::UContextImpl::setTimer().
Referenced by urbi::UTimerCallbackobj< T >::UTimerCallbackobj().
Member Data Documentation
impl::UContextImpl* urbi::UTimerCallback::ctx_ [private]
Definition at line 48 of file utimer-callback.hh.
Referenced by registerCallback().
TimerHandle urbi::UTimerCallback::handle_ [private]
Definition at line 49 of file utimer-callback.hh.
Referenced by registerCallback().
ufloat urbi::UTimerCallback::lastTimeCalled
Definition at line 45 of file utimer-callback.hh.
Referenced by UTimerCallback().
std::string urbi::UTimerCallback::objname
Definition at line 46 of file utimer-callback.hh.
ufloat urbi::UTimerCallback::period
Definition at line 44 of file utimer-callback.hh.
Referenced by urbi::impl::RemoteUContextImpl::onTimer(), and urbi::impl::RemoteUContextImpl::setTimer().
The documentation for this class was generated from the following files:
utimer-callback.hh
uobject-common.cc