Urbi SDK Remote: urbi::UCallback6< OBJ, R, P1, P2, P3, P4, P5, P6 > Class Template Reference
urbi::UCallback6< OBJ, R, P1, P2, P3, P4, P5, P6 > Class Template Reference
#include <ucallbacks.hh>
Public Member Functions
MKUCallBackNotifyCtr6 (, false)
MKUCallBackNotifyCtr6 (const, true)
virtual UValue __evalcall (UList &param)
Private Attributes
OBJ * obj
R(OBJ::* fun)(P1, P2, P3, P4, P5, P6)
R(OBJ::* funconst)(P1, P2, P3, P4, P5, P6) const
bool is_const_
Detailed Description
template<class OBJ, class R, class P1, class P2, class P3, class P4, class P5, class P6>
class urbi::UCallback6< OBJ, R, P1, P2, P3, P4, P5, P6 >
Definition at line 1273 of file ucallbacks.hh.
Member Function Documentation
template<class OBJ , class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > virtual UValue urbi::UCallback6< OBJ, R, P1, P2, P3, P4, P5, P6 >::__evalcall (UList & param) [inline, virtual]
Implements urbi::UGenericCallback.
Definition at line 1299 of file ucallbacks.hh.
References urbi::UContext::ctx_, urbi::UCallback6< OBJ, R, P1, P2, P3, P4, P5, P6 >::fun, urbi::UCallback6< OBJ, R, P1, P2, P3, P4, P5, P6 >::funconst, urbi::UCallback6< OBJ, R, P1, P2, P3, P4, P5, P6 >::is_const_, and urbi::uvar_uvalue_cast().
template<class OBJ , class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > urbi::UCallback6< OBJ, R, P1, P2, P3, P4, P5, P6 >::MKUCallBackNotifyCtr6 (false)
template<class OBJ , class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > urbi::UCallback6< OBJ, R, P1, P2, P3, P4, P5, P6 >::MKUCallBackNotifyCtr6 (const , true)
Member Data Documentation
template<class OBJ , class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > R(OBJ::* urbi::UCallback6< OBJ, R, P1, P2, P3, P4, P5, P6 >::fun)(P1, P2, P3, P4, P5, P6) [private]
Definition at line 1314 of file ucallbacks.hh.
Referenced by urbi::UCallback6< OBJ, R, P1, P2, P3, P4, P5, P6 >::__evalcall().
template<class OBJ , class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > R(OBJ::* urbi::UCallback6< OBJ, R, P1, P2, P3, P4, P5, P6 >::funconst)(P1, P2, P3, P4, P5, P6) const [private]
Definition at line 1315 of file ucallbacks.hh.
Referenced by urbi::UCallback6< OBJ, R, P1, P2, P3, P4, P5, P6 >::__evalcall().
template<class OBJ , class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > bool urbi::UCallback6< OBJ, R, P1, P2, P3, P4, P5, P6 >::is_const_ [private]
Definition at line 1316 of file ucallbacks.hh.
Referenced by urbi::UCallback6< OBJ, R, P1, P2, P3, P4, P5, P6 >::__evalcall().
template<class OBJ , class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > OBJ* urbi::UCallback6< OBJ, R, P1, P2, P3, P4, P5, P6 >::obj [private]
Definition at line 1313 of file ucallbacks.hh.
The documentation for this class was generated from the following file:
ucallbacks.hh