Urbi SDK Remote: urbi::UObject Class Reference
urbi::UObject Class Reference
Main UObject class definition Each UObject instance corresponds to an URBI object.
#include <uobject.hh>
Public Member Functions
UObject (const std::string &, impl::UContextImpl *impl=0)
UObject constructor.
UObject (int, impl::UContextImpl *impl=0)
Reserved for internal use.
virtual ~UObject ()
UObject destructor.
void UNotifyChange (UVar &v, void(UObject::*fun)(UVar &))
Call a function each time a variable is modified.
template<typename T >
void UNotifyChange (UVar &v, void(UObject::*fun)(T))
UnotifyChange() variant that passes the UVar value as argument to your callback function.
void UNotifyThreadedChange (UVar &v, void(UObject::*fun)(UVar &), LockMode m)
Similar to UNotifyChange(), but run function in a thread.
void UNotifyAccess (UVar &v, void(UObject::*fun)(UVar &))
Call a function each time a variable is accessed.
void UNotifyThreadedAccess (UVar &v, void(UObject::*fun)(UVar &), LockMode m)
template<class T >
TimerHandle USetTimer (ufloat t, void(T::*fun)())
Call fun every t milliseconds.
void USync (UVar &v)
Request permanent synchronization for v.
void USetUpdate (ufloat period)
Set a timer that will call the update function every 'period' milliseconds.
virtual int update ()
int voidfun ()
Void function used in USync callbacks.
void clean ()
Remove all bindings, this method is called by the destructor.
libport::ThreadPool::rTaskLock getTaskLock (LockMode m, const std::string &what)
Find the TaskLock associated with lock mode m.
impl::UObjectImpl * impl_get ()
virtual
libport::ThreadPool::rTaskLock getClassTaskLock ()
Public Attributes
std::string __name
Name of the object as seen in Urbi.
std::string classname
Name of the class the object is derived from.
bool derived
True when the object has been newed by an urbi command.
UObjectList members
UObjectHub * objecthub
The hub, if it exists.
bool remote
Flag to know whether the UObject is in remote mode or not.
UVar load
The load attribute is standard and can be used to control the activity of the object.
baseURBIStarter * cloner
Private Attributes
UObjectData * objectData
Pointer to a globalData structure specific to the remote/plugin architectures who defines it.
impl::UObjectImpl * impl_
boost::unordered_map
< std::string,
libport::ThreadPool::rTaskLock > taskLocks_
libport::ThreadPool::rTaskLock taskLock_
Instance task lock.
Autogroup.
These functions are obsoleted, they are not supported in Urbi SDK 2.0.
URBI_SDK_DEPRECATED bool autogroup
Add a group with a 's' after the base class name.
URBI_SDK_DEPRECATED void UAutoGroup ()
virtual URBI_SDK_DEPRECATED void addAutoGroup ()
Called when a subclass is created if autogroup is true.
virtual URBI_SDK_DEPRECATED void UJoinGroup (const std::string &gpname)
Join the uobject to the 'gpname' group.
Detailed Description
Main UObject class definition Each UObject instance corresponds to an URBI object.
It provides mechanisms to bind variables and functions between C++ and Urbi.
Definition at line 254 of file uobject.hh.
Constructor & Destructor Documentation
urbi::UObject::UObject (const std::string & s, impl::UContextImpl * impl = 0)
UObject constructor.
Definition at line 202 of file uobject-common.cc.
References __name, autogroup, impl_, urbi::UVar::init(), urbi::impl::UObjectImpl::initialize(), load, and objecthub.
urbi::UObject::UObject (int , impl::UContextImpl * impl = 0)
Reserved for internal use.
Definition at line 187 of file uobject-common.cc.
References impl_, urbi::impl::UObjectImpl::initialize(), and objecthub.
urbi::UObject::~UObject () [virtual]
UObject destructor.
Definition at line 236 of file uobject-common.cc.
References clean(), and impl_.
Member Function Documentation
void urbi::UObject::addAutoGroup () [virtual]
Called when a subclass is created if autogroup is true.
Definition at line 224 of file uobject-common.cc.
References classname, and UJoinGroup().
void urbi::UObject::clean () [inline]
Remove all bindings, this method is called by the destructor.
Definition at line 42 of file uobject.hxx.
References urbi::impl::UObjectImpl::clean(), and impl_.
Referenced by ~UObject().
libport::ThreadPool::rTaskLock urbi::UObject::getClassTaskLock () [virtual]
Definition at line 250 of file uobject-common.cc.
Referenced by getTaskLock().
libport::ThreadPool::rTaskLock urbi::UObject::getTaskLock (LockMode m, const std::string & what) [inline]
Find the TaskLock associated with lock mode m.
Definition at line 79 of file uobject.hxx.
References getClassTaskLock(), urbi::LOCK_CLASS, urbi::LOCK_FUNCTION, urbi::LOCK_INSTANCE, urbi::LOCK_MODULE, urbi::LOCK_NONE, taskLock_, and taskLocks_.
impl::UObjectImpl * urbi::UObject::impl_get () [inline]
Definition at line 72 of file uobject.hxx.
References impl_.
void urbi::UObject::UAutoGroup ()
Definition at line 230 of file uobject-common.cc.
References autogroup.
void urbi::UObject::UJoinGroup (const std::string & gpname) [virtual]
Join the uobject to the 'gpname' group.
Definition at line 243 of file uobject-common.cc.
References __name, and urbi::UContext::send().
Referenced by addAutoGroup().
int urbi::UObject::update () [inline, virtual]
Definition at line 28 of file uobject.hxx.
Referenced by urbi::impl::RemoteUObjectImpl::initialize().
template<class T > TimerHandle urbi::UObject::USetTimer (ufloat t, void(T::*)() fun)
Call fun every t milliseconds.
void urbi::UObject::USetUpdate (ufloat period) [inline]
Set a timer that will call the update function every 'period' milliseconds.
Definition at line 50 of file uobject.hxx.
References impl_, and urbi::impl::UObjectImpl::setUpdate().
void urbi::UObject::USync (UVar & v) [inline]
Request permanent synchronization for v.
Definition at line 58 of file uobject.hxx.
References urbi::UVar::keepSynchronized().
int urbi::UObject::voidfun () [inline]
Void function used in USync callbacks.
Definition at line 35 of file uobject.hxx.
Member Data Documentation
std::string urbi::UObject::__name
Name of the object as seen in Urbi.
Definition at line 388 of file uobject.hh.
Referenced by urbi::impl::RemoteUObjectImpl::clean(), urbi::impl::RemoteUObjectImpl::initialize(), urbi::impl::RemoteUObjectImpl::onUpdate(), urbi::operator,(), urbi::impl::UContextImpl::registerObject(), UJoinGroup(), and UObject().
URBI_SDK_DEPRECATED bool urbi::UObject::autogroup
Add a group with a 's' after the base class name.
Definition at line 428 of file uobject.hh.
Referenced by UAutoGroup(), and UObject().
std::string urbi::UObject::classname
Name of the class the object is derived from.
Definition at line 390 of file uobject.hh.
Referenced by addAutoGroup().
baseURBIStarter* urbi::UObject::cloner
Definition at line 449 of file uobject.hh.
Referenced by urbi::URBIStarter< T >::instanciate().
bool urbi::UObject::derived
True when the object has been newed by an urbi command.
Definition at line 392 of file uobject.hh.
impl::UObjectImpl* urbi::UObject::impl_ [private]
Definition at line 460 of file uobject.hh.
Referenced by clean(), impl_get(), UObject(), USetUpdate(), and ~UObject().
UVar urbi::UObject::load
The load attribute is standard and can be used to control the activity of the object.
Definition at line 447 of file uobject.hh.
Referenced by UObject().
UObjectList urbi::UObject::members
Definition at line 394 of file uobject.hh.
UObjectData* urbi::UObject::objectData [private]
Pointer to a globalData structure specific to the remote/plugin architectures who defines it.
Definition at line 458 of file uobject.hh.
UObjectHub* urbi::UObject::objecthub
The hub, if it exists.
Definition at line 397 of file uobject.hh.
Referenced by urbi::impl::RemoteUObjectImpl::clean(), and UObject().
bool urbi::UObject::remote
Flag to know whether the UObject is in remote mode or not.
Definition at line 436 of file uobject.hh.
libport::ThreadPool::rTaskLock urbi::UObject::taskLock_ [private]
Instance task lock.
Definition at line 464 of file uobject.hh.
Referenced by getTaskLock().
boost::unordered_map<std::string, libport::ThreadPool::rTaskLock> urbi::UObject::taskLocks_ [private]
Definition at line 462 of file uobject.hh.
Referenced by getTaskLock().
The documentation for this class was generated from the following files:
uobject.hh
uobject-common.cc
uobject.hxx