Urbi SDK Remote: urbi::UList Class Reference
urbi::UList Class Reference
Class storing URBI List type.
#include <uvalue.hh>
Public Member Functions
UList ()
UList (const UList &b)
~UList ()
UList & operator= (const UList &b)
template<typename T >
UList & operator= (const T &container)
UList & operator= (UVar &v)
template<typename T >
T as ()
template<typename T >
UList & push_back (const T &v)
void pop_back ()
UValue & front ()
UValue & operator[] (size_t i)
const UValue & operator[] (size_t i) const
size_t size () const
void setOffset (size_t n)
std::ostream & print (std::ostream &o) const
Public Attributes
std::vector< UValue * > array
Private Member Functions
void clear ()
Private Attributes
size_t offset
Detailed Description
Class storing URBI List type.
Definition at line 55 of file uvalue.hh.
Constructor & Destructor Documentation
urbi::UList::UList ()
Definition at line 636 of file uvalue-common.cc.
urbi::UList::UList (const UList & b)
Definition at line 640 of file uvalue-common.cc.
urbi::UList::~UList ()
Definition at line 657 of file uvalue-common.cc.
References clear().
Member Function Documentation
template<typename T > T urbi::UList::as ()
Definition at line 375 of file uvalue.hxx.
References array.
void urbi::UList::clear () [private]
Definition at line 662 of file uvalue-common.cc.
References array, and offset.
Referenced by operator=(), and ~UList().
UValue & urbi::UList::front () [inline]
Definition at line 65 of file uvalue.hxx.
References array.
UList & urbi::UList::operator= (const UList & b)
Definition at line 646 of file uvalue-common.cc.
References array, clear(), and offset.
template<typename T > UList & urbi::UList::operator= (const T & container)
Definition at line 361 of file uvalue.hxx.
References array.
UList & urbi::UList::operator= (UVar & v)
Definition at line 141 of file uvar-common.cc.
References urbi::UVar::val().
UValue& urbi::UList::operator[] (size_t i)
const UValue& urbi::UList::operator[] (size_t i) const
void urbi::UList::pop_back () [inline]
Definition at line 72 of file uvalue.hxx.
References array.
std::ostream & urbi::UList::print (std::ostream & o) const
Definition at line 671 of file uvalue-common.cc.
References size().
template<typename T > UList & urbi::UList::push_back (const T & v)
Definition at line 57 of file uvalue.hxx.
References array.
Referenced by urbi::impl::RemoteUObjectImpl::onUpdate().
void urbi::UList::setOffset (size_t n) [inline]
Definition at line 50 of file uvalue.hxx.
References offset.
Referenced by urbi::impl::RemoteUContextImpl::evalFunctionMessage().
size_t urbi::UList::size () const [inline]
Definition at line 43 of file uvalue.hxx.
References array.
Referenced by print(), and urbi::UAbstractClient::send().
Member Data Documentation
std::vector<UValue*> urbi::UList::array
Definition at line 92 of file uvalue.hh.
Referenced by as(), urbi::impl::RemoteUContextImpl::assignMessage(), clear(), front(), urbi::impl::RemoteUContextImpl::localCall(), operator=(), urbi::UValue::parse(), pop_back(), push_back(), and size().
size_t urbi::UList::offset [private]
Definition at line 96 of file uvalue.hh.
Referenced by clear(), operator=(), and setOffset().
The documentation for this class was generated from the following files:
uvalue.hh
uvar-common.cc
uvalue-common.cc
uvalue.hxx