Urbi SDK Remote: UrbiRoot Class Reference
UrbiRoot Class Reference
#include <urbi-root.hh>
Public Member Functions
UrbiRoot (const std::string &program, bool static_build=false)
Load an Urbi SDK.
int urbi_launch (int argc, const char **argv)
int urbi_launch (int argc, char **argv)
int urbi_main (const std::vector< std::string > &args, bool block, bool errors)
void load_plugin ()
void load_remote ()
Location of Urbi remote libuobject.
void load_custom (const std::string &path)
const std::string & root () const
Root of the Urbi installation.
std::string core_path () const
Plugin and remote libuobjects parent directory.
std::string share_path () const
Share location. Contains Urbi scripts in the urbi/ subdirectory.
std::vector< std::string > uobjects_path () const
Standard uobjects directories.
Private Member Functions
RTLD_HANDLE library_load (const std::string &base, const std::string &env_suffix="")
Load the library "${libdir}/${base}${ext}", unless the envvar named "URBI_ROOT_LIB${BASE}" points to another location.
Private Attributes
std::string program_
std::string root_
RTLD_HANDLE handle_libjpeg_
RTLD_HANDLE handle_libport_
RTLD_HANDLE handle_libsched_
RTLD_HANDLE handle_libserialize_
RTLD_HANDLE handle_liburbi_
RTLD_HANDLE handle_libuobject_
Detailed Description
Definition at line 34 of file urbi-root.hh.
Constructor & Destructor Documentation
UrbiRoot::UrbiRoot (const std::string & program, bool static_build = false)
Load an Urbi SDK.
Parameters:
program The command used to invoke urbi-launch or urbi.
static_build true if this is a static build:do not dlopen anything
Definition at line 267 of file liburbi/urbi-root.cc.
References handle_libjpeg_, handle_libport_, handle_libsched_, handle_libserialize_, handle_liburbi_, library_load(), mygetenv(), program_, resolve_symlinks(), root_, split(), urbi_getenv(), URBI_ROOT_DEBUG, and URBI_ROOT_FATAL.
Member Function Documentation
std::string UrbiRoot::core_path () const
Plugin and remote libuobjects parent directory.
Definition at line 398 of file liburbi/urbi-root.cc.
References root().
Referenced by load_plugin(), load_remote(), and uobjects_path().
RTLD_HANDLE UrbiRoot::library_load (const std::string & base, const std::string & env_suffix = "") [private]
Load the library "${libdir}/${base}${ext}", unless the envvar named "URBI_ROOT_LIB${BASE}" points to another location.
Definition at line 374 of file liburbi/urbi-root.cc.
References libdir, program_, root(), urbi_getenv(), and xdlopen().
Referenced by UrbiRoot().
void UrbiRoot::load_custom (const std::string & path)
Definition at line 446 of file liburbi/urbi-root.cc.
References handle_libuobject_, program_, and xdlopen().
Referenced by urbi_launch_().
void UrbiRoot::load_plugin ()
Definition at line 420 of file liburbi/urbi-root.cc.
References core_path(), handle_libuobject_, program_, urbi_getenv(), and xdlopen().
Referenced by urbi_launch_().
void UrbiRoot::load_remote ()
Location of Urbi remote libuobject.
Definition at line 435 of file liburbi/urbi-root.cc.
References core_path(), handle_libuobject_, program_, urbi_getenv(), and xdlopen().
Referenced by urbi_launch_().
const std::string & UrbiRoot::root () const
Root of the Urbi installation.
Definition at line 392 of file liburbi/urbi-root.cc.
References root_.
Referenced by core_path(), library_load(), and share_path().
std::string UrbiRoot::share_path () const
Share location. Contains Urbi scripts in the urbi/ subdirectory.
Definition at line 414 of file liburbi/urbi-root.cc.
References root().
std::vector< std::string > UrbiRoot::uobjects_path () const
Standard uobjects directories.
Definition at line 404 of file liburbi/urbi-root.cc.
References core_path().
Referenced by urbi_launch_().
int UrbiRoot::urbi_launch (int argc, char ** argv)
Definition at line 467 of file liburbi/urbi-root.cc.
References urbi_launch().
int UrbiRoot::urbi_launch (int argc, const char ** argv)
Definition at line 457 of file liburbi/urbi-root.cc.
References handle_liburbi_, and program_.
Referenced by main(), and urbi_launch().
int UrbiRoot::urbi_main (const std::vector< std::string > & args, bool block, bool errors)
Definition at line 476 of file liburbi/urbi-root.cc.
References handle_libuobject_, program_, urbi_main_args(), and URBI_ROOT_DEBUG.
Referenced by urbi_launch_().
Member Data Documentation
RTLD_HANDLE UrbiRoot::handle_libjpeg_ [private]
Definition at line 84 of file urbi-root.hh.
Referenced by UrbiRoot().
RTLD_HANDLE UrbiRoot::handle_libport_ [private]
Definition at line 85 of file urbi-root.hh.
Referenced by UrbiRoot().
RTLD_HANDLE UrbiRoot::handle_libsched_ [private]
Definition at line 86 of file urbi-root.hh.
Referenced by UrbiRoot().
RTLD_HANDLE UrbiRoot::handle_libserialize_ [private]
Definition at line 87 of file urbi-root.hh.
Referenced by UrbiRoot().
RTLD_HANDLE UrbiRoot::handle_libuobject_ [private]
Definition at line 89 of file urbi-root.hh.
Referenced by load_custom(), load_plugin(), load_remote(), and urbi_main().
RTLD_HANDLE UrbiRoot::handle_liburbi_ [private]
Definition at line 88 of file urbi-root.hh.
Referenced by urbi_launch(), and UrbiRoot().
std::string UrbiRoot::program_ [private]
Definition at line 82 of file urbi-root.hh.
Referenced by library_load(), load_custom(), load_plugin(), load_remote(), urbi_launch(), urbi_main(), and UrbiRoot().
std::string UrbiRoot::root_ [private]
Definition at line 83 of file urbi-root.hh.
Referenced by root(), and UrbiRoot().
The documentation for this class was generated from the following files:
urbi-root.hh
liburbi/urbi-root.cc