Urbi SDK Remote: urbi::baseURBIStarterHub Class Reference
urbi::baseURBIStarterHub Class Reference
URBIStarter base class used to store heterogeneous template class objects in starterlist.
#include <ustarter.hh>
Public Types
typedef std::list
< baseURBIStarterHub * > list_type
UObjectHub list.
Public Member Functions
baseURBIStarterHub (const std::string &name)
virtual ~baseURBIStarterHub ()
virtual UObjectHub * instanciate (impl::UContextImpl *ctx, const std::string &n=std::string())=0
Used to provide a wrapper to initialize objects in starterlist.
Static Public Member Functions
static list_type & list ()
Public Attributes
std::string name
Detailed Description
URBIStarter base class used to store heterogeneous template class objects in starterlist.
Definition at line 98 of file ustarter.hh.
Member Typedef Documentation
typedef std::list<baseURBIStarterHub*> urbi::baseURBIStarterHub::list_type
UObjectHub list.
Definition at line 110 of file ustarter.hh.
Constructor & Destructor Documentation
urbi::baseURBIStarterHub::baseURBIStarterHub (const std::string & name) [inline]
Definition at line 78 of file ustarter.hxx.
urbi::baseURBIStarterHub::~baseURBIStarterHub () [inline, virtual]
Definition at line 83 of file ustarter.hxx.
Member Function Documentation
virtual UObjectHub* urbi::baseURBIStarterHub::instanciate (impl::UContextImpl * ctx, const std::string & n = std::string()) [pure virtual]
Used to provide a wrapper to initialize objects in starterlist.
Implemented in urbi::URBIStarterHub< T >.
Referenced by urbi::impl::RemoteUContextImpl::newUObjectHubClass().
baseURBIStarterHub::list_type & urbi::baseURBIStarterHub::list () [static]
Definition at line 34 of file ustarter.cc.
Referenced by urbi::impl::UContextImpl::init(), urbi::URBIStarterHub< T >::URBIStarterHub(), and urbi::URBIStarterHub< T >::~URBIStarterHub().
Member Data Documentation
std::string urbi::baseURBIStarterHub::name
Definition at line 107 of file ustarter.hh.
Referenced by urbi::impl::UContextImpl::init(), and urbi::URBIStarterHub< T >::instanciate().
The documentation for this class was generated from the following files:
ustarter.hh
ustarter.cc
ustarter.hxx