Urbi SDK Remote: urbi::impl::UVarImpl Class Reference
urbi::impl::UVarImpl Class Reference
#include <ucontext-impl.hh>
Public Member Functions
virtual ~UVarImpl ()=0
virtual void initialize (UVar *owner)=0
virtual void clean ()=0
virtual void setOwned ()=0
virtual void sync ()=0
virtual void request ()=0
virtual void keepSynchronized ()=0
virtual void set (const UValue &v)=0
virtual const UValue & get () const =0
virtual UDataType type () const =0
virtual UValue getProp (UProperty prop)=0
virtual void setProp (UProperty prop, const UValue &v)=0
virtual bool setBypass (bool enable)=0
virtual time_t timestamp () const =0
virtual void unnotify ()=0
virtual void useRTP (bool enable)=0
Detailed Description
Definition at line 172 of file ucontext-impl.hh.
Constructor & Destructor Documentation
urbi::impl::UVarImpl::~UVarImpl () [inline, pure virtual]
Definition at line 42 of file ucontext-impl.hxx.
Member Function Documentation
virtual void urbi::impl::UVarImpl::clean () [pure virtual]
Implemented in urbi::impl::RemoteUVarImpl.
Referenced by urbi::UVar::~UVar().
virtual const UValue& urbi::impl::UVarImpl::get () const [pure virtual]
Implemented in urbi::impl::RemoteUVarImpl.
Referenced by urbi::UVar::val().
virtual UValue urbi::impl::UVarImpl::getProp (UProperty prop) [pure virtual]
Implemented in urbi::impl::RemoteUVarImpl.
Referenced by urbi::UVar::getProp().
virtual void urbi::impl::UVarImpl::initialize (UVar * owner) [pure virtual]
Implemented in urbi::impl::RemoteUVarImpl.
Referenced by urbi::UVar::__init().
virtual void urbi::impl::UVarImpl::keepSynchronized () [pure virtual]
Implemented in urbi::impl::RemoteUVarImpl.
Referenced by urbi::UVar::keepSynchronized().
virtual void urbi::impl::UVarImpl::request () [pure virtual]
Implemented in urbi::impl::RemoteUVarImpl.
virtual void urbi::impl::UVarImpl::set (const UValue & v) [pure virtual]
Implemented in urbi::impl::RemoteUVarImpl.
Referenced by urbi::UVar::operator=().
virtual bool urbi::impl::UVarImpl::setBypass (bool enable) [pure virtual]
Implemented in urbi::impl::RemoteUVarImpl.
Referenced by urbi::UVar::setBypass().
virtual void urbi::impl::UVarImpl::setOwned () [pure virtual]
Implemented in urbi::impl::RemoteUVarImpl.
Referenced by urbi::UVar::setOwned().
virtual void urbi::impl::UVarImpl::setProp (UProperty prop, const UValue & v) [pure virtual]
Implemented in urbi::impl::RemoteUVarImpl.
Referenced by urbi::UVar::setProp().
virtual void urbi::impl::UVarImpl::sync () [pure virtual]
Implemented in urbi::impl::RemoteUVarImpl.
Referenced by urbi::UVar::syncValue().
virtual time_t urbi::impl::UVarImpl::timestamp () const [pure virtual]
Implemented in urbi::impl::RemoteUVarImpl.
Referenced by urbi::UVar::timestamp().
virtual UDataType urbi::impl::UVarImpl::type () const [pure virtual]
Implemented in urbi::impl::RemoteUVarImpl.
Referenced by urbi::UVar::type().
virtual void urbi::impl::UVarImpl::unnotify () [pure virtual]
Implemented in urbi::impl::RemoteUVarImpl.
Referenced by urbi::UVar::unnotify().
virtual void urbi::impl::UVarImpl::useRTP (bool enable) [pure virtual]
Implemented in urbi::impl::RemoteUVarImpl.
Referenced by urbi::UVar::useRTP().
The documentation for this class was generated from the following files:
ucontext-impl.hh
ucontext-impl.hxx