Urbi SDK Remote: urbi::UObjectHub Class Reference
urbi::UObjectHub Class Reference
Main UObjectHub class definition.
#include <uobject-hub.hh>
Public Member Functions
UObjectHub (const std::string &, impl::UContextImpl *ctx=0)
UObjectHub constructor.
virtual ~UObjectHub ()
void addMember (UObject *obj)
void delMember (UObject *obj)
void USetUpdate (ufloat period)
Set a timer that will call update() every 'period' milliseconds.
virtual int update ()
UObjectList * getSubClass (const std::string &)
const std::string & get_name ()
Public Attributes
UObjectList members
Protected Member Functions
int updateGlobal ()
This function calls update and the subclass update.
Protected Attributes
ufloat period
std::string name
Detailed Description
Main UObjectHub class definition.
Definition at line 22 of file uobject-hub.hh.
Constructor & Destructor Documentation
urbi::UObjectHub::UObjectHub (const std::string & s, impl::UContextImpl * ctx = 0)
UObjectHub constructor.
Definition at line 23 of file uobject-hub-common.cc.
References urbi::UContext::ctx_, and urbi::impl::UContextImpl::registerHub().
urbi::UObjectHub::~UObjectHub () [virtual]
Definition at line 67 of file uobject-hub-common.cc.
References urbi::UContext::ctx_, and urbi::impl::UContextImpl::removeHub().
Member Function Documentation
void urbi::UObjectHub::addMember (UObject * obj)
Definition at line 40 of file uobject-hub-common.cc.
References members.
void urbi::UObjectHub::delMember (UObject * obj)
Definition at line 46 of file uobject-hub-common.cc.
References members.
const std::string& urbi::UObjectHub::get_name () [inline]
Definition at line 39 of file uobject-hub.hh.
Referenced by urbi::impl::UContextImpl::registerHub().
UObjectList * urbi::UObjectHub::getSubClass (const std::string & subclass)
Definition at line 52 of file uobject-hub-common.cc.
References members.
virtual int urbi::UObjectHub::update () [inline, virtual]
Definition at line 34 of file uobject-hub.hh.
Referenced by updateGlobal().
int urbi::UObjectHub::updateGlobal () [protected]
This function calls update and the subclass update.
Definition at line 31 of file uobject-hub-common.cc.
References members, and update().
void urbi::UObjectHub::USetUpdate (ufloat period)
Set a timer that will call update() every 'period' milliseconds.
Definition at line 63 of file uobject-hub-common.cc.
References urbi::UContext::ctx_, and urbi::impl::UContextImpl::setHubUpdate().
Member Data Documentation
UObjectList urbi::UObjectHub::members
Definition at line 36 of file uobject-hub.hh.
Referenced by addMember(), urbi::impl::RemoteUObjectImpl::clean(), delMember(), getSubClass(), and updateGlobal().
std::string urbi::UObjectHub::name [protected]
Definition at line 45 of file uobject-hub.hh.
ufloat urbi::UObjectHub::period [protected]
Definition at line 44 of file uobject-hub.hh.
The documentation for this class was generated from the following files:
uobject-hub.hh
uobject-hub-common.cc