Urbi SDK Remote: urbi::UVar Class Reference
urbi::UVar Class Reference
UVar class definition.
#include <uvar.hh>
Public Types
enum RtpMode { RTP_DEFAULT, RTP_YES, RTP_NO }
Public Member Functions
UVar ()
Creates an unbound UVar. Call init() to bind it.
UVar (const std::string &, impl::UContextImpl *=0)
UVar (const std::string &, const std::string &, impl::UContextImpl *=0)
UVar (UObject &, const std::string &, impl::UContextImpl *=0)
UVar (const UVar &)
~UVar ()
void init (const std::string &varname, impl::UContextImpl *=0)
void init (const std::string &object, const std::string &slot, impl::UContextImpl *=0)
void setOwned ()
UDataType type () const
The type of the current content.
void syncValue ()
Request the current value, wait until it is available.
void keepSynchronized ()
Keep this UVar synchronized with kernel value.
void reset (ufloat)
UVar & operator= (ufloat)
UVar & operator= (const std::string &)
UVar & operator= (const UBinary &)
Deep copy.
UVar & operator= (const UImage &i)
Deep copy.
UVar & operator= (const USound &s)
Deep copy.
UVar & operator= (const UList &l)
UVar & operator= (const UDictionary &d)
UVar & operator= (const UValue &v)
template<typename T >
UVar & operator= (const T &)
template<typename T >
bool operator== (const T &) const
template<typename T >
T as (T *) const
Cast operator taking a dummy value of the target type.
template<typename T >
T as () const
Generic cast operator using the extensible uvalue_cast mechanism.
template<typename T >
T & fill (T &) const
Conveniance wrapper on as().
operator int () const
operator bool () const
operator const UBinary & () const
operator UBinary * () const
Deep copy, binary will have to be deleted by the user.
operator UImage () const
In plugin mode, gives direct access to the buffer, which may not be valid after the calling function returns.
operator USound () const
In plugin mode, gives direct access to the buffer, which may not be valid after the calling function returns.
operator ufloat () const
operator std::string () const
operator UList () const
operator UDictionary () const
void unnotify ()
Deactivate all callbacks associated with this UVar and stop synchro.
ufloat & in ()
Kernel operators.
ufloat & out ()
UValue getProp (UProperty prop)
void setProp (UProperty prop, const UValue &v)
void setProp (UProperty prop, ufloat v)
void setProp (UProperty prop, const char *v)
void setProp (UProperty prop, const std::string &v)
bool setBypass (bool enable=true)
Enable bypass-mode for this UVar.
void useRTP (bool enable=true)
Use RTP mode to transmit this variable if possible.
const UValue & val () const
libport::utime_t timestamp () const
Public Attributes
bool owned
Is the variable owned by the module?
UProp rangemin
Property accessors.
UProp rangemax
UProp speedmin
UProp speedmax
UProp delta
UProp blend
UProp constant
impl::UVarImpl * impl_
Private Member Functions
UVar & operator= (const UVar &)
void check_ () const
Check that impl_ is set or throw a runtime error.
void __init ()
PRIVATE (bool, temp)
Full name of the variable as seen in URBI.
PRIVATE (RtpMode, rtp)
bool invariant () const
Private Attributes
UVardata * vardata
Pointer to internal data specifics.
Friends
class impl::UVarImpl
Detailed Description
UVar class definition.
Each UVar instance corresponds to one URBI variable. The class provides access to the variable properties, and reading/writing the value to/from all known types.
Definition at line 33 of file uvar.hh.
Member Enumeration Documentation
enum urbi::UVar::RtpMode
Enumerator:
RTP_DEFAULT
Use RTP if it is the default mode.
RTP_YES
Force RTP.
RTP_NO
Do not use RTP.
Definition at line 158 of file uvar.hh.
Constructor & Destructor Documentation
urbi::UVar::UVar () [inline]
Creates an unbound UVar. Call init() to bind it.
Definition at line 28 of file uvar.hxx.
urbi::UVar::UVar (const std::string & varname, impl::UContextImpl * impl = 0)
Definition at line 25 of file uvar-common.cc.
References __init().
urbi::UVar::UVar (const std::string & objname, const std::string & varname, impl::UContextImpl * impl = 0)
Definition at line 43 of file uvar-common.cc.
References __init().
urbi::UVar::UVar (UObject & obj, const std::string & varname, impl::UContextImpl * impl = 0)
Definition at line 34 of file uvar-common.cc.
References __init().
urbi::UVar::UVar (const UVar & b)
Definition at line 53 of file uvar-common.cc.
References __init().
urbi::UVar::~UVar ()
Definition at line 105 of file uvar-common.cc.
References urbi::impl::UVarImpl::clean(), impl_, and unnotify().
Member Function Documentation
void urbi::UVar::__init () [private]
Definition at line 92 of file uvar-common.cc.
References urbi::UContext::ctx_, urbi::impl::UContextImpl::getVarImpl(), impl_, urbi::impl::UVarImpl::initialize(), owned, and vardata.
Referenced by init(), and UVar().
template<typename T > T urbi::UVar::as (T *) const
Cast operator taking a dummy value of the target type.
Definition at line 208 of file uvar.hxx.
References urbi::uvalue_cast(), and val().
template<typename T > T urbi::UVar::as () const
Generic cast operator using the extensible uvalue_cast mechanism.
Definition at line 202 of file uvar.hxx.
References urbi::uvalue_cast(), and val().
void urbi::UVar::check_ () const [inline, private]
Check that impl_ is set or throw a runtime error.
Definition at line 188 of file uvar.hxx.
References impl_.
Referenced by getProp(), keepSynchronized(), operator=(), setBypass(), setOwned(), setProp(), syncValue(), timestamp(), type(), unnotify(), and val().
template<typename T > T & urbi::UVar::fill (T & v) const
Conveniance wrapper on as().
Definition at line 214 of file uvar.hxx.
References urbi::uvalue_cast(), and val().
UValue urbi::UVar::getProp (UProperty prop) [inline]
Definition at line 174 of file uvar.hxx.
References check_(), urbi::impl::UVarImpl::getProp(), and impl_.
Referenced by urbi::UProp::operator std::string(), urbi::UProp::operator ufloat(), and urbi::UProp::operator UValue().
ufloat& urbi::UVar::in ()
Kernel operators.
void urbi::UVar::init (const std::string & varname, impl::UContextImpl * ctx = 0)
Definition at line 63 of file uvar-common.cc.
References __init(), urbi::UContext::ctx_, urbi::getCurrentContext(), impl_, and urbi::name().
Referenced by init(), and urbi::UObject::UObject().
void urbi::UVar::init (const std::string & object, const std::string & slot, impl::UContextImpl * ctx = 0) [inline]
Definition at line 40 of file uvar.hxx.
References init().
bool urbi::UVar::invariant () const [private]
Definition at line 74 of file uvar-common.cc.
References urbi::echo(), urbi::name(), and vardata.
void urbi::UVar::keepSynchronized () [inline]
Keep this UVar synchronized with kernel value.
Definition at line 80 of file uvar.hxx.
References check_(), impl_, and urbi::impl::UVarImpl::keepSynchronized().
Referenced by urbi::UObject::USync().
urbi::UVar::operator bool () const [inline]
Definition at line 22 of file uvar.hxx.
urbi::UVar::operator const UBinary & () const
urbi::UVar::operator int () const
urbi::UVar::operator std::string () const
urbi::UVar::operator UBinary * () const [inline]
Deep copy, binary will have to be deleted by the user.
Definition at line 141 of file uvar.hxx.
urbi::UVar::operator UDictionary () const
urbi::UVar::operator ufloat () const
urbi::UVar::operator UImage () const
In plugin mode, gives direct access to the buffer, which may not be valid after the calling function returns.
Changes to the other fields of the structure have no effect.
urbi::UVar::operator UList () const
urbi::UVar::operator USound () const
In plugin mode, gives direct access to the buffer, which may not be valid after the calling function returns.
Changes to the other fields of the structure have no effect.
UVar & urbi::UVar::operator= (const UValue & v) [inline]
Definition at line 88 of file uvar.hxx.
References check_(), impl_, and urbi::impl::UVarImpl::set().
UVar& urbi::UVar::operator= (const UVar &) [private]
template<typename T > UVar & urbi::UVar::operator= (const T & v)
Definition at line 115 of file uvar.hxx.
References check_(), impl_, and urbi::impl::UVarImpl::set().
UVar& urbi::UVar::operator= (ufloat)
UVar& urbi::UVar::operator= (const std::string &)
UVar& urbi::UVar::operator= (const UBinary &)
Deep copy.
UVar& urbi::UVar::operator= (const UImage & i)
Deep copy.
UVar& urbi::UVar::operator= (const USound & s)
Deep copy.
UVar& urbi::UVar::operator= (const UList & l)
UVar& urbi::UVar::operator= (const UDictionary & d)
template<typename T > bool urbi::UVar::operator== (const T & v) const
Definition at line 222 of file uvar.hxx.
References urbi::uvalue_cast(), and val().
ufloat& urbi::UVar::out ()
urbi::UVar::PRIVATE (bool , temp) [private]
Full name of the variable as seen in URBI.
True if the variable is a temporary and must not be stored in callbacks
urbi::UVar::PRIVATE (RtpMode , rtp) [private]
void urbi::UVar::reset (ufloat n)
Definition at line 116 of file uvar-common.cc.
bool urbi::UVar::setBypass (bool enable = true) [inline]
Enable bypass-mode for this UVar.
Plugin-mode only. In bypass mode, if the UVar contains binary data, the data is never copied. The consequence is that the data is only accessible from notifyChange callbacks (urbiScript or C++): it is invalidated as soon as all callbacks have returned.
Definition at line 167 of file uvar.hxx.
References check_(), impl_, and urbi::impl::UVarImpl::setBypass().
void urbi::UVar::setOwned () [inline]
Definition at line 49 of file uvar.hxx.
References check_(), impl_, and urbi::impl::UVarImpl::setOwned().
void urbi::UVar::setProp (UProperty prop, const UValue & v) [inline]
Definition at line 146 of file uvar.hxx.
References check_(), impl_, and urbi::impl::UVarImpl::setProp().
Referenced by urbi::UProp::operator=().
void urbi::UVar::setProp (UProperty prop, const char * v) [inline]
Definition at line 152 of file uvar.hxx.
References check_(), impl_, and urbi::impl::UVarImpl::setProp().
void urbi::UVar::setProp (UProperty prop, const std::string & v) [inline]
Definition at line 139 of file uvar.hh.
void urbi::UVar::setProp (UProperty prop, ufloat v) [inline]
Definition at line 159 of file uvar.hxx.
References check_(), impl_, and urbi::impl::UVarImpl::setProp().
void urbi::UVar::syncValue () [inline]
Request the current value, wait until it is available.
Definition at line 65 of file uvar.hxx.
References check_(), impl_, and urbi::impl::UVarImpl::sync().
libport::utime_t urbi::UVar::timestamp () const
Definition at line 148 of file uvar-common.cc.
References check_(), impl_, and urbi::impl::UVarImpl::timestamp().
UDataType urbi::UVar::type () const [inline]
The type of the current content.
Definition at line 57 of file uvar.hxx.
References check_(), impl_, and urbi::impl::UVarImpl::type().
void urbi::UVar::unnotify () [inline]
Deactivate all callbacks associated with this UVar and stop synchro.
Definition at line 181 of file uvar.hxx.
References check_(), impl_, and urbi::impl::UVarImpl::unnotify().
Referenced by ~UVar().
void urbi::UVar::useRTP (bool enable = true) [inline]
Use RTP mode to transmit this variable if possible.
Definition at line 195 of file uvar.hxx.
References impl_, RTP_YES, and urbi::impl::UVarImpl::useRTP().
const UValue & urbi::UVar::val () const [inline]
Definition at line 72 of file uvar.hxx.
References check_(), urbi::impl::UVarImpl::get(), and impl_.
Referenced by as(), fill(), urbi::UList::operator=(), operator==(), and urbi::uvar_uvalue_cast().
Friends And Related Function Documentation
friend class impl::UVarImpl [friend]
Definition at line 200 of file uvar.hh.
Member Data Documentation
UProp urbi::UVar::blend
Definition at line 132 of file uvar.hh.
UProp urbi::UVar::constant
Definition at line 133 of file uvar.hh.
UProp urbi::UVar::delta
Definition at line 131 of file uvar.hh.
impl::UVarImpl* urbi::UVar::impl_
Definition at line 153 of file uvar.hh.
Referenced by __init(), urbi::impl::RemoteUContextImpl::assignMessage(), check_(), getProp(), init(), keepSynchronized(), operator=(), urbi::impl::RemoteUGenericCallbackImpl::registerCallback(), setBypass(), setOwned(), setProp(), syncValue(), timestamp(), type(), unnotify(), useRTP(), val(), and ~UVar().
bool urbi::UVar::owned
Is the variable owned by the module?
Definition at line 124 of file uvar.hh.
Referenced by __init(), urbi::impl::RemoteUVarImpl::setOwned(), and urbi::UGenericCallback::UGenericCallback().
UProp urbi::UVar::rangemax
Definition at line 128 of file uvar.hh.
UProp urbi::UVar::rangemin
Property accessors.
Definition at line 127 of file uvar.hh.
UProp urbi::UVar::speedmax
Definition at line 130 of file uvar.hh.
UProp urbi::UVar::speedmin
Definition at line 129 of file uvar.hh.
UVardata* urbi::UVar::vardata [private]
Pointer to internal data specifics.
Definition at line 167 of file uvar.hh.
Referenced by __init(), and invariant().
The documentation for this class was generated from the following files:
uvar.hh
uvar-common.cc
uvar.hxx