Urbi SDK Remote: urbi::UEvent Class Reference
urbi::UEvent Class Reference
UEvent class definition.
#include <uevent.hh>
Public Member Functions
UEvent ()
Creates an unbound UEvent. Call init() to bind it.
UEvent (const std::string &, impl::UContextImpl *=0)
UEvent (const std::string &, const std::string &, impl::UContextImpl *=0)
UEvent (UObject &, const std::string &, impl::UContextImpl *=0)
UEvent (const UEvent &)
void init (const std::string &object, const std::string &slot, impl::UContextImpl *=0)
void emit (urbi::UAutoValue v1=UAutoValue(), urbi::UAutoValue v2=UAutoValue(), urbi::UAutoValue v3=UAutoValue(), urbi::UAutoValue v4=UAutoValue(), urbi::UAutoValue v5=UAutoValue(), urbi::UAutoValue v6=UAutoValue(), urbi::UAutoValue v7=UAutoValue(), urbi::UAutoValue v8=UAutoValue())
Private Member Functions
void __init ()
Detailed Description
UEvent class definition.
Each UEvent instance corresponds to one URBI event. The class provides access to the event properties, and emitting/receiving events with payload.
Definition at line 27 of file uevent.hh.
Constructor & Destructor Documentation
urbi::UEvent::UEvent () [inline]
Creates an unbound UEvent. Call init() to bind it.
Definition at line 22 of file uevent.hxx.
urbi::UEvent::UEvent (const std::string & varname, impl::UContextImpl * impl = 0)
Definition at line 22 of file uevent.cc.
References __init().
urbi::UEvent::UEvent (const std::string & objname, const std::string & varname, impl::UContextImpl * impl = 0)
Definition at line 36 of file uevent.cc.
References __init().
urbi::UEvent::UEvent (UObject & obj, const std::string & varname, impl::UContextImpl * impl = 0)
Definition at line 29 of file uevent.cc.
References __init().
urbi::UEvent::UEvent (const UEvent & b)
Definition at line 44 of file uevent.cc.
References __init().
Member Function Documentation
void urbi::UEvent::__init () [inline, private]
Definition at line 30 of file uevent.hxx.
References urbi::UContext::ctx_, and urbi::impl::UContextImpl::declare_event().
Referenced by UEvent().
void urbi::UEvent::emit (urbi::UAutoValue v1 = UAutoValue(), urbi::UAutoValue v2 = UAutoValue(), urbi::UAutoValue v3 = UAutoValue(), urbi::UAutoValue v4 = UAutoValue(), urbi::UAutoValue v5 = UAutoValue(), urbi::UAutoValue v6 = UAutoValue(), urbi::UAutoValue v7 = UAutoValue(), urbi::UAutoValue v8 = UAutoValue()) [inline]
Definition at line 38 of file uevent.hxx.
References urbi::UContext::ctx_, urbi::impl::UContextImpl::emit(), and urbi::name().
void urbi::UEvent::init (const std::string & object, const std::string & slot, impl::UContextImpl * ctx = 0)
Definition at line 52 of file uevent.cc.
References urbi::UContext::ctx_, urbi::impl::UContextImpl::declare_event(), urbi::getCurrentContext(), and urbi::name().
The documentation for this class was generated from the following files:
uevent.hh
uevent.cc
uevent.hxx