Urbi SDK Remote: urbi::impl::UContextImpl Class Reference
urbi::impl::UContextImpl Class Reference
#include <ucontext-impl.hh>
Classes
class CleanupStack
Cleanup Stack RAII.
Public Types
typedef boost::unordered_map
< std::string, UObject * > objects_type
typedef boost::unordered_map
< std::string, UObjectHub * > hubs_type
Public Member Functions
virtual ~UContextImpl ()=0
void init ()
Inject all loaded uobjects in the system by calling newUObjectClass.
bool bind (const std::string &name, std::string rename=std::string())
Inject a specific uobject.
virtual void newUObjectClass (baseURBIStarter *s)=0
Called to instanciate the first Object of class.
virtual void newUObjectHubClass (baseURBIStarterHub *s)=0
virtual UObjectHub * getUObjectHub (const std::string &n)
Retrieve a UObjectHub based on its name or return 0 if not found.
virtual UObject * getUObject (const std::string &n)
Retrieve a UObject based on its name or return 0 if not found.
virtual void uobject_unarmorAndSend (const char *str)=0
Send Urbi code (ghost connection in plugin mode, default connection in remote mode).
virtual void send (const char *str)=0
Send the string to the connection hosting the UObject.
virtual void send (const void *buf, size_t size)=0
Send buf to the connection hosting the UObject.
virtual void call (const std::string &object, const std::string &method, UAutoValue v1=UAutoValue(), UAutoValue v2=UAutoValue(), UAutoValue v3=UAutoValue(), UAutoValue v4=UAutoValue(), UAutoValue v5=UAutoValue(), UAutoValue v6=UAutoValue(), UAutoValue v7=UAutoValue(), UAutoValue v8=UAutoValue())=0
virtual void declare_event (const UEvent *owner)=0
virtual void emit (const std::string &object, UAutoValue &v1, UAutoValue &v2, UAutoValue &v3, UAutoValue &v4, UAutoValue &v5, UAutoValue &v6, UAutoValue &v7, UAutoValue &v8)=0
virtual UObjectMode getRunningMode () const =0
Return the mode in which the code is running.
virtual std::pair< int, int > kernelVersion () const =0
Get the kernel major,minor version.
virtual void yield () const =0
Yield execution until next cycle.
virtual void yield_until (libport::utime_t deadline) const =0
Yield execution until deadline is met (see libport::utime()).
virtual void yield_for (libport::utime_t delay) const
Yield execution for delay.
virtual void yield_until_things_changed () const =0
Yield execution until something else is scheduled, or until a message is received in remote mode.
virtual void side_effect_free_set (bool s)=0
If s is true, mark the current task as having no side effect.
virtual bool side_effect_free_get () const =0
Get the current side_effect_free state.
virtual UVarImpl * getVarImpl ()=0
virtual UObjectImpl * getObjectImpl ()=0
virtual UGenericCallbackImpl * getGenericCallbackImpl ()=0
virtual void registerObject (UObject *o)
Default implementations appends to 'objects'.
virtual TimerHandle setTimer (UTimerCallback *cb)=0
virtual void registerHub (UObjectHub *)
virtual void removeHub (UObjectHub *)=0
virtual void setHubUpdate (UObjectHub *, ufloat)=0
virtual void instanciated (UObject *)=0
Called by the urbiStarter after each UObject instanciation.
template<typename T >
void addCleanup (T *ptr)
Add ptr to the list of objects to delete whean cleanup() is called.
void pushCleanupStack ()
Push a new cleanup stack.
void popCleanupStack ()
Delete all pointers passed to addCleanup in current stack and pop.
virtual void lock ()=0
Request a context lock from another thread to perform multiple operations.
virtual void unlock ()=0
Release lock acquired with lock().
virtual boost::asio::io_service & getIoService ()=0
Get the io_service used by this context.
Public Attributes
objects_type objects
hubs_type hubs
std::set< void * > initialized
Private Types
typedef std::vector
< std::vector
< boost::function0< void > > > CleanupList
Private Attributes
boost::thread_specific_ptr
< CleanupList > cleanup_list_
Detailed Description
Definition at line 34 of file ucontext-impl.hh.
Member Typedef Documentation
typedef std::vector<std::vector<boost::function0<void> > > urbi::impl::UContextImpl::CleanupList [private]
Definition at line 157 of file ucontext-impl.hh.
typedef boost::unordered_map<std::string, UObjectHub*> urbi::impl::UContextImpl::hubs_type
Definition at line 122 of file ucontext-impl.hh.
typedef boost::unordered_map<std::string, UObject*> urbi::impl::UContextImpl::objects_type
Definition at line 120 of file ucontext-impl.hh.
Constructor & Destructor Documentation
urbi::impl::UContextImpl::~UContextImpl () [inline, pure virtual]
Definition at line 26 of file ucontext-impl.hxx.
Member Function Documentation
template<typename T > void urbi::impl::UContextImpl::addCleanup (T * ptr)
Add ptr to the list of objects to delete whean cleanup() is called.
Definition at line 66 of file ucontext-impl.hxx.
References cleanup_list_.
Referenced by urbi::uvalue_caster< UVar >::operator()(), and urbi::impl::RemoteUVarImpl::unnotify().
bool urbi::impl::UContextImpl::bind (const std::string & name, std::string rename = std::string())
Inject a specific uobject.
Definition at line 310 of file uobject-common.cc.
References urbi::baseURBIStarter::instanciate(), urbi::baseURBIStarter::list(), and urbi::baseURBIStarter::name.
virtual void urbi::impl::UContextImpl::call (const std::string & object, const std::string & method, UAutoValue v1 = UAutoValue(), UAutoValue v2 = UAutoValue(), UAutoValue v3 = UAutoValue(), UAutoValue v4 = UAutoValue(), UAutoValue v5 = UAutoValue(), UAutoValue v6 = UAutoValue(), UAutoValue v7 = UAutoValue(), UAutoValue v8 = UAutoValue()) [pure virtual]
Implemented in urbi::impl::RemoteUContextImpl.
Referenced by urbi::UContext::call().
virtual void urbi::impl::UContextImpl::declare_event (const UEvent * owner) [pure virtual]
Implemented in urbi::impl::RemoteUContextImpl.
Referenced by urbi::UEvent::__init(), and urbi::UEvent::init().
virtual void urbi::impl::UContextImpl::emit (const std::string & object, UAutoValue & v1, UAutoValue & v2, UAutoValue & v3, UAutoValue & v4, UAutoValue & v5, UAutoValue & v6, UAutoValue & v7, UAutoValue & v8) [pure virtual]
Implemented in urbi::impl::RemoteUContextImpl.
Referenced by urbi::UEvent::emit().
virtual UGenericCallbackImpl* urbi::impl::UContextImpl::getGenericCallbackImpl () [pure virtual]
Implemented in urbi::impl::RemoteUContextImpl.
Referenced by urbi::UGenericCallback::UGenericCallback().
virtual boost::asio::io_service& urbi::impl::UContextImpl::getIoService () [pure virtual]
Get the io_service used by this context.
Implemented in urbi::impl::RemoteUContextImpl.
virtual UObjectImpl* urbi::impl::UContextImpl::getObjectImpl () [pure virtual]
Implemented in urbi::impl::RemoteUContextImpl.
virtual UObjectMode urbi::impl::UContextImpl::getRunningMode () const [pure virtual]
Return the mode in which the code is running.
Implemented in urbi::impl::RemoteUContextImpl.
Referenced by urbi::UContext::getRunningMode().
UObject * urbi::impl::UContextImpl::getUObject (const std::string & n) [virtual]
Retrieve a UObject based on its name or return 0 if not found.
Definition at line 342 of file uobject-common.cc.
References objects.
Referenced by urbi::UContext::getUObject(), and urbi::impl::RemoteUContextImpl::makeRTPLink().
UObjectHub * urbi::impl::UContextImpl::getUObjectHub (const std::string & n) [virtual]
Retrieve a UObjectHub based on its name or return 0 if not found.
Definition at line 336 of file uobject-common.cc.
References hubs.
Referenced by urbi::UContext::getUObjectHub().
virtual UVarImpl* urbi::impl::UContextImpl::getVarImpl () [pure virtual]
Implemented in urbi::impl::RemoteUContextImpl.
Referenced by urbi::UVar::__init().
void urbi::impl::UContextImpl::init ()
Inject all loaded uobjects in the system by calling newUObjectClass.
Definition at line 282 of file uobject-common.cc.
References GENERIC_TRY, initialized, urbi::baseURBIStarter::list(), urbi::baseURBIStarterHub::list(), urbi::baseURBIStarter::name, urbi::baseURBIStarterHub::name, newUObjectClass(), newUObjectHubClass(), and urbi::setCurrentContext().
Referenced by urbi::impl::RemoteUContextImpl::dispatcher().
virtual void urbi::impl::UContextImpl::instanciated (UObject *) [pure virtual]
Called by the urbiStarter after each UObject instanciation.
Implemented in urbi::impl::RemoteUContextImpl.
Referenced by urbi::URBIStarter< T >::instanciate().
virtual std::pair<int, int> urbi::impl::UContextImpl::kernelVersion () const [pure virtual]
Get the kernel major,minor version.
Implemented in urbi::impl::RemoteUContextImpl.
Referenced by urbi::UContext::kernelVersion().
virtual void urbi::impl::UContextImpl::lock () [pure virtual]
Request a context lock from another thread to perform multiple operations.
Implemented in urbi::impl::RemoteUContextImpl.
virtual void urbi::impl::UContextImpl::newUObjectClass (baseURBIStarter * s) [pure virtual]
Called to instanciate the first Object of class.
Implemented in urbi::impl::RemoteUContextImpl.
Referenced by init().
virtual void urbi::impl::UContextImpl::newUObjectHubClass (baseURBIStarterHub * s) [pure virtual]
Implemented in urbi::impl::RemoteUContextImpl.
Referenced by init().
void urbi::impl::UContextImpl::popCleanupStack () [inline]
Delete all pointers passed to addCleanup in current stack and pop.
Definition at line 84 of file ucontext-impl.hxx.
References cleanup_list_.
Referenced by urbi::impl::UContextImpl::CleanupStack::~CleanupStack().
void urbi::impl::UContextImpl::pushCleanupStack () [inline]
Push a new cleanup stack.
Definition at line 72 of file ucontext-impl.hxx.
References cleanup_list_.
Referenced by urbi::impl::UContextImpl::CleanupStack::CleanupStack().
void urbi::impl::UContextImpl::registerHub (UObjectHub * u) [virtual]
Reimplemented in urbi::impl::RemoteUContextImpl.
Definition at line 330 of file uobject-common.cc.
References urbi::UObjectHub::get_name(), and hubs.
Referenced by urbi::UObjectHub::UObjectHub().
void urbi::impl::UContextImpl::registerObject (UObject * o) [virtual]
Default implementations appends to 'objects'.
Definition at line 324 of file uobject-common.cc.
References urbi::UObject::__name, and objects.
Referenced by urbi::impl::RemoteUObjectImpl::initialize().
virtual void urbi::impl::UContextImpl::removeHub (UObjectHub *) [pure virtual]
Implemented in urbi::impl::RemoteUContextImpl.
Referenced by urbi::UObjectHub::~UObjectHub().
virtual void urbi::impl::UContextImpl::send (const void * buf, size_t size) [pure virtual]
Send buf to the connection hosting the UObject.
Implemented in urbi::impl::RemoteUContextImpl.
virtual void urbi::impl::UContextImpl::send (const char * str) [pure virtual]
Send the string to the connection hosting the UObject.
Implemented in urbi::impl::RemoteUContextImpl.
Referenced by urbi::UContext::send().
virtual void urbi::impl::UContextImpl::setHubUpdate (UObjectHub * , ufloat) [pure virtual]
Implemented in urbi::impl::RemoteUContextImpl.
Referenced by urbi::UObjectHub::USetUpdate().
virtual TimerHandle urbi::impl::UContextImpl::setTimer (UTimerCallback * cb) [pure virtual]
Implemented in urbi::impl::RemoteUContextImpl.
Referenced by urbi::UTimerCallback::registerCallback().
virtual bool urbi::impl::UContextImpl::side_effect_free_get () const [pure virtual]
Get the current side_effect_free state.
Implemented in urbi::impl::RemoteUContextImpl.
Referenced by urbi::UContext::side_effect_free_get().
virtual void urbi::impl::UContextImpl::side_effect_free_set (bool s) [pure virtual]
If s is true, mark the current task as having no side effect.
This call has no effect in remote mode.
Implemented in urbi::impl::RemoteUContextImpl.
Referenced by urbi::UContext::side_effect_free_set().
virtual void urbi::impl::UContextImpl::unlock () [pure virtual]
Release lock acquired with lock().
Implemented in urbi::impl::RemoteUContextImpl.
virtual void urbi::impl::UContextImpl::uobject_unarmorAndSend (const char * str) [pure virtual]
Send Urbi code (ghost connection in plugin mode, default connection in remote mode).
Implemented in urbi::impl::RemoteUContextImpl.
Referenced by urbi::UContext::uobject_unarmorAndSend().
virtual void urbi::impl::UContextImpl::yield () const [pure virtual]
Yield execution until next cycle.
Process pending messages in remote mode.
Implemented in urbi::impl::RemoteUContextImpl.
Referenced by urbi::UContext::yield().
void urbi::impl::UContextImpl::yield_for (libport::utime_t delay) const [inline, virtual]
Yield execution for delay.
Bounces to yield_until.
Definition at line 53 of file ucontext-impl.hxx.
References yield_until().
Referenced by urbi::UContext::yield_for(), and urbi::UObjectSocket::~UObjectSocket().
virtual void urbi::impl::UContextImpl::yield_until (libport::utime_t deadline) const [pure virtual]
Yield execution until deadline is met (see libport::utime()).
Implemented in urbi::impl::RemoteUContextImpl.
Referenced by yield_for(), and urbi::UContext::yield_until().
virtual void urbi::impl::UContextImpl::yield_until_things_changed () const [pure virtual]
Yield execution until something else is scheduled, or until a message is received in remote mode.
Implemented in urbi::impl::RemoteUContextImpl.
Referenced by urbi::UContext::yield_until_things_changed().
Member Data Documentation
boost::thread_specific_ptr<CleanupList> urbi::impl::UContextImpl::cleanup_list_ [private]
Definition at line 158 of file ucontext-impl.hh.
Referenced by addCleanup(), popCleanupStack(), and pushCleanupStack().
hubs_type urbi::impl::UContextImpl::hubs
Definition at line 123 of file ucontext-impl.hh.
Referenced by urbi::impl::RemoteUContextImpl::clientError(), getUObjectHub(), and registerHub().
std::set<void*> urbi::impl::UContextImpl::initialized
Definition at line 124 of file ucontext-impl.hh.
Referenced by init().
objects_type urbi::impl::UContextImpl::objects
Definition at line 121 of file ucontext-impl.hh.
Referenced by urbi::impl::RemoteUContextImpl::clientError(), urbi::impl::RemoteUContextImpl::dispatcher(), getUObject(), urbi::impl::RemoteUContextImpl::makeRTPLink(), and registerObject().
The documentation for this class was generated from the following files:
ucontext-impl.hh
uobject-common.cc
ucontext-impl.hxx