Urbi SDK Remote: urbi::UCallback1< OBJ, R, P1 > Class Template Reference
urbi::UCallback1< OBJ, R, P1 > Class Template Reference
#include <ucallbacks.hh>
Public Member Functions
MKUCallBackNotifyCtr1 (, false)
MKUCallBackNotifyCtr1 (const, true)
virtual UValue __evalcall (UList &param)
Private Attributes
OBJ * obj
R(OBJ::* fun)(P1)
R(OBJ::* funconst)(P1) const
bool is_const_
Detailed Description
template<class OBJ, class R, class P1>
class urbi::UCallback1< OBJ, R, P1 >
Definition at line 353 of file ucallbacks.hh.
Member Function Documentation
template<class OBJ , class R , class P1 > virtual UValue urbi::UCallback1< OBJ, R, P1 >::__evalcall (UList & param) [inline, virtual]
Implements urbi::UGenericCallback.
Definition at line 379 of file ucallbacks.hh.
References urbi::UContext::ctx_, urbi::UCallback1< OBJ, R, P1 >::fun, urbi::UCallback1< OBJ, R, P1 >::funconst, urbi::UCallback1< OBJ, R, P1 >::is_const_, and urbi::uvar_uvalue_cast().
template<class OBJ , class R , class P1 > urbi::UCallback1< OBJ, R, P1 >::MKUCallBackNotifyCtr1 (false)
template<class OBJ , class R , class P1 > urbi::UCallback1< OBJ, R, P1 >::MKUCallBackNotifyCtr1 (const , true)
Member Data Documentation
template<class OBJ , class R , class P1 > R(OBJ::* urbi::UCallback1< OBJ, R, P1 >::fun)(P1) [private]
Definition at line 394 of file ucallbacks.hh.
Referenced by urbi::UCallback1< OBJ, R, P1 >::__evalcall().
template<class OBJ , class R , class P1 > R(OBJ::* urbi::UCallback1< OBJ, R, P1 >::funconst)(P1) const [private]
Definition at line 395 of file ucallbacks.hh.
Referenced by urbi::UCallback1< OBJ, R, P1 >::__evalcall().
template<class OBJ , class R , class P1 > bool urbi::UCallback1< OBJ, R, P1 >::is_const_ [private]
Definition at line 396 of file ucallbacks.hh.
Referenced by urbi::UCallback1< OBJ, R, P1 >::__evalcall().
template<class OBJ , class R , class P1 > OBJ* urbi::UCallback1< OBJ, R, P1 >::obj [private]
Definition at line 393 of file ucallbacks.hh.
The documentation for this class was generated from the following file:
ucallbacks.hh