Urbi SDK Remote: urbi::UObjectStruct Class Reference
urbi::UObjectStruct Class Reference
#include <uvalue.hh>
Public Member Functions
UObjectStruct ()
UObjectStruct (const UObjectStruct &b)
UObjectStruct & operator= (const UObjectStruct &b)
~UObjectStruct ()
UValue & operator[] (const std::string &s)
Return UValue::error() on errors.
const UNamedValue & operator[] (size_t i) const
Return UNamedValue::error() on errors.
UNamedValue & operator[] (size_t i)
size_t size () const
std::ostream & print (std::ostream &o) const
Public Attributes
std::string refName
std::vector< UNamedValue > array
Detailed Description
Definition at line 128 of file uvalue.hh.
Constructor & Destructor Documentation
urbi::UObjectStruct::UObjectStruct ()
Definition at line 712 of file uvalue-common.cc.
urbi::UObjectStruct::UObjectStruct (const UObjectStruct & b)
Definition at line 715 of file uvalue-common.cc.
urbi::UObjectStruct::~UObjectStruct ()
Definition at line 720 of file uvalue-common.cc.
References array, and size().
Referenced by operator=().
Member Function Documentation
UObjectStruct & urbi::UObjectStruct::operator= (const UObjectStruct & b)
Definition at line 729 of file uvalue-common.cc.
References array, and ~UObjectStruct().
UValue & urbi::UObjectStruct::operator[] (const std::string & s)
Return UValue::error() on errors.
Definition at line 746 of file uvalue-common.cc.
References array, urbi::UValue::error(), urbi::name(), and size().
UNamedValue& urbi::UObjectStruct::operator[] (size_t i)
const UNamedValue& urbi::UObjectStruct::operator[] (size_t i) const
Return UNamedValue::error() on errors.
std::ostream & urbi::UObjectStruct::print (std::ostream & o) const
Definition at line 756 of file uvalue-common.cc.
References refName, and size().
size_t urbi::UObjectStruct::size () const [inline]
Definition at line 119 of file uvalue.hxx.
References array.
Referenced by operator[](), print(), urbi::UAbstractClient::send(), and ~UObjectStruct().
Member Data Documentation
std::vector<UNamedValue> urbi::UObjectStruct::array
Definition at line 148 of file uvalue.hh.
Referenced by operator=(), operator[](), size(), and ~UObjectStruct().
std::string urbi::UObjectStruct::refName
Definition at line 147 of file uvalue.hh.
Referenced by print(), and urbi::UAbstractClient::send().
The documentation for this class was generated from the following files:
uvalue.hh
uvalue-common.cc
uvalue.hxx