Urbi SDK Remote: urbi::UCallback2< OBJ, R, P1, P2 > Class Template Reference
urbi::UCallback2< OBJ, R, P1, P2 > Class Template Reference
#include <ucallbacks.hh>
Public Member Functions
MKUCallBackNotifyCtr2 (, false)
MKUCallBackNotifyCtr2 (const, true)
virtual UValue __evalcall (UList &param)
Private Attributes
OBJ * obj
R(OBJ::* fun)(P1, P2)
R(OBJ::* funconst)(P1, P2) const
bool is_const_
Detailed Description
template<class OBJ, class R, class P1, class P2>
class urbi::UCallback2< OBJ, R, P1, P2 >
Definition at line 537 of file ucallbacks.hh.
Member Function Documentation
template<class OBJ , class R , class P1 , class P2 > virtual UValue urbi::UCallback2< OBJ, R, P1, P2 >::__evalcall (UList & param) [inline, virtual]
Implements urbi::UGenericCallback.
Definition at line 563 of file ucallbacks.hh.
References urbi::UContext::ctx_, urbi::UCallback2< OBJ, R, P1, P2 >::fun, urbi::UCallback2< OBJ, R, P1, P2 >::funconst, urbi::UCallback2< OBJ, R, P1, P2 >::is_const_, and urbi::uvar_uvalue_cast().
template<class OBJ , class R , class P1 , class P2 > urbi::UCallback2< OBJ, R, P1, P2 >::MKUCallBackNotifyCtr2 (false)
template<class OBJ , class R , class P1 , class P2 > urbi::UCallback2< OBJ, R, P1, P2 >::MKUCallBackNotifyCtr2 (const , true)
Member Data Documentation
template<class OBJ , class R , class P1 , class P2 > R(OBJ::* urbi::UCallback2< OBJ, R, P1, P2 >::fun)(P1, P2) [private]
Definition at line 578 of file ucallbacks.hh.
Referenced by urbi::UCallback2< OBJ, R, P1, P2 >::__evalcall().
template<class OBJ , class R , class P1 , class P2 > R(OBJ::* urbi::UCallback2< OBJ, R, P1, P2 >::funconst)(P1, P2) const [private]
Definition at line 579 of file ucallbacks.hh.
Referenced by urbi::UCallback2< OBJ, R, P1, P2 >::__evalcall().
template<class OBJ , class R , class P1 , class P2 > bool urbi::UCallback2< OBJ, R, P1, P2 >::is_const_ [private]
Definition at line 580 of file ucallbacks.hh.
Referenced by urbi::UCallback2< OBJ, R, P1, P2 >::__evalcall().
template<class OBJ , class R , class P1 , class P2 > OBJ* urbi::UCallback2< OBJ, R, P1, P2 >::obj [private]
Definition at line 577 of file ucallbacks.hh.
The documentation for this class was generated from the following file:
ucallbacks.hh