Urbi SDK Remote: urbi::impl::RemoteUVarImpl Class Reference
urbi::impl::RemoteUVarImpl Class Reference
#include <remote-ucontext-impl.hh>
Public Member Functions
virtual void initialize (UVar *owner)
UVar initialization.
virtual void clean ()
UVar destructor.
virtual void setOwned ()
set own mode
virtual void sync ()
virtual void request ()
virtual void keepSynchronized ()
virtual void set (const UValue &v)
virtual const UValue & get () const
virtual ufloat & in ()
UVar in value (write mode).
virtual ufloat & out ()
UVar out value (read mode).
virtual UDataType type () const
Get Uvalue type.
virtual UValue getProp (UProperty prop)
virtual void setProp (UProperty prop, const UValue &v)
virtual bool setBypass (bool enable)
virtual time_t timestamp () const
virtual void unnotify ()
void update (const UValue &v)
void update (const UValue &v, time_t timestamp)
virtual void useRTP (bool enable)
Private Attributes
USyncClient * client_
UValue value_
UVar * owner_
time_t timestamp_
std::vector
< RemoteUGenericCallbackImpl * > callbacks_
Friends
class RemoteUGenericCallbackImpl
Detailed Description
Definition at line 159 of file remote-ucontext-impl.hh.
Member Function Documentation
void urbi::impl::RemoteUVarImpl::clean () [virtual]
UVar destructor.
Implements urbi::impl::UVarImpl.
Definition at line 112 of file uvar.cc.
References urbi::UContext::ctx_, and owner_.
const UValue & urbi::impl::RemoteUVarImpl::get () const [virtual]
Implements urbi::impl::UVarImpl.
Definition at line 281 of file uvar.cc.
References value_.
UValue urbi::impl::RemoteUVarImpl::getProp (UProperty prop) [virtual]
Implements urbi::impl::UVarImpl.
Definition at line 91 of file uvar.cc.
References client_, urbi::name(), owner_, urbi::USyncClient::syncGet(), and urbi::UMessage::value.
ufloat & urbi::impl::RemoteUVarImpl::in () [virtual]
UVar in value (write mode).
Definition at line 69 of file uvar.cc.
void urbi::impl::RemoteUVarImpl::initialize (UVar * owner) [virtual]
UVar initialization.
Implements urbi::impl::UVarImpl.
Definition at line 39 of file uvar.cc.
References urbi::impl::RemoteUContextImpl::client_, client_, urbi::UContext::ctx_, urbi::impl::RemoteUContextImpl::dataSent, urbi::name(), owner_, and URBI_SEND_PIPED_COMMAND_C.
void urbi::impl::RemoteUVarImpl::keepSynchronized () [virtual]
Implements urbi::impl::UVarImpl.
Definition at line 85 of file uvar.cc.
ufloat & urbi::impl::RemoteUVarImpl::out () [virtual]
UVar out value (read mode).
Definition at line 62 of file uvar.cc.
void urbi::impl::RemoteUVarImpl::request () [virtual]
Implements urbi::impl::UVarImpl.
Definition at line 301 of file uvar.cc.
References client_, urbi::UContext::ctx_, urbi::impl::RemoteUContextImpl::dataSent, urbi::externalModuleTag, urbi::name(), owner_, urbi::UEM_ASSIGNVALUE, and URBI_SEND_PIPED_COMMAND_C.
void urbi::impl::RemoteUVarImpl::set (const UValue & v) [virtual]
Implements urbi::impl::UVarImpl.
Definition at line 194 of file uvar.cc.
References urbi::impl::RemoteUContextImpl::assignMessage(), urbi::UValue::binary, client_, urbi::impl::RemoteUContextImpl::client_, urbi::UBinary::common, urbi::UContext::ctx_, urbi::DATA_BINARY, urbi::DATA_STRING, urbi::impl::RemoteUContextImpl::dataSent, urbi::impl::RemoteUContextImpl::dispatchDepth, urbi::impl::RemoteUContextImpl::enableRTP, urbi::UAbstractClient::endPack(), urbi::UBinary::getMessage(), urbi::getUObject(), urbi::USyncClient::isCallbackThread(), urbi::impl::RemoteUContextImpl::localCall(), urbi::impl::RemoteUContextImpl::makeRTPLink(), urbi::name(), owner_, urbi::impl::rtp_id(), urbi::impl::RemoteUContextImpl::rtpLinks, urbi::UAbstractClient::sendBinary(), urbi::UAbstractClient::startPack(), urbi::UValue::stringValue, urbi::UValue::type, and URBI_SEND_COMMAND_C.
bool urbi::impl::RemoteUVarImpl::setBypass (bool enable) [virtual]
Implements urbi::impl::UVarImpl.
Definition at line 55 of file uvar.cc.
void urbi::impl::RemoteUVarImpl::setOwned () [virtual]
set own mode
Implements urbi::impl::UVarImpl.
Definition at line 288 of file uvar.cc.
References urbi::UVar::owned, and owner_.
void urbi::impl::RemoteUVarImpl::setProp (UProperty prop, const UValue & v) [virtual]
Implements urbi::impl::UVarImpl.
Definition at line 76 of file uvar.cc.
References client_, urbi::UContext::ctx_, urbi::impl::RemoteUContextImpl::dataSent, urbi::name(), owner_, and URBI_SEND_PIPED_COMMAND_C.
void urbi::impl::RemoteUVarImpl::sync () [virtual]
Implements urbi::impl::UVarImpl.
Definition at line 313 of file uvar.cc.
References client_, urbi::UAbstractClient::fresh(), urbi::compatibility::isvoid(), urbi::UAbstractClient::kernelMajor(), urbi::MESSAGE_DATA, urbi::name(), owner_, urbi::USyncClient::syncGetTag(), urbi::UMessage::type, urbi::UMessage::value, and value_.
time_t urbi::impl::RemoteUVarImpl::timestamp () const [virtual]
Implements urbi::impl::UVarImpl.
Definition at line 344 of file uvar.cc.
References timestamp_.
UDataType urbi::impl::RemoteUVarImpl::type () const [virtual]
Get Uvalue type.
Implements urbi::impl::UVarImpl.
Definition at line 295 of file uvar.cc.
void urbi::impl::RemoteUVarImpl::unnotify () [virtual]
Implements urbi::impl::UVarImpl.
Definition at line 356 of file uvar.cc.
References urbi::impl::UContextImpl::addCleanup(), callbacks_, urbi::UContext::ctx_, urbi::impl::RemoteUContextImpl::dataSent, urbi::UGenericCallback::name, urbi::name(), urbi::impl::RemoteUGenericCallbackImpl::owner_, owner_, urbi::send(), and urbi::UGenericCallback::type.
void urbi::impl::RemoteUVarImpl::update (const UValue & v, time_t timestamp)
Definition at line 350 of file uvar.cc.
References timestamp_, and value_.
void urbi::impl::RemoteUVarImpl::update (const UValue & v)
void urbi::impl::RemoteUVarImpl::useRTP (bool enable) [virtual]
Implements urbi::impl::UVarImpl.
Definition at line 387 of file uvar.cc.
References urbi::UContext::ctx_, urbi::impl::RemoteUContextImpl::dataSent, urbi::name(), owner_, and urbi::send().
Friends And Related Function Documentation
friend class RemoteUGenericCallbackImpl [friend]
Definition at line 187 of file remote-ucontext-impl.hh.
Member Data Documentation
std::vector<RemoteUGenericCallbackImpl*> urbi::impl::RemoteUVarImpl::callbacks_ [private]
Definition at line 188 of file remote-ucontext-impl.hh.
Referenced by unnotify().
USyncClient* urbi::impl::RemoteUVarImpl::client_ [private]
Definition at line 183 of file remote-ucontext-impl.hh.
Referenced by getProp(), initialize(), request(), set(), setProp(), and sync().
UVar* urbi::impl::RemoteUVarImpl::owner_ [private]
Definition at line 185 of file remote-ucontext-impl.hh.
Referenced by clean(), getProp(), initialize(), request(), set(), setOwned(), setProp(), sync(), unnotify(), and useRTP().
time_t urbi::impl::RemoteUVarImpl::timestamp_ [private]
Definition at line 186 of file remote-ucontext-impl.hh.
Referenced by timestamp(), and update().
UValue urbi::impl::RemoteUVarImpl::value_ [private]
Definition at line 184 of file remote-ucontext-impl.hh.
Referenced by get(), sync(), and update().
The documentation for this class was generated from the following files:
remote-ucontext-impl.hh
uvar.cc