Urbi SDK Remote: urbi::impl::UObjectImpl Class Reference
urbi::impl::UObjectImpl Class Reference
#include <ucontext-impl.hh>
Public Member Functions
virtual ~UObjectImpl ()=0
virtual void initialize (UObject *owner)=0
virtual void clean ()=0
virtual void setUpdate (ufloat period)=0
virtual bool removeTimer (TimerHandle h)=0
Detailed Description
Definition at line 161 of file ucontext-impl.hh.
Constructor & Destructor Documentation
urbi::impl::UObjectImpl::~UObjectImpl () [inline, pure virtual]
Definition at line 34 of file ucontext-impl.hxx.
Member Function Documentation
virtual void urbi::impl::UObjectImpl::clean () [pure virtual]
Implemented in urbi::impl::RemoteUObjectImpl.
Referenced by urbi::UObject::clean().
virtual void urbi::impl::UObjectImpl::initialize (UObject * owner) [pure virtual]
Implemented in urbi::impl::RemoteUObjectImpl.
Referenced by urbi::UObject::UObject().
virtual bool urbi::impl::UObjectImpl::removeTimer (TimerHandle h) [pure virtual]
Implemented in urbi::impl::RemoteUObjectImpl.
virtual void urbi::impl::UObjectImpl::setUpdate (ufloat period) [pure virtual]
Implemented in urbi::impl::RemoteUObjectImpl.
Referenced by urbi::UObject::USetUpdate().
The documentation for this class was generated from the following files:
ucontext-impl.hh
ucontext-impl.hxx