Urbi SDK Remote: urbi::URBIStarter< T > Class Template Reference
urbi::URBIStarter< T > Class Template Reference
This is the class containing URBI starters.
#include <ustarter.hh>
Public Member Functions
URBIStarter (const std::string &name, bool local=false)
virtual ~URBIStarter ()
virtual UObject * instanciate (impl::UContextImpl *ctx, const std::string &n=std::string())
Create an instance of the UObject.
Detailed Description
template<class T>
class urbi::URBIStarter< T >
This is the class containing URBI starters.
A starter is a class whose job is to start an instance of a particular UObject subclass, resulting in the initialization of this object (registration to the kernel)
Definition at line 77 of file ustarter.hh.
Constructor & Destructor Documentation
template<class T > urbi::URBIStarter< T >::URBIStarter (const std::string & name, bool local = false) [inline]
Definition at line 43 of file ustarter.hxx.
References urbi::baseURBIStarter::list().
template<class T > urbi::URBIStarter< T >::~URBIStarter () [inline, virtual]
Definition at line 51 of file ustarter.hxx.
References urbi::baseURBIStarter::list().
Member Function Documentation
template<class T > UObject * urbi::URBIStarter< T >::instanciate (impl::UContextImpl * ctx, const std::string & n = std::string()) [inline, virtual]
Create an instance of the UObject.
Implements urbi::baseURBIStarter.
Definition at line 59 of file ustarter.hxx.
References urbi::UObject::cloner, urbi::impl::UContextImpl::instanciated(), urbi::baseURBIStarter::name, and urbi::setCurrentContext().
The documentation for this class was generated from the following files:
ustarter.hh
ustarter.hxx