Urbi SDK Remote: urbi::UProp Class Reference
urbi::UProp Class Reference
Provides easy access to variable properties.
#include <uprop.hh>
Public Member Functions
void operator= (const UValue &v)
void operator= (const ufloat v)
void operator= (const std::string &v)
operator ufloat ()
operator std::string ()
operator UValue ()
UProp (UVar &owner, UProperty name)
Private Member Functions
UProp (const UProp &)
UProp & operator= (const UProp &)
Private Attributes
UVar & owner
UProperty name
Detailed Description
Provides easy access to variable properties.
Definition at line 24 of file uprop.hh.
Constructor & Destructor Documentation
urbi::UProp::UProp (UVar & owner, UProperty name)
Definition at line 18 of file uprop.cc.
urbi::UProp::UProp (const UProp &) [private]
Member Function Documentation
urbi::UProp::operator std::string ()
Definition at line 46 of file uprop.cc.
References urbi::UVar::getProp(), name, and owner.
urbi::UProp::operator ufloat ()
Definition at line 41 of file uprop.cc.
References urbi::UVar::getProp(), name, and owner.
urbi::UProp::operator UValue ()
Definition at line 51 of file uprop.cc.
References urbi::UVar::getProp(), name, and owner.
void urbi::UProp::operator= (const UValue & v)
Definition at line 24 of file uprop.cc.
References name, owner, and urbi::UVar::setProp().
void urbi::UProp::operator= (const ufloat v)
Definition at line 30 of file uprop.cc.
References name, owner, and urbi::UVar::setProp().
void urbi::UProp::operator= (const std::string & v)
Definition at line 36 of file uprop.cc.
References name, owner, and urbi::UVar::setProp().
UProp& urbi::UProp::operator= (const UProp &) [private]
Member Data Documentation
UProperty urbi::UProp::name [private]
Definition at line 39 of file uprop.hh.
Referenced by operator std::string(), operator ufloat(), operator UValue(), and operator=().
UVar& urbi::UProp::owner [private]
Definition at line 38 of file uprop.hh.
Referenced by operator std::string(), operator ufloat(), operator UValue(), and operator=().
The documentation for this class was generated from the following files:
uprop.hh
uprop.cc