Urbi SDK Remote: urbi::impl::RemoteUObjectImpl Class Reference
urbi::impl::RemoteUObjectImpl Class Reference
#include <remote-ucontext-impl.hh>
Public Member Functions
virtual ~RemoteUObjectImpl ()
virtual void initialize (UObject *owner)
UObject constructor.
virtual void clean ()
UObject cleaner.
virtual void setUpdate (ufloat period)
virtual bool removeTimer (TimerHandle h)
void onUpdate ()
Private Attributes
UObject * owner_
ufloat period
libport::AsyncCallHandler updateHandler
Detailed Description
Definition at line 143 of file remote-ucontext-impl.hh.
Constructor & Destructor Documentation
urbi::impl::RemoteUObjectImpl::~RemoteUObjectImpl () [virtual]
Definition at line 228 of file uobject.cc.
Member Function Documentation
void urbi::impl::RemoteUObjectImpl::clean () [virtual]
UObject cleaner.
Implements urbi::impl::UObjectImpl.
Definition at line 258 of file uobject.cc.
References urbi::UObject::__name, urbi::UContext::ctx_, urbi::UObjectHub::members, urbi::UObject::objecthub, and owner_.
void urbi::impl::RemoteUObjectImpl::initialize (UObject * owner) [virtual]
UObject constructor.
Implements urbi::impl::UObjectImpl.
Definition at line 232 of file uobject.cc.
References urbi::UObject::__name, urbi::createUCallback(), urbi::UContext::ctx_, owner_, period, urbi::impl::UContextImpl::registerObject(), urbi::UObject::update(), and URBI_SEND_PIPED_COMMAND_C.
void urbi::impl::RemoteUObjectImpl::onUpdate ()
Definition at line 285 of file uobject.cc.
References urbi::UObject::__name, urbi::impl::RemoteUContextImpl::client_, urbi::UContext::ctx_, urbi::externalModuleTag, urbi::impl::RemoteUContextImpl::getClient(), urbi::UValue::list, urbi::USyncClient::notifyCallbacks(), owner_, period, urbi::UList::push_back(), urbi::UMessage::tag, urbi::UMessage::type, urbi::UEM_EVALFUNCTION, updateHandler, and urbi::UMessage::value.
Referenced by setUpdate().
bool urbi::impl::RemoteUObjectImpl::removeTimer (TimerHandle h) [virtual]
Implements urbi::impl::UObjectImpl.
Definition at line 599 of file uobject.cc.
References urbi::UContext::ctx_, urbi::impl::RemoteUContextImpl::mapLock, owner_, and urbi::impl::RemoteUContextImpl::timerMap.
void urbi::impl::RemoteUObjectImpl::setUpdate (ufloat period) [virtual]
Implements urbi::impl::UObjectImpl.
Definition at line 273 of file uobject.cc.
References onUpdate(), period, and updateHandler.
Member Data Documentation
UObject* urbi::impl::RemoteUObjectImpl::owner_ [private]
Definition at line 154 of file remote-ucontext-impl.hh.
Referenced by clean(), initialize(), onUpdate(), and removeTimer().
ufloat urbi::impl::RemoteUObjectImpl::period [private]
Definition at line 155 of file remote-ucontext-impl.hh.
Referenced by initialize(), onUpdate(), and setUpdate().
libport::AsyncCallHandler urbi::impl::RemoteUObjectImpl::updateHandler [private]
Definition at line 156 of file remote-ucontext-impl.hh.
Referenced by onUpdate(), and setUpdate().
The documentation for this class was generated from the following files:
remote-ucontext-impl.hh
uobject.cc