Urbi SDK Remote: urbi::UCallback7< OBJ, R, P1, P2, P3, P4, P5, P6, P7 > Class Template Reference
urbi::UCallback7< OBJ, R, P1, P2, P3, P4, P5, P6, P7 > Class Template Reference
#include <ucallbacks.hh>
Public Member Functions
MKUCallBackNotifyCtr7 (, false)
MKUCallBackNotifyCtr7 (const, true)
virtual UValue __evalcall (UList &param)
Private Attributes
OBJ * obj
R(OBJ::* fun)(P1, P2, P3, P4, P5, P6, P7)
R(OBJ::* funconst)(P1, P2, P3, P4, P5, P6, P7) const
bool is_const_
Detailed Description
template<class OBJ, class R, class P1, class P2, class P3, class P4, class P5, class P6, class P7>
class urbi::UCallback7< OBJ, R, P1, P2, P3, P4, P5, P6, P7 >
Definition at line 1457 of file ucallbacks.hh.
Member Function Documentation
template<class OBJ , class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 > virtual UValue urbi::UCallback7< OBJ, R, P1, P2, P3, P4, P5, P6, P7 >::__evalcall (UList & param) [inline, virtual]
Implements urbi::UGenericCallback.
Definition at line 1483 of file ucallbacks.hh.
References urbi::UContext::ctx_, urbi::UCallback7< OBJ, R, P1, P2, P3, P4, P5, P6, P7 >::fun, urbi::UCallback7< OBJ, R, P1, P2, P3, P4, P5, P6, P7 >::funconst, urbi::UCallback7< OBJ, R, P1, P2, P3, P4, P5, P6, P7 >::is_const_, and urbi::uvar_uvalue_cast().
template<class OBJ , class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 > urbi::UCallback7< OBJ, R, P1, P2, P3, P4, P5, P6, P7 >::MKUCallBackNotifyCtr7 (false)
template<class OBJ , class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 > urbi::UCallback7< OBJ, R, P1, P2, P3, P4, P5, P6, P7 >::MKUCallBackNotifyCtr7 (const , true)
Member Data Documentation
template<class OBJ , class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 > R(OBJ::* urbi::UCallback7< OBJ, R, P1, P2, P3, P4, P5, P6, P7 >::fun)(P1, P2, P3, P4, P5, P6, P7) [private]
Definition at line 1498 of file ucallbacks.hh.
Referenced by urbi::UCallback7< OBJ, R, P1, P2, P3, P4, P5, P6, P7 >::__evalcall().
template<class OBJ , class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 > R(OBJ::* urbi::UCallback7< OBJ, R, P1, P2, P3, P4, P5, P6, P7 >::funconst)(P1, P2, P3, P4, P5, P6, P7) const [private]
Definition at line 1499 of file ucallbacks.hh.
Referenced by urbi::UCallback7< OBJ, R, P1, P2, P3, P4, P5, P6, P7 >::__evalcall().
template<class OBJ , class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 > bool urbi::UCallback7< OBJ, R, P1, P2, P3, P4, P5, P6, P7 >::is_const_ [private]
Definition at line 1500 of file ucallbacks.hh.
Referenced by urbi::UCallback7< OBJ, R, P1, P2, P3, P4, P5, P6, P7 >::__evalcall().
template<class OBJ , class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 > OBJ* urbi::UCallback7< OBJ, R, P1, P2, P3, P4, P5, P6, P7 >::obj [private]
Definition at line 1497 of file ucallbacks.hh.
The documentation for this class was generated from the following file:
ucallbacks.hh