Urbi SDK Remote: urbi::UCallback5< OBJ, R, P1, P2, P3, P4, P5 > Class Template Reference
urbi::UCallback5< OBJ, R, P1, P2, P3, P4, P5 > Class Template Reference
#include <ucallbacks.hh>
Public Member Functions
MKUCallBackNotifyCtr5 (, false)
MKUCallBackNotifyCtr5 (const, true)
virtual UValue __evalcall (UList &param)
Private Attributes
OBJ * obj
R(OBJ::* fun)(P1, P2, P3, P4, P5)
R(OBJ::* funconst)(P1, P2, P3, P4, P5) const
bool is_const_
Detailed Description
template<class OBJ, class R, class P1, class P2, class P3, class P4, class P5>
class urbi::UCallback5< OBJ, R, P1, P2, P3, P4, P5 >
Definition at line 1089 of file ucallbacks.hh.
Member Function Documentation
template<class OBJ , class R , class P1 , class P2 , class P3 , class P4 , class P5 > virtual UValue urbi::UCallback5< OBJ, R, P1, P2, P3, P4, P5 >::__evalcall (UList & param) [inline, virtual]
Implements urbi::UGenericCallback.
Definition at line 1115 of file ucallbacks.hh.
References urbi::UContext::ctx_, urbi::UCallback5< OBJ, R, P1, P2, P3, P4, P5 >::fun, urbi::UCallback5< OBJ, R, P1, P2, P3, P4, P5 >::funconst, urbi::UCallback5< OBJ, R, P1, P2, P3, P4, P5 >::is_const_, and urbi::uvar_uvalue_cast().
template<class OBJ , class R , class P1 , class P2 , class P3 , class P4 , class P5 > urbi::UCallback5< OBJ, R, P1, P2, P3, P4, P5 >::MKUCallBackNotifyCtr5 (false)
template<class OBJ , class R , class P1 , class P2 , class P3 , class P4 , class P5 > urbi::UCallback5< OBJ, R, P1, P2, P3, P4, P5 >::MKUCallBackNotifyCtr5 (const , true)
Member Data Documentation
template<class OBJ , class R , class P1 , class P2 , class P3 , class P4 , class P5 > R(OBJ::* urbi::UCallback5< OBJ, R, P1, P2, P3, P4, P5 >::fun)(P1, P2, P3, P4, P5) [private]
Definition at line 1130 of file ucallbacks.hh.
Referenced by urbi::UCallback5< OBJ, R, P1, P2, P3, P4, P5 >::__evalcall().
template<class OBJ , class R , class P1 , class P2 , class P3 , class P4 , class P5 > R(OBJ::* urbi::UCallback5< OBJ, R, P1, P2, P3, P4, P5 >::funconst)(P1, P2, P3, P4, P5) const [private]
Definition at line 1131 of file ucallbacks.hh.
Referenced by urbi::UCallback5< OBJ, R, P1, P2, P3, P4, P5 >::__evalcall().
template<class OBJ , class R , class P1 , class P2 , class P3 , class P4 , class P5 > bool urbi::UCallback5< OBJ, R, P1, P2, P3, P4, P5 >::is_const_ [private]
Definition at line 1132 of file ucallbacks.hh.
Referenced by urbi::UCallback5< OBJ, R, P1, P2, P3, P4, P5 >::__evalcall().
template<class OBJ , class R , class P1 , class P2 , class P3 , class P4 , class P5 > OBJ* urbi::UCallback5< OBJ, R, P1, P2, P3, P4, P5 >::obj [private]
Definition at line 1129 of file ucallbacks.hh.
The documentation for this class was generated from the following file:
ucallbacks.hh