Urbi SDK Remote: urbi::UCallback8< OBJ, R, P1, P2, P3, P4, P5, P6, P7, P8 > Class Template Reference
urbi::UCallback8< OBJ, R, P1, P2, P3, P4, P5, P6, P7, P8 > Class Template Reference
#include <ucallbacks.hh>
Public Member Functions
MKUCallBackNotifyCtr8 (, false)
MKUCallBackNotifyCtr8 (const, true)
virtual UValue __evalcall (UList &param)
Private Attributes
OBJ * obj
R(OBJ::* fun)(P1, P2, P3, P4, P5, P6, P7, P8)
R(OBJ::* funconst)(P1, P2, P3, P4, P5, P6, P7, P8) const
bool is_const_
Detailed Description
template<class OBJ, class R, class P1, class P2, class P3, class P4, class P5, class P6, class P7, class P8>
class urbi::UCallback8< OBJ, R, P1, P2, P3, P4, P5, P6, P7, P8 >
Definition at line 1641 of file ucallbacks.hh.
Member Function Documentation
template<class OBJ , class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 > virtual UValue urbi::UCallback8< OBJ, R, P1, P2, P3, P4, P5, P6, P7, P8 >::__evalcall (UList & param) [inline, virtual]
Implements urbi::UGenericCallback.
Definition at line 1667 of file ucallbacks.hh.
References urbi::UContext::ctx_, urbi::UCallback8< OBJ, R, P1, P2, P3, P4, P5, P6, P7, P8 >::fun, urbi::UCallback8< OBJ, R, P1, P2, P3, P4, P5, P6, P7, P8 >::funconst, urbi::UCallback8< OBJ, R, P1, P2, P3, P4, P5, P6, P7, P8 >::is_const_, and urbi::uvar_uvalue_cast().
template<class OBJ , class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 > urbi::UCallback8< OBJ, R, P1, P2, P3, P4, P5, P6, P7, P8 >::MKUCallBackNotifyCtr8 (false)
template<class OBJ , class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 > urbi::UCallback8< OBJ, R, P1, P2, P3, P4, P5, P6, P7, P8 >::MKUCallBackNotifyCtr8 (const , true)
Member Data Documentation
template<class OBJ , class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 > R(OBJ::* urbi::UCallback8< OBJ, R, P1, P2, P3, P4, P5, P6, P7, P8 >::fun)(P1, P2, P3, P4, P5, P6, P7, P8) [private]
Definition at line 1682 of file ucallbacks.hh.
Referenced by urbi::UCallback8< OBJ, R, P1, P2, P3, P4, P5, P6, P7, P8 >::__evalcall().
template<class OBJ , class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 > R(OBJ::* urbi::UCallback8< OBJ, R, P1, P2, P3, P4, P5, P6, P7, P8 >::funconst)(P1, P2, P3, P4, P5, P6, P7, P8) const [private]
Definition at line 1683 of file ucallbacks.hh.
Referenced by urbi::UCallback8< OBJ, R, P1, P2, P3, P4, P5, P6, P7, P8 >::__evalcall().
template<class OBJ , class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 > bool urbi::UCallback8< OBJ, R, P1, P2, P3, P4, P5, P6, P7, P8 >::is_const_ [private]
Definition at line 1684 of file ucallbacks.hh.
Referenced by urbi::UCallback8< OBJ, R, P1, P2, P3, P4, P5, P6, P7, P8 >::__evalcall().
template<class OBJ , class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 > OBJ* urbi::UCallback8< OBJ, R, P1, P2, P3, P4, P5, P6, P7, P8 >::obj [private]
Definition at line 1681 of file ucallbacks.hh.
The documentation for this class was generated from the following file:
ucallbacks.hh