Urbi SDK Remote: urbi::UCallback9< OBJ, R, P1, P2, P3, P4, P5, P6, P7, P8, P9 > Class Template Reference
urbi::UCallback9< OBJ, R, P1, P2, P3, P4, P5, P6, P7, P8, P9 > Class Template Reference
#include <ucallbacks.hh>
Public Member Functions
MKUCallBackNotifyCtr9 (, false)
MKUCallBackNotifyCtr9 (const, true)
virtual UValue __evalcall (UList &param)
Private Attributes
OBJ * obj
R(OBJ::* fun)(P1, P2, P3, P4, P5, P6, P7, P8, P9)
R(OBJ::* funconst)(P1, P2, P3, P4, P5, P6, P7, P8, P9) const
bool is_const_
Detailed Description
template<class OBJ, class R, class P1, class P2, class P3, class P4, class P5, class P6, class P7, class P8, class P9>
class urbi::UCallback9< OBJ, R, P1, P2, P3, P4, P5, P6, P7, P8, P9 >
Definition at line 1825 of file ucallbacks.hh.
Member Function Documentation
template<class OBJ , class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 , class P9 > virtual UValue urbi::UCallback9< OBJ, R, P1, P2, P3, P4, P5, P6, P7, P8, P9 >::__evalcall (UList & param) [inline, virtual]
Implements urbi::UGenericCallback.
Definition at line 1851 of file ucallbacks.hh.
References urbi::UContext::ctx_, urbi::UCallback9< OBJ, R, P1, P2, P3, P4, P5, P6, P7, P8, P9 >::fun, urbi::UCallback9< OBJ, R, P1, P2, P3, P4, P5, P6, P7, P8, P9 >::funconst, urbi::UCallback9< OBJ, R, P1, P2, P3, P4, P5, P6, P7, P8, P9 >::is_const_, and urbi::uvar_uvalue_cast().
template<class OBJ , class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 , class P9 > urbi::UCallback9< OBJ, R, P1, P2, P3, P4, P5, P6, P7, P8, P9 >::MKUCallBackNotifyCtr9 (false)
template<class OBJ , class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 , class P9 > urbi::UCallback9< OBJ, R, P1, P2, P3, P4, P5, P6, P7, P8, P9 >::MKUCallBackNotifyCtr9 (const , true)
Member Data Documentation
template<class OBJ , class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 , class P9 > R(OBJ::* urbi::UCallback9< OBJ, R, P1, P2, P3, P4, P5, P6, P7, P8, P9 >::fun)(P1, P2, P3, P4, P5, P6, P7, P8, P9) [private]
Definition at line 1866 of file ucallbacks.hh.
Referenced by urbi::UCallback9< OBJ, R, P1, P2, P3, P4, P5, P6, P7, P8, P9 >::__evalcall().
template<class OBJ , class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 , class P9 > R(OBJ::* urbi::UCallback9< OBJ, R, P1, P2, P3, P4, P5, P6, P7, P8, P9 >::funconst)(P1, P2, P3, P4, P5, P6, P7, P8, P9) const [private]
Definition at line 1867 of file ucallbacks.hh.
Referenced by urbi::UCallback9< OBJ, R, P1, P2, P3, P4, P5, P6, P7, P8, P9 >::__evalcall().
template<class OBJ , class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 , class P9 > bool urbi::UCallback9< OBJ, R, P1, P2, P3, P4, P5, P6, P7, P8, P9 >::is_const_ [private]
Definition at line 1868 of file ucallbacks.hh.
Referenced by urbi::UCallback9< OBJ, R, P1, P2, P3, P4, P5, P6, P7, P8, P9 >::__evalcall().
template<class OBJ , class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 , class P9 > OBJ* urbi::UCallback9< OBJ, R, P1, P2, P3, P4, P5, P6, P7, P8, P9 >::obj [private]
Definition at line 1865 of file ucallbacks.hh.
The documentation for this class was generated from the following file:
ucallbacks.hh