Urbi SDK Remote: urbi::URBIStarterHub< T > Class Template Reference
urbi::URBIStarterHub< T > Class Template Reference
This is the class containing URBI starters.
#include <ustarter.hh>
Public Member Functions
URBIStarterHub (const std::string &name)
virtual UObjectHub * instanciate (impl::UContextImpl *ctx, const std::string &n=std::string())
Used to provide a wrapper to initialize objects in starterlist.
virtual ~URBIStarterHub ()
Detailed Description
template<class T>
class urbi::URBIStarterHub< T >
This is the class containing URBI starters.
A starter is a class whose job is to start an instance of a particular UObject subclass, resulting in the initialization of this object (registration to the kernel)
Definition at line 123 of file ustarter.hh.
Constructor & Destructor Documentation
template<class T > urbi::URBIStarterHub< T >::URBIStarterHub (const std::string & name) [inline]
Definition at line 92 of file ustarter.hxx.
References urbi::baseURBIStarterHub::list().
template<class T > urbi::URBIStarterHub< T >::~URBIStarterHub () [inline, virtual]
Definition at line 100 of file ustarter.hxx.
References urbi::baseURBIStarterHub::list().
Member Function Documentation
template<class T > UObjectHub * urbi::URBIStarterHub< T >::instanciate (impl::UContextImpl * ctx, const std::string & n = std::string()) [inline, virtual]
Used to provide a wrapper to initialize objects in starterlist.
Implements urbi::baseURBIStarterHub.
Definition at line 107 of file ustarter.hxx.
References urbi::baseURBIStarterHub::name, and urbi::setCurrentContext().
The documentation for this class was generated from the following files:
ustarter.hh
ustarter.hxx