Urbi SDK Remote: urbi::impl::UGenericCallbackImpl Class Reference
urbi::impl::UGenericCallbackImpl Class Reference
#include <ucallbacks.hh>
Public Member Functions
virtual ~UGenericCallbackImpl ()=0
virtual void initialize (UGenericCallback *owner, bool owned)=0
virtual void initialize (UGenericCallback *owner)=0
virtual void registerCallback ()=0
virtual void clear ()=0
Detailed Description
Definition at line 42 of file ucallbacks.hh.
Constructor & Destructor Documentation
urbi::impl::UGenericCallbackImpl::~UGenericCallbackImpl () [inline, pure virtual]
Definition at line 53 of file ucallbacks.hh.
Member Function Documentation
virtual void urbi::impl::UGenericCallbackImpl::clear () [pure virtual]
Implemented in urbi::impl::RemoteUGenericCallbackImpl.
Referenced by urbi::UGenericCallback::~UGenericCallback().
virtual void urbi::impl::UGenericCallbackImpl::initialize (UGenericCallback * owner) [pure virtual]
Implemented in urbi::impl::RemoteUGenericCallbackImpl.
virtual void urbi::impl::UGenericCallbackImpl::initialize (UGenericCallback * owner, bool owned) [pure virtual]
Implemented in urbi::impl::RemoteUGenericCallbackImpl.
Referenced by urbi::UGenericCallback::UGenericCallback().
virtual void urbi::impl::UGenericCallbackImpl::registerCallback () [pure virtual]
Implemented in urbi::impl::RemoteUGenericCallbackImpl.
Referenced by urbi::UGenericCallback::registerCallback().
The documentation for this class was generated from the following file:
ucallbacks.hh