Urbi SDK Remote: urbiscript code.
urbiscript code.
All the send functions are expected to be asynchronous by default: they return immediately, and send the data in a separate thread.
Functions
error_type urbi::UAbstractClient::send (const char *format,...)
Send an Urbi command.
error_type urbi::UAbstractClient::send (const urbi::UValue &v)
Send the value without any prefix or terminator.
error_type urbi::UAbstractClient::send (std::istream &is)
Send the remainder of the stream.
error_type urbi::UAbstractClient::sendBinary (const void *data, size_t len, const std::string &header)
Send an urbi Binary value.
error_type urbi::UAbstractClient::sendBin (const void *, size_t len)
Send binary data.
error_type urbi::UAbstractClient::sendBin (const void *, size_t len, const char *header,...)
Send an Urbi header followed by binary data.
error_type urbi::UAbstractClient::startPack ()
Lock the send buffer (for backward compatibility, will be removed in future versions).
error_type urbi::UAbstractClient::endPack ()
Unlock the send buffer (for backward compatibility, will be removed in future versions).
error_type urbi::UAbstractClient::pack (const char *format,...)
Append Urbi commands to the send buffer (for backward compatibility, will be removed in future versions).
error_type urbi::UAbstractClient::vpack (const char *format, va_list args)
va_list version of pack.
error_type urbi::UAbstractClient::sendFile (const std::string &f)
Send urbi commands contained in a file.
UCallbackID urbi::UAbstractClient::sendCommand (UCallback, const char *,...)
Send a command, prefixing it with a tag, and associate the given callback with this tag.
UCallbackID urbi::UAbstractClient::sendCommand (UCustomCallback, void *, const char *,...)
Send a command, prefixing it with a tag, and associate the given callback with this tag.
error_type urbi::UAbstractClient::sendSound (const char *device, const urbi::USound &sound, const char *tag=0)
Send sound data to the robot for immediate playback.
error_type urbi::UAbstractClient::putFile (const char *localName, const char *remoteName=0)
Put a file on the robot's mass storage device.
error_type urbi::UAbstractClient::putFile (const void *buffer, size_t length, const char *remoteName)
Save a buffer to a file on the robot.
Detailed Description
All the send functions are expected to be asynchronous by default: they return immediately, and send the data in a separate thread.
Function Documentation
UAbstractClient::error_type urbi::UAbstractClient::endPack () [inherited]
Unlock the send buffer (for backward compatibility, will be removed in future versions).
Definition at line 272 of file uabstractclient.cc.
References urbi::UAbstractClient::effective_send(), urbi::UAbstractClient::sendBuffer, and urbi::UAbstractClient::sendBufferLock.
Referenced by urbi::impl::call_result(), urbi::UAbstractClient::send(), urbi::UAbstractClient::sendCommand(), and urbi::impl::RemoteUVarImpl::set().
UAbstractClient::error_type urbi::UAbstractClient::pack (const char * command, ...) [inherited]
Append Urbi commands to the send buffer (for backward compatibility, will be removed in future versions).
Passing `0' is supported as means `""', but with no warning.
This function must only be called between a startPack() and the corresponding endPack(). Data is queued in the send buffer, and sent when endPack() is called.
Definition at line 396 of file uabstractclient.cc.
References urbi::UAbstractClient::rc, and urbi::UAbstractClient::vpack().
Referenced by urbi::USyncClient::syncGet_().
UAbstractClient::error_type urbi::UAbstractClient::putFile (const void * buffer, size_t length, const char * remoteName) [inherited]
Save a buffer to a file on the robot.
Definition at line 747 of file uabstractclient.cc.
References urbi::UAbstractClient::send(), urbi::UAbstractClient::sendBin(), and urbi::UAbstractClient::sendBufferLock.
UAbstractClient::error_type urbi::UAbstractClient::putFile (const char * localName, const char * remoteName = 0) [inherited]
Put a file on the robot's mass storage device.
Definition at line 729 of file uabstractclient.cc.
References urbi::UAbstractClient::send(), urbi::UAbstractClient::sendBufferLock, and urbi::UAbstractClient::sendFile().
UAbstractClient::error_type urbi::UAbstractClient::send (const char * command, ...) [inherited]
Send an Urbi command.
The syntax is similar to the printf() function. Passing `0' is supported as means `""', but with no warning.
Multiple commands can be sent in one call.
Definition at line 284 of file uabstractclient.cc.
References urbi::UAbstractClient::endPack(), urbi::UAbstractClient::rc, urbi::UAbstractClient::sendBufferLock, and urbi::UAbstractClient::vpack().
Referenced by urbi::impl::call_result(), urbi::UClient::onConnect(), urbi::UAbstractClient::onConnection(), urbi::UAbstractClient::putFile(), urbi::UAbstractClient::send(), urbi::UAbstractClient::sendBinary(), urbi::UAbstractClient::sendFile(), urbi::UClient::sendPing(), urbi::UAbstractClient::sendSound(), urbi::UAbstractClient::setVersion(), urbi::USyncClient::syncGetImage(), and urbi::USyncClient::syncGetSound().
UAbstractClient::error_type urbi::UAbstractClient::send (const urbi::UValue & v) [inherited]
Send the value without any prefix or terminator.
Definition at line 302 of file uabstractclient.cc.
References urbi::UValue::binary, urbi::BINARY_NONE, urbi::BINARY_UNKNOWN, urbi::UBinary::buildMessage(), urbi::UBinary::common, urbi::DATA_BINARY, urbi::DATA_DICTIONARY, urbi::DATA_DOUBLE, urbi::DATA_LIST, urbi::DATA_OBJECT, urbi::DATA_SLOTNAME, urbi::DATA_STRING, urbi::DATA_VOID, urbi::UValue::dictionary, urbi::UValue::list, urbi::UBinary::message, urbi::UValue::object, urbi::UObjectStruct::refName, urbi::UAbstractClient::send(), urbi::UAbstractClient::sendBinary(), urbi::UObjectStruct::size(), urbi::UList::size(), urbi::UBinary::type, and urbi::UValue::type.
UAbstractClient::error_type urbi::UAbstractClient::send (std::istream & is) [inherited]
Send the remainder of the stream.
Definition at line 374 of file uabstractclient.cc.
References urbi::UAbstractClient::effectiveSend(), urbi::UAbstractClient::rc, urbi::UAbstractClient::sendBuffer, urbi::UAbstractClient::sendBufferLock, and urbi::UAbstractClient::sendBufSize.
UAbstractClient::error_type urbi::UAbstractClient::sendBin (const void * buffer, size_t len) [inherited]
Send binary data.
Definition at line 456 of file uabstractclient.cc.
Referenced by urbi::UAbstractClient::putFile(), urbi::UAbstractClient::sendBinary(), and urbi::UAbstractClient::sendSound().
UAbstractClient::error_type urbi::UAbstractClient::sendBin (const void * buffer, size_t len, const char * header, ...) [inherited]
Send an Urbi header followed by binary data.
Definition at line 463 of file uabstractclient.cc.
References urbi::UAbstractClient::effective_send(), urbi::UAbstractClient::effectiveSend(), urbi::UAbstractClient::rc, urbi::UAbstractClient::sendBuffer, urbi::UAbstractClient::sendBufferLock, and urbi::UAbstractClient::vpack().
UAbstractClient::error_type urbi::UAbstractClient::sendBinary (const void * data, size_t len, const std::string & header) [inherited]
Send an urbi Binary value.
Definition at line 485 of file uabstractclient.cc.
References urbi::UAbstractClient::effectiveSend(), urbi::UAbstractClient::kernelMajor(), urbi::UAbstractClient::rc, urbi::UAbstractClient::send(), urbi::UAbstractClient::sendBin(), and urbi::UAbstractClient::sendBufferLock.
Referenced by urbi::UAbstractClient::send(), and urbi::impl::RemoteUVarImpl::set().
UCallbackID urbi::UAbstractClient::sendCommand (UCustomCallback cb, void * cbData, const char * cmd, ...) [inherited]
Send a command, prefixing it with a tag, and associate the given callback with this tag.
Definition at line 709 of file uabstractclient.cc.
References urbi::UAbstractClient::deleteCallback(), urbi::UAbstractClient::endPack(), urbi::UAbstractClient::fresh(), urbi::UAbstractClient::sendBufferLock, urbi::UAbstractClient::setCallback(), and urbi::UAbstractClient::vpack().
UCallbackID urbi::UAbstractClient::sendCommand (UCallback cb, const char * cmd, ...) [inherited]
Send a command, prefixing it with a tag, and associate the given callback with this tag.
Definition at line 690 of file uabstractclient.cc.
References urbi::UAbstractClient::deleteCallback(), urbi::UAbstractClient::endPack(), urbi::UAbstractClient::fresh(), urbi::UAbstractClient::sendBufferLock, urbi::UAbstractClient::setCallback(), and urbi::UAbstractClient::vpack().
UAbstractClient::error_type urbi::UAbstractClient::sendFile (const std::string & f) [inherited]
Send urbi commands contained in a file.
The file "/dev/stdin" is recognized as referring to std::cin.
Definition at line 440 of file uabstractclient.cc.
References urbi::UAbstractClient::send().
Referenced by urbi::initialize(), and urbi::UAbstractClient::putFile().
UAbstractClient::error_type urbi::UAbstractClient::sendSound (const char * device, const urbi::USound & sound, const char * tag = 0) [inherited]
Send sound data to the robot for immediate playback.
If tag is set, an URBI system "stop" message with this tag will be generated when the sound has been played. The sound data is copied in case of asynchronous send, and may be safely deleted as soon as this function returns.
Definition at line 579 of file uabstractclient.cc.
References urbi::USound::channels, urbi::USound::data, urbi::UAbstractClient::deleteCallback(), urbi::UAbstractClient::fresh(), urbi::USound::rate, urbi::USound::sampleFormat, urbi::USound::sampleSize, urbi::UAbstractClient::send(), urbi::UAbstractClient::sendBin(), urbi::sendSound_(), urbi::UAbstractClient::setCallback(), urbi::USound::size, urbi::SOUND_MP3, urbi::SOUND_OGG, urbi::SOUND_RAW, urbi::SOUND_WAV, and urbi::USound::soundFormat.
UAbstractClient::error_type urbi::UAbstractClient::startPack () [inherited]
Lock the send buffer (for backward compatibility, will be removed in future versions).
In threaded environnments, this function lock()s the send buffer so that only the calling thread can call the send functions. Otherwise do nothing.
Definition at line 265 of file uabstractclient.cc.
References urbi::UAbstractClient::sendBufferLock.
Referenced by urbi::impl::call_result(), and urbi::impl::RemoteUVarImpl::set().
UAbstractClient::error_type urbi::UAbstractClient::vpack (const char * format, va_list args) [inherited]
va_list version of pack.
Passing `0' is supported as means `""', but with no warning.
Definition at line 409 of file uabstractclient.cc.
References urbi::UAbstractClient::rc, urbi::UAbstractClient::sendBuffer, urbi::UAbstractClient::sendBufferLock, and urbi::UAbstractClient::sendBufSize.
Referenced by urbi::UAbstractClient::pack(), urbi::UAbstractClient::send(), urbi::UAbstractClient::sendBin(), urbi::UAbstractClient::sendCommand(), and urbi::USyncClient::syncGet_().