Urbi SDK Remote: urbi-launch.cc File Reference
liburbi/urbi-launch.cc File Reference
#include <string>
#include <libport/cassert>
#include <cstdarg>
#include <libport/cstdlib>
#include <iostream>
#include <stdexcept>
#include <sdk/config.h>
#include <boost/assign/list_of.hpp>
#include <libport/cli.hh>
#include <libport/containers.hh>
#include <libport/debug.hh>
#include <libport/file-system.hh>
#include <libport/foreach.hh>
#include <libport/path.hh>
#include <libport/package-info.hh>
#include <libport/program-name.hh>
#include <libport/sysexits.hh>
#include <libport/unistd.h>
#include <libport/windows.hh>
#include <libport/option-parser.hh>
#include <libport/xltdl.hh>
#include <urbi/exit.hh>
#include <urbi/package-info.hh>
#include <urbi/uclient.hh>
#include <urbi/urbi-root.hh>
Functions
GD_CATEGORY (urbi-launch)
static UCallbackAction onError (const UMessage &msg)
static UCallbackAction onDone (const UMessage &)
static int connect_plugin (const std::string &host, int port, const libport::cli_args_type &modules)
static void usage (libport::OptionParser &parser)
static void version ()
static int urbi_launch_ (int argc, const char *argv[], UrbiRoot &urbi_root)
int URBI_SDK_API urbi_launch (int argc, const char *argv[], UrbiRoot &urbi_root)
Function Documentation
static int connect_plugin (const std::string & host, int port, const libport::cli_args_type & modules) [static]
Definition at line 61 of file liburbi/urbi-launch.cc.
References urbi::callback(), urbi::UAbstractClient::error(), urbi::exit(), onDone(), onError(), urbi::UAbstractClient::setCallback(), and urbi::UAbstractClient::setErrorCallback().
Referenced by urbi_launch_().
GD_CATEGORY (urbi- launch)
static UCallbackAction onDone (const UMessage &) [static]
Definition at line 55 of file liburbi/urbi-launch.cc.
References urbi::exit().
Referenced by connect_plugin(), and urbi::UGenericCallback::syncEval().
static UCallbackAction onError (const UMessage & msg) [static]
Definition at line 48 of file liburbi/urbi-launch.cc.
References urbi::UMessage::message.
Referenced by connect_plugin().
int URBI_SDK_API urbi_launch (int argc, const char * argv[], UrbiRoot & urbi_root)
Definition at line 231 of file liburbi/urbi-launch.cc.
References urbi::exit(), and urbi_launch_().
static int urbi_launch_ (int argc, const char * argv[], UrbiRoot & urbi_root) [static]
Start a new engine and plug the module
Load the module in a running engine as a plugin
Connect the module to a running engine (remote uobject)
Server host name.
Server port.
Definition at line 111 of file liburbi/urbi-launch.cc.
References connect_plugin(), debug(), UrbiRoot::load_custom(), UrbiRoot::load_plugin(), UrbiRoot::load_remote(), urbi::MODE_REMOTE, UrbiRoot::uobjects_path(), UrbiRoot::urbi_main(), usage(), and version().
Referenced by urbi_launch().
static void usage (libport::OptionParser & parser) [static]
Definition at line 79 of file liburbi/urbi-launch.cc.
References urbi::exit().
Referenced by urbi_launch_().
static void version () [static]
Definition at line 102 of file liburbi/urbi-launch.cc.
References urbi::exit(), and urbi::package_info().
Referenced by urbi_launch_().