Urbi SDK Remote: urbi::impl Namespace Reference
urbi::impl Namespace Reference
The interfaces UContextImpl, UVarImpl, UObjectImpl and UGenericCallbackImpl are what must be implemented to make an UObject backend.
Classes
class RemoteUContextImpl
class RemoteUObjectImpl
class RemoteUVarImpl
class RemoteUGenericCallbackImpl
class UGenericCallbackImpl
class UContextImpl
class UObjectImpl
class UVarImpl
Typedefs
typedef boost::unordered_map
< std::string,
impl::UContextImpl * > contexts_type
Functions
std::vector< std::string > listModules ()
Return the list of modules that can be bound() into a UContext.
impl::UContextImpl * makeRemoteContext (const std::string &host, const std::string &port)
Return a new remote context. Implemented in remote library only.
impl::UContextImpl * getRemoteContext (const std::string &host, const std::string &port)
Return a remote context, only creates one context per host:port pair.
static void call_result (UAbstractClient *client, std::string var, const UValue &retval, const std::exception *e)
GD_CATEGORY (LibUObject)
static std::string rtp_id ()
URBI_SDK_API UContextImpl * getPluginContext ()
Return the plugin context. Implemented in plugin library only.
template<typename T >
void deletor (T *ptr)
Variables
static contexts_type contexts
Detailed Description
The interfaces UContextImpl, UVarImpl, UObjectImpl and UGenericCallbackImpl are what must be implemented to make an UObject backend.
Typedef Documentation
typedef boost::unordered_map<std::string, impl::UContextImpl*> urbi::impl::contexts_type
Definition at line 80 of file uobject.cc.
Function Documentation
static void urbi::impl::call_result (UAbstractClient * client, std::string var, const UValue & retval, const std::exception * e) [static]
Definition at line 345 of file uobject.cc.
References urbi::DATA_BINARY, urbi::DATA_VOID, urbi::UAbstractClient::endPack(), urbi::UAbstractClient::send(), urbi::UAbstractClient::startPack(), urbi::UValue::type, URBI_SEND_COMMA_COMMAND_C, and URBI_SEND_COMMAND_C.
Referenced by urbi::impl::RemoteUContextImpl::evalFunctionMessage().
template<typename T > void urbi::impl::deletor (T * ptr)
Definition at line 60 of file ucontext-impl.hxx.
urbi::impl::GD_CATEGORY (LibUObject)
URBI_SDK_API UContextImpl* urbi::impl::getPluginContext ()
Return the plugin context. Implemented in plugin library only.
URBI_SDK_API UContextImpl * urbi::impl::getRemoteContext (const std::string & host, const std::string & port)
Return a remote context, only creates one context per host:port pair.
URBI_SDK_API std::vector< std::string > urbi::impl::listModules ()
Return the list of modules that can be bound() into a UContext.
URBI_SDK_API UContextImpl * urbi::impl::makeRemoteContext (const std::string & host, const std::string & port)
Return a new remote context. Implemented in remote library only.
static std::string urbi::impl::rtp_id () [static]
Definition at line 120 of file uvar.cc.
References urbi::getFilteredHostname().
Referenced by urbi::impl::RemoteUContextImpl::makeRTPLink(), and urbi::impl::RemoteUVarImpl::set().
Variable Documentation
contexts_type urbi::impl::contexts [static]
Definition at line 81 of file uobject.cc.