Urbi SDK Remote: urbi Namespace Reference
urbi Namespace Reference
Global definition of the starterlist.
Namespaces
namespace compatibility
namespace impl
The interfaces UContextImpl, UVarImpl, UObjectImpl and UGenericCallbackImpl are what must be implemented to make an UObject backend.
Classes
class CustomUVar
UVar wrapper with a custom data field.
class Exit
class UObjectSocket
Use this class instead of libport::Socket when you need an UObject which is also a Socket.
class UCallbackInfo
class UAbstractClient
Interface for an URBI wrapper object.
class UCallbackWrapper
Wrapper around a callback function. Use callback() to create them.
class UCallbackWrapperF
class UCallbackWrapperCF
class UCallbackWrapper0
class UCallbackWrapper1
class UCallbackWrapper2
class UCallbackWrapper3
class UCallbackWrapper4
class BinaryData
class UBinary
Binary data of known or unknown type.
class UGenericCallback
Function and Event storage mechanism This heavily overloaded class is the only way in C++ to make life easy from the the interface user point's of view.
class UCallback0
class UCallbacknotifyend0
class UFCallback0
class UCallback1
class UCallbacknotifyend1
class UFCallback1
class UCallback2
class UCallbacknotifyend2
class UFCallback2
class UCallback3
class UCallbacknotifyend3
class UFCallback3
class UCallback4
class UCallbacknotifyend4
class UFCallback4
class UCallback5
class UCallbacknotifyend5
class UFCallback5
class UCallback6
class UCallbacknotifyend6
class UFCallback6
class UCallback7
class UCallbacknotifyend7
class UFCallback7
class UCallback8
class UCallbacknotifyend8
class UFCallback8
class UCallback9
class UCallbacknotifyend9
class UFCallback9
class UCallback10
class UCallbacknotifyend10
class UFCallback10
class UCallback11
class UCallbacknotifyend11
class UFCallback11
class UCallback12
class UCallbacknotifyend12
class UFCallback12
class UCallback13
class UCallbacknotifyend13
class UFCallback13
class UCallback14
class UCallbacknotifyend14
class UFCallback14
class UCallback15
class UCallbacknotifyend15
class UFCallback15
class UCallback16
class UCallbacknotifyend16
class UFCallback16
class UBoostFunctionCallback0
class UBoostFunctionCallback1
class UBoostFunctionCallback2
class UBoostFunctionCallback3
class UBoostFunctionCallback4
class UBoostFunctionCallback5
class UBoostFunctionCallback6
class UBoostFunctionCallback7
class UBoostFunctionCallback8
class UBoostFunctionCallback9
class UBoostFunctionCallback10
class UClient
Linux implementation of UAbstractClient.
class UAutoValue
UValue with implicit constructors.
class UContext
Methods available in both UObject and UVar Wrapper around UContextImpl to enable access through inheritance.
struct wavheader
class UEvent
UEvent class definition.
class UImage
Class encapsulating an image.
class UMessage
Class containing all informations related to an URBI message.
class UObjectHub
Main UObjectHub class definition.
class UObject
Main UObject class definition Each UObject instance corresponds to an URBI object.
struct uvalue_caster< UObject * >
struct uvalue_caster< T * >
class UProp
Provides easy access to variable properties.
class USound
Class encapsulating sound information.
class baseURBIStarter
class URBIStarter
This is the class containing URBI starters.
class baseURBIStarterHub
URBIStarter base class used to store heterogeneous template class objects in starterlist.
class URBIStarterHub
This is the class containing URBI starters.
class USyncClient
UClient linux implementation with support for synchronous extra functions.
class USystemMessage
USystemMessage class definition.
class UStringSystemMessage
UStringSystemMessage class definition.
class USystem
Main USystem class definition.
struct UTable
struct UVarTable
class UTimerCallback
Timer mechanism.
class UTimerCallbackobj
class UList
Class storing URBI List type.
class UNamedValue
class UObjectStruct
class UValue
Container for a value that handles all types known to URBI.
struct uvalue_caster
struct uvar_ref_traits
struct uvar_ref_traits< UVar >
struct uvalue_cast_return_type
struct uvalue_cast_return_type< const UValue & >
struct uvalue_caster< UVar >
struct uvalue_caster< boost::unordered_map< std::string, V > >
class UVar
UVar class definition.
Typedefs
typedef std::vector< std::string > files_type
typedef std::list< UObject * > UObjectList
typedef boost::shared_ptr
< std::string > TimerHandle
typedef unsigned int UCallbackID
typedef UCallbackAction(* UCallback)(const UMessage &msg)
Callback prototypes.
typedef UCallbackAction(* UCustomCallback)(void *callbackData, const UMessage &msg)
typedef std::list< BinaryData > binaries_type
List of the binaries.
typedef unsigned char byte
typedef int UReturn
typedef std::list
< UTimerCallback * > UTimerTable
typedef boost::unordered_map
< std::string, UValue > UDictionary
Enumerations
enum UCallbackType { UCB_, UCB_C }
enum UCallbackAction { URBI_CONTINUE = 0, URBI_REMOVE }
Return values for the callcack functions.
enum { URBI_MAX_TAG_LENGTH = 64 }
Maximum length of an URBI tag.
enum UBinaryType { BINARY_NONE, BINARY_UNKNOWN, BINARY_IMAGE, BINARY_SOUND }
enum UBlendType {
UMIX, UADD, UDISCARD, UQUEUE,
UCANCEL, UNORMAL
}
Possible blending mode for an UVar.
enum UObjectMode { MODE_PLUGIN = 1, MODE_REMOTE }
Possible UObject running modes.
enum USystemExternalMessage {
UEM_EVALFUNCTION, UEM_ASSIGNVALUE, UEM_EMITEVENT, UEM_ENDEVENT,
UEM_NEW, UEM_DELETE, UEM_INIT, UEM_TIMER,
UEM_NORTP
}
enum UImageFormat {
IMAGE_UNKNOWN = 0, IMAGE_RGB = 1, IMAGE_YCbCr = 2, IMAGE_YUV = 2,
IMAGE_JPEG = 3, IMAGE_PPM = 4, IMAGE_YUV422 = 5, IMAGE_GREY8 = 6,
IMAGE_GREY4 = 7, IMAGE_YUV411_PLANAR = 8
}
enum UMessageType { MESSAGE_SYSTEM, MESSAGE_ERROR, MESSAGE_DATA }
enum LockMode {
LOCK_NONE, LOCK_FUNCTION, LOCK_INSTANCE, LOCK_CLASS,
LOCK_MODULE
}
Locking model.
enum UProperty {
PROP_RANGEMIN, PROP_RANGEMAX, PROP_SPEEDMIN, PROP_SPEEDMAX,
PROP_BLEND, PROP_DELTA, PROP_CONSTANT
}
URBI properties associated to a variable.
enum USoundFormat {
SOUND_RAW = 0, SOUND_WAV = 1, SOUND_MP3 = 2, SOUND_OGG = 3,
SOUND_UNKNOWN = 4
}
enum USoundSampleFormat { SAMPLE_SIGNED = 1, SAMPLE_UNSIGNED = 2, SAMPLE_FLOAT = 3 }
enum UTransmitFormat { URBI_TRANSMIT_JPEG, URBI_TRANSMIT_YCbCr }
enum USystemChannel { NEW_CHANNEL }
Possible value types a UValue can contain.
enum UDataType {
DATA_BINARY, DATA_DICTIONARY, DATA_DOUBLE, DATA_LIST,
DATA_OBJECT, DATA_STRING, DATA_SLOTNAME, DATA_VOID
}
Possible value types a UValue can contain.
Functions
static void noop (impl::UContextImpl *)
impl::UContextImpl * getCurrentContext ()
Will be used if no context is explicitly passed.
void setCurrentContext (impl::UContextImpl *impl)
void setThreadLimit (size_t nThreads)
Set maximum number of threads to use for threaded calls (0=unlimited).
void echo (const char *format,...)
echo method
std::string getFilteredHostname ()
Return current hostname mangled to fit into an urbiscript variable name.
int main (int argc, const char *argv[], UrbiRoot &root, bool block=true, bool errors=false)
Initialisation method using C style arguments.
std::ostream & operator<< (std::ostream &o, const UVar &u)
Report u on o for debugging.
UCallbackAction debug (const UMessage &msg)
static UCallbackAction endProgram (const UMessage &msg)
static void usage ()
static void version ()
int initialize (const std::string &host, int port, size_t buflen, bool exitOnDisconnect, bool server, const files_type &files, bool useSyncClient)
URBI_SDK_API int main (const libport::cli_args_type &args, UrbiRoot &root, bool block=true, bool errors=false)
Initialisation method.
UObjectMode running_mode ()
int kernelMajor ()
int kernelMinor ()
const std::string & kernelVersion ()
std::ostream & default_stream ()
Return a stream for error, preferrably the one the defaultClient.
static UCallbackAction sendSound_ (void *cb, const UMessage &msg)
std::string getClientConnectionID (const UAbstractClient *cli)
UAbstractClient * client_get (std::ostream &o)
UClient * getDefaultClient ()
Return the first UClient created by the program.
UClient & get_default_client ()
Same as getDefaultClient(), but as a reference.
void setDefaultClient (UClient *cl)
Redefine the default client.
std::ostream & unarmorAndSend (const char *str, UAbstractClient *c=(UAbstractClient *) getDefaultClient())
Send a possibly armored string to the default client.
void execute (void)
Must be called at the last line of your main() function.
void exit (int code)
Terminate your URBI program.
UClient & connect (const std::string &host)
Create a new UClient object.
void disconnect (UClient &client)
Destroy an UClient object Be careful: don't use client after called this function.
int convertRGBtoYCrCb (const byte *sourceImage, size_t bufferSize, byte *destinationImage)
Convert a buffer sourceImage, which contains an RGB image, to a buffer for the destinationImage, which will contain a YCrCb image.
int convertYCrCbtoYCbCr (const byte *sourceImage, size_t bufferSize, byte *destinationImage)
Convert a buffer sourceImage, which contains an YCrCb, image to a buffer for the destinationImage, which will contain a YCbCr image.
int convertYCrCbtoRGB (const byte *sourceImage, size_t bufferSize, byte *destinationImage)
Convert a buffer sourceImage, which contains an YCrCb, image to a buffer for the destinationImage, which will contain a RGB image.
int convert_jpeg_to (const byte *source, size_t sourcelen, UImageFormat dest_format, byte **dest, size_t &size, size_t &w, size_t &h)
Convert a buffer source, which contains a JPEG image, to a buffer for the dest, which will contain a RGB/YCrCb image (depending on dest_format).
int convertJPEGtoYCrCb (const byte *source, size_t sourcelen, byte **dest, size_t &size, size_t &w, size_t &h)
int convertJPEGtoRGB (const byte *source, size_t sourcelen, byte **dest, size_t &size, size_t &w, size_t &h)
int convertRGBtoJPEG (const byte *source, size_t w, size_t h, byte *dest, size_t &size, int quality)
Convert a buffer source, which contains an RGB image, to a buffer for the dest, which will contain a JPEG image.
int convertYCrCbtoJPEG (const byte *source, size_t w, size_t h, byte *dest, size_t &size, int quality)
Convert a buffer source, which contains an YCrCb image, to a buffer for the dest, which will contain a JPEG image.
urbi_jpeg_error_exit (j_common_ptr cinfo)
static void init_destination (j_compress_ptr)
static boolean empty_output_buffer (j_compress_ptr)
static void term_destination (j_compress_ptr)
int convert (const UImage &src, UImage &dest)
Convert the image src to the image dest.
void dup (unsigned short *dst, unsigned short *src, int count)
void dup (byte *dst, byte *src, int count)
template<typename D >
void pud (D *dst, D *src, int count)
template<class S , class D >
void copy (S *src, D *dst, int sc, int dc, int sr, int dr, int count, bool sf, bool df)
int convert (const USound &source, USound &dest)
Conversion between various sound formats.
UCLIENT_OPTION_IMPL (USyncClient, bool, startCallbackThread)
UCLIENT_OPTION_IMPL (USyncClient, USyncClient::connect_callback_type, connectCallback)
static void destroySocket (libport::Socket *s)
const libport::PackageInfo & package_info ()
Package information about liburbi and UObjects.
std::ostream & operator<< (std::ostream &o, const UBinary &t)
const char * format_string (UImageFormat f)
UImageFormat parse_image_format (const std::string &s)
const char * format_string (USoundFormat f)
Conversion to string.
USoundFormat parse_sound_format (const std::string &)
Parse a sound format string.
std::istream & operator>> (std::istream &is, USoundSampleFormat &f)
std::ostream & operator<< (std::ostream &o, USoundSampleFormat f)
std::ostream & operator<< (std::ostream &o, const USound &s)
int & kernelMajor (std::ostream &o)
If a kernel version was associated to this stream, its value.
UVALUE_OPERATORS (const UDictionary &d, DATA_DICTIONARY, dictionary, new UDictionary(d))
UVALUE_OPERATORS (const UObjectStruct &v, DATA_OBJECT, object, new UObjectStruct(v)) void UValue
std::ostream & operator<< (std::ostream &o, const UList &t)
std::ostream & operator<< (std::ostream &s, const urbi::UDictionary &d)
std::ostream & operator<< (std::ostream &o, const UObjectStruct &t)
bool is_blendtype (int i)
const char * name (UBlendType u)
UBlendType ublendtype (const char *cp)
template<typename T >
uvar_ref_traits< typename
uvalue_cast_return_type< T >
::type >::type uvar_uvalue_cast (UValue &v)
template<>
UVar & uvar_uvalue_cast< UVar & > (UValue &v)
template<class R >
UGenericCallback * createUCallback (UObject &owner, UVar *target, const std::string &type, R(*fun)(), const std::string &funname, impl::UContextImpl *ctx)
MKUCreateCallBack0 (,)
MKUCreateCallBack0 (const,)
MKCreateUCallBackEnd0 (,)
MKCreateUCallBackEnd0 (, const)
MKCreateUCallBackEnd0 (const, const)
template<class R , class P1 >
UGenericCallback * createUCallback (UObject &owner, UVar *target, const std::string &type, R(*fun)(P1), const std::string &funname, impl::UContextImpl *ctx)
MKUCreateCallBack1 (,)
MKUCreateCallBack1 (const,)
MKCreateUCallBackEnd1 (,)
MKCreateUCallBackEnd1 (, const)
MKCreateUCallBackEnd1 (const, const)
template<class R , class P1 , class P2 >
UGenericCallback * createUCallback (UObject &owner, UVar *target, const std::string &type, R(*fun)(P1, P2), const std::string &funname, impl::UContextImpl *ctx)
MKUCreateCallBack2 (,)
MKUCreateCallBack2 (const,)
MKCreateUCallBackEnd2 (,)
MKCreateUCallBackEnd2 (, const)
MKCreateUCallBackEnd2 (const, const)
template<class R , class P1 , class P2 , class P3 >
UGenericCallback * createUCallback (UObject &owner, UVar *target, const std::string &type, R(*fun)(P1, P2, P3), const std::string &funname, impl::UContextImpl *ctx)
MKUCreateCallBack3 (,)
MKUCreateCallBack3 (const,)
MKCreateUCallBackEnd3 (,)
MKCreateUCallBackEnd3 (, const)
MKCreateUCallBackEnd3 (const, const)
template<class R , class P1 , class P2 , class P3 , class P4 >
UGenericCallback * createUCallback (UObject &owner, UVar *target, const std::string &type, R(*fun)(P1, P2, P3, P4), const std::string &funname, impl::UContextImpl *ctx)
MKUCreateCallBack4 (,)
MKUCreateCallBack4 (const,)
MKCreateUCallBackEnd4 (,)
MKCreateUCallBackEnd4 (, const)
MKCreateUCallBackEnd4 (const, const)
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 >
UGenericCallback * createUCallback (UObject &owner, UVar *target, const std::string &type, R(*fun)(P1, P2, P3, P4, P5), const std::string &funname, impl::UContextImpl *ctx)
MKUCreateCallBack5 (,)
MKUCreateCallBack5 (const,)
MKCreateUCallBackEnd5 (,)
MKCreateUCallBackEnd5 (, const)
MKCreateUCallBackEnd5 (const, const)
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
UGenericCallback * createUCallback (UObject &owner, UVar *target, const std::string &type, R(*fun)(P1, P2, P3, P4, P5, P6), const std::string &funname, impl::UContextImpl *ctx)
MKUCreateCallBack6 (,)
MKUCreateCallBack6 (const,)
MKCreateUCallBackEnd6 (,)
MKCreateUCallBackEnd6 (, const)
MKCreateUCallBackEnd6 (const, const)
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 >
UGenericCallback * createUCallback (UObject &owner, UVar *target, const std::string &type, R(*fun)(P1, P2, P3, P4, P5, P6, P7), const std::string &funname, impl::UContextImpl *ctx)
MKUCreateCallBack7 (,)
MKUCreateCallBack7 (const,)
MKCreateUCallBackEnd7 (,)
MKCreateUCallBackEnd7 (, const)
MKCreateUCallBackEnd7 (const, const)
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 >
UGenericCallback * createUCallback (UObject &owner, UVar *target, const std::string &type, R(*fun)(P1, P2, P3, P4, P5, P6, P7, P8), const std::string &funname, impl::UContextImpl *ctx)
MKUCreateCallBack8 (,)
MKUCreateCallBack8 (const,)
MKCreateUCallBackEnd8 (,)
MKCreateUCallBackEnd8 (, const)
MKCreateUCallBackEnd8 (const, const)
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 , class P9 >
UGenericCallback * createUCallback (UObject &owner, UVar *target, const std::string &type, R(*fun)(P1, P2, P3, P4, P5, P6, P7, P8, P9), const std::string &funname, impl::UContextImpl *ctx)
MKUCreateCallBack9 (,)
MKUCreateCallBack9 (const,)
MKCreateUCallBackEnd9 (,)
MKCreateUCallBackEnd9 (, const)
MKCreateUCallBackEnd9 (const, const)
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 , class P9 , class P10 >
UGenericCallback * createUCallback (UObject &owner, UVar *target, const std::string &type, R(*fun)(P1, P2, P3, P4, P5, P6, P7, P8, P9, P10), const std::string &funname, impl::UContextImpl *ctx)
MKUCreateCallBack10 (,)
MKUCreateCallBack10 (const,)
MKCreateUCallBackEnd10 (,)
MKCreateUCallBackEnd10 (, const)
MKCreateUCallBackEnd10 (const, const)
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 , class P9 , class P10 , class P11 >
UGenericCallback * createUCallback (UObject &owner, UVar *target, const std::string &type, R(*fun)(P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11), const std::string &funname, impl::UContextImpl *ctx)
MKUCreateCallBack11 (,)
MKUCreateCallBack11 (const,)
MKCreateUCallBackEnd11 (,)
MKCreateUCallBackEnd11 (, const)
MKCreateUCallBackEnd11 (const, const)
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 , class P9 , class P10 , class P11 , class P12 >
UGenericCallback * createUCallback (UObject &owner, UVar *target, const std::string &type, R(*fun)(P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12), const std::string &funname, impl::UContextImpl *ctx)
MKUCreateCallBack12 (,)
MKUCreateCallBack12 (const,)
MKCreateUCallBackEnd12 (,)
MKCreateUCallBackEnd12 (, const)
MKCreateUCallBackEnd12 (const, const)
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 , class P9 , class P10 , class P11 , class P12 , class P13 >
UGenericCallback * createUCallback (UObject &owner, UVar *target, const std::string &type, R(*fun)(P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13), const std::string &funname, impl::UContextImpl *ctx)
MKUCreateCallBack13 (,)
MKUCreateCallBack13 (const,)
MKCreateUCallBackEnd13 (,)
MKCreateUCallBackEnd13 (, const)
MKCreateUCallBackEnd13 (const, const)
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 , class P9 , class P10 , class P11 , class P12 , class P13 , class P14 >
UGenericCallback * createUCallback (UObject &owner, UVar *target, const std::string &type, R(*fun)(P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14), const std::string &funname, impl::UContextImpl *ctx)
MKUCreateCallBack14 (,)
MKUCreateCallBack14 (const,)
MKCreateUCallBackEnd14 (,)
MKCreateUCallBackEnd14 (, const)
MKCreateUCallBackEnd14 (const, const)
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 , class P9 , class P10 , class P11 , class P12 , class P13 , class P14 , class P15 >
UGenericCallback * createUCallback (UObject &owner, UVar *target, const std::string &type, R(*fun)(P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15), const std::string &funname, impl::UContextImpl *ctx)
MKUCreateCallBack15 (,)
MKUCreateCallBack15 (const,)
MKCreateUCallBackEnd15 (,)
MKCreateUCallBackEnd15 (, const)
MKCreateUCallBackEnd15 (const, const)
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 , class P9 , class P10 , class P11 , class P12 , class P13 , class P14 , class P15 , class P16 >
UGenericCallback * createUCallback (UObject &owner, UVar *target, const std::string &type, R(*fun)(P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15, P16), const std::string &funname, impl::UContextImpl *ctx)
MKUCreateCallBack16 (,)
MKUCreateCallBack16 (const,)
MKCreateUCallBackEnd16 (,)
MKCreateUCallBackEnd16 (, const)
MKCreateUCallBackEnd16 (const, const)
template<class R >
UGenericCallback * createUCallback (UObject &owner, UVar *target, const std::string &type, boost::function0< R > fun, const std::string &funname, impl::UContextImpl *ctx)
template<class R >
UGenericCallback * createUCallbackStd (UObject &owner, UVar *target, const std::string &type, R(ATTRIBUTE_STDCALL *fun)(), const std::string &funname, impl::UContextImpl *ctx)
template<class R , class P1 >
UGenericCallback * createUCallback (UObject &owner, UVar *target, const std::string &type, boost::function1< R, P1 > fun, const std::string &funname, impl::UContextImpl *ctx)
template<class R , class P1 >
UGenericCallback * createUCallbackStd (UObject &owner, UVar *target, const std::string &type, R(ATTRIBUTE_STDCALL *fun)(P1), const std::string &funname, impl::UContextImpl *ctx)
template<class R , class P1 , class P2 >
UGenericCallback * createUCallback (UObject &owner, UVar *target, const std::string &type, boost::function2< R, P1, P2 > fun, const std::string &funname, impl::UContextImpl *ctx)
template<class R , class P1 , class P2 >
UGenericCallback * createUCallbackStd (UObject &owner, UVar *target, const std::string &type, R(ATTRIBUTE_STDCALL *fun)(P1, P2), const std::string &funname, impl::UContextImpl *ctx)
template<class R , class P1 , class P2 , class P3 >
UGenericCallback * createUCallback (UObject &owner, UVar *target, const std::string &type, boost::function3< R, P1, P2, P3 > fun, const std::string &funname, impl::UContextImpl *ctx)
template<class R , class P1 , class P2 , class P3 >
UGenericCallback * createUCallbackStd (UObject &owner, UVar *target, const std::string &type, R(ATTRIBUTE_STDCALL *fun)(P1, P2, P3), const std::string &funname, impl::UContextImpl *ctx)
template<class R , class P1 , class P2 , class P3 , class P4 >
UGenericCallback * createUCallback (UObject &owner, UVar *target, const std::string &type, boost::function4< R, P1, P2, P3, P4 > fun, const std::string &funname, impl::UContextImpl *ctx)
template<class R , class P1 , class P2 , class P3 , class P4 >
UGenericCallback * createUCallbackStd (UObject &owner, UVar *target, const std::string &type, R(ATTRIBUTE_STDCALL *fun)(P1, P2, P3, P4), const std::string &funname, impl::UContextImpl *ctx)
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 >
UGenericCallback * createUCallback (UObject &owner, UVar *target, const std::string &type, boost::function5< R, P1, P2, P3, P4, P5 > fun, const std::string &funname, impl::UContextImpl *ctx)
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 >
UGenericCallback * createUCallbackStd (UObject &owner, UVar *target, const std::string &type, R(ATTRIBUTE_STDCALL *fun)(P1, P2, P3, P4, P5), const std::string &funname, impl::UContextImpl *ctx)
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
UGenericCallback * createUCallback (UObject &owner, UVar *target, const std::string &type, boost::function6< R, P1, P2, P3, P4, P5, P6 > fun, const std::string &funname, impl::UContextImpl *ctx)
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
UGenericCallback * createUCallbackStd (UObject &owner, UVar *target, const std::string &type, R(ATTRIBUTE_STDCALL *fun)(P1, P2, P3, P4, P5, P6), const std::string &funname, impl::UContextImpl *ctx)
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 >
UGenericCallback * createUCallback (UObject &owner, UVar *target, const std::string &type, boost::function7< R, P1, P2, P3, P4, P5, P6, P7 > fun, const std::string &funname, impl::UContextImpl *ctx)
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 >
UGenericCallback * createUCallbackStd (UObject &owner, UVar *target, const std::string &type, R(ATTRIBUTE_STDCALL *fun)(P1, P2, P3, P4, P5, P6, P7), const std::string &funname, impl::UContextImpl *ctx)
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 >
UGenericCallback * createUCallback (UObject &owner, UVar *target, const std::string &type, boost::function8< R, P1, P2, P3, P4, P5, P6, P7, P8 > fun, const std::string &funname, impl::UContextImpl *ctx)
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 >
UGenericCallback * createUCallbackStd (UObject &owner, UVar *target, const std::string &type, R(ATTRIBUTE_STDCALL *fun)(P1, P2, P3, P4, P5, P6, P7, P8), const std::string &funname, impl::UContextImpl *ctx)
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 , class P9 >
UGenericCallback * createUCallback (UObject &owner, UVar *target, const std::string &type, boost::function9< R, P1, P2, P3, P4, P5, P6, P7, P8, P9 > fun, const std::string &funname, impl::UContextImpl *ctx)
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 , class P9 >
UGenericCallback * createUCallbackStd (UObject &owner, UVar *target, const std::string &type, R(ATTRIBUTE_STDCALL *fun)(P1, P2, P3, P4, P5, P6, P7, P8, P9), const std::string &funname, impl::UContextImpl *ctx)
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 , class P9 , class P10 >
UGenericCallback * createUCallback (UObject &owner, UVar *target, const std::string &type, boost::function10< R, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 > fun, const std::string &funname, impl::UContextImpl *ctx)
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 , class P9 , class P10 >
UGenericCallback * createUCallbackStd (UObject &owner, UVar *target, const std::string &type, R(ATTRIBUTE_STDCALL *fun)(P1, P2, P3, P4, P5, P6, P7, P8, P9, P10), const std::string &funname, impl::UContextImpl *ctx)
UObjectHub * getUObjectHub (const std::string &n)
UObject * getUObject (const std::string &n)
void uobject_unarmorAndSend (const char *str)
Send Urbi code (ghost connection in plugin mode, default connection in remote mode).
void send (const char *str)
void send (const std::string &str)
void send (const void *buf, size_t size)
Send buf to the connection hosting the UObject.
UObjectMode getRunningMode ()
bool isPluginMode ()
bool isRemoteMode ()
int URBI_SDK_API initialize (const std::string &host, int port, size_t buflen, bool exitOnDisconnect, bool server=false)
Initialisation method, for remote mode only, that returns.
std::ostream & operator<< (std::ostream &s, const UMessage &m)
template<typename T >
int getValue (UMessage *m, T &val)
Set val to the value of m.
template<>
int getValue< double > (UMessage *m, double &val)
UValue & operator, (UValue &a, const UObject *b)
bool is_propertytype (int i)
const char * name (UProperty u)
UProperty uproperty (const char *cp)
std::ostream & operator<< (std::ostream &s, const UValue &v)
template<typename Type >
uvar_ref_traits< typename
uvalue_cast_return_type< Type >
::type >::type uvalue_cast (UValue &v)
UVALUE_CASTER_DEFINE (std::string)
UVALUE_CASTER_DEFINE (bool)
UVALUE_CASTER_DEFINE (UImage)
UVALUE_CASTER_DEFINE (USound)
UVALUE_CASTER_DEFINE (const UValue &)
UVALUE_CASTER_DEFINE (UValue &)
UVALUE_CASTER_DEFINE (const UValue)
UVALUE_CASTER_DECLARE (UBinary)
UVALUE_CASTER_DECLARE (UList)
UVALUE_CASTER_DECLARE (UDictionary)
UVALUE_CASTER_DECLARE (UObjectStruct)
UVALUE_CASTER_DECLARE (const char *)
UVALUE_CONTAINER_CASTER_DECLARE (std::list)
UVALUE_CONTAINER_CASTER_DECLARE (std::vector)
template<typename V >
UValue & operator, (UValue &v, const boost::unordered_map< std::string, V > &d)
UCallbackWrapper & callback (UCallback cb)
Generate a callback wrapper used by UAbstractClient::setCallback().
UCallbackWrapper & callback (UCustomCallback cb, void *data)
template<class C >
UCallbackWrapper & callback (C &ref, UCallbackAction(C::*func)(const UMessage &))
template<class C , class P1 >
UCallbackWrapper & callback (C &ref, UCallbackAction(C::*func)(P1, const UMessage &), P1 p1)
template<class C , class P1 , class P2 >
UCallbackWrapper & callback (C &ref, UCallbackAction(C::*func)(P1, P2, const UMessage &), P1 p1, P2 p2)
template<class C , class P1 , class P2 , class P3 >
UCallbackWrapper & callback (C &ref, UCallbackAction(C::*func)(P1, P2, P3, const UMessage &), P1 p1, P2 p2, P3 p3)
template<class C , class P1 , class P2 , class P3 , class P4 >
UCallbackWrapper & callback (C &ref, UCallbackAction(C::*func)(P1, P2, P3, P4, const UMessage &), P1 p1, P2 p2, P3 p3, P4 p4)
Variables
static
boost::thread_specific_ptr
< impl::UContextImpl >
current_context & noop
static impl::UContextImpl * default_context = 0
static impl::RemoteUContextImpl * defaultContext
const char * tag_error = "[error]"
Fake tag to treat error message with tags.
const char * tag_wildcard = "[wildcard]"
Fake tag to catch all the messages.
static UCallbackID nextId
UClient * defaultClient = 0
const char * connectionTimeoutTag = "connection_timeout"
const char * internalPongTag = "internal_pong"
static const char * formats []
static const char semicolon = ';'
static const char pipe = '|'
static const char parallel = '&'
static const char comma = ','
static const std::string externalModuleTag = "__ExternalMessage__"
Detailed Description
Global definition of the starterlist.
Typedef Documentation
typedef std::list<BinaryData> urbi::binaries_type
List of the binaries.
Definition at line 44 of file ubinary.hh.
typedef unsigned char urbi::byte
Definition at line 22 of file uconversion.hh.
typedef std::vector<std::string> urbi::files_type
Definition at line 96 of file main.cc.
typedef boost::shared_ptr<std::string> urbi::TimerHandle
Definition at line 57 of file fwd.hh.
typedef UCallbackAction(* urbi::UCallback)(const UMessage &msg)
Callback prototypes.
Definition at line 69 of file uabstractclient.hh.
typedef unsigned int urbi::UCallbackID
Definition at line 64 of file uabstractclient.hh.
typedef UCallbackAction(* urbi::UCustomCallback)(void *callbackData, const UMessage &msg)
Definition at line 71 of file uabstractclient.hh.
typedef boost::unordered_map<std::string, UValue> urbi::UDictionary
Definition at line 106 of file uvalue.hh.
typedef std::list<UObject*> urbi::UObjectList
Definition at line 41 of file fwd.hh.
typedef int urbi::UReturn
Definition at line 248 of file uobject.hh.
typedef std::list<UTimerCallback*> urbi::UTimerTable
Definition at line 97 of file utable.hh.
Enumeration Type Documentation
anonymous enum
Maximum length of an URBI tag.
Enumerator:
URBI_MAX_TAG_LENGTH
Definition at line 62 of file uabstractclient.hh.
enum urbi::LockMode
Locking model.
This enum is used in UBindThreadedFunction to tell what locking model should be used
Enumerator:
LOCK_NONE
No locking is performed.
LOCK_FUNCTION
Prevent parallel call to the same function.
For notifies, it prevent multiple parallel notifies on the same variable
LOCK_INSTANCE
Prevent parallel call to any function of this object.
LOCK_CLASS
Prevent parallel call to any function of this class.
LOCK_MODULE
Prevent parallel call to any function of this module.
Definition at line 221 of file uobject.hh.
enum urbi::UBinaryType
Enumerator:
BINARY_NONE
BINARY_UNKNOWN
BINARY_IMAGE
BINARY_SOUND
Definition at line 51 of file ubinary.hh.
enum urbi::UBlendType
Possible blending mode for an UVar.
Enumerator:
UMIX
UADD
UDISCARD
UQUEUE
UCANCEL
UNORMAL
Definition at line 38 of file ublend-type.hh.
enum urbi::UCallbackAction
Return values for the callcack functions.
Each callback function, when called, must return with either URBI_CONTINUE or URBI_REMOVE:
URBI_CONTINUE means that the client should continue to call this callbak function.
URBI_REMOVE means that the client should never call this callback again.
Enumerator:
URBI_CONTINUE
URBI_REMOVE
Definition at line 55 of file uabstractclient.hh.
enum urbi::UCallbackType
Enumerator:
UCB_
UCB_C
Definition at line 65 of file uabstractclient.cc.
enum urbi::UDataType
Possible value types a UValue can contain.
Enumerator:
DATA_BINARY
DATA_DICTIONARY
DATA_DOUBLE
DATA_LIST
DATA_OBJECT
DATA_STRING
DATA_SLOTNAME
DATA_VOID
Definition at line 38 of file uvalue.hh.
enum urbi::UImageFormat
Enumerator:
IMAGE_UNKNOWN
IMAGE_RGB
RGB 24 bit/pixel.
IMAGE_YCbCr
YCbCr 24 bit/pixel.
IMAGE_YUV
Alternate name for YCbCr.
IMAGE_JPEG
JPEG.
IMAGE_PPM
RGB with a PPM header.
IMAGE_YUV422
a.k.a YUYV, 2Bytes / pixel, Interlaced (YUYVYUYV)
IMAGE_GREY8
Grey image, 1 byte/pixel.
IMAGE_GREY4
Grey image, two pixels per byte.
IMAGE_YUV411_PLANAR
4y 1u1v planar
Definition at line 25 of file uimage.hh.
enum urbi::UMessageType
Enumerator:
MESSAGE_SYSTEM
Messages prefixed by ***.
MESSAGE_ERROR
Messages prefixed by !!!.
MESSAGE_DATA
All other messages.
Definition at line 27 of file umessage.hh.
enum urbi::UObjectMode
Possible UObject running modes.
Enumerator:
MODE_PLUGIN
MODE_REMOTE
Definition at line 21 of file ucontext.hh.
enum urbi::UProperty
URBI properties associated to a variable.
Enumerator:
PROP_RANGEMIN
PROP_RANGEMAX
PROP_SPEEDMIN
PROP_SPEEDMAX
PROP_BLEND
PROP_DELTA
PROP_CONSTANT
Definition at line 23 of file uproperty.hh.
enum urbi::USoundFormat
Enumerator:
SOUND_RAW
SOUND_WAV
SOUND_MP3
SOUND_OGG
SOUND_UNKNOWN
Definition at line 25 of file usound.hh.
enum urbi::USoundSampleFormat
Enumerator:
SAMPLE_SIGNED
SAMPLE_UNSIGNED
SAMPLE_FLOAT
Definition at line 44 of file usound.hh.
enum urbi::USystemChannel
Possible value types a UValue can contain.
Enumerator:
NEW_CHANNEL
Definition at line 41 of file usystem.hh.
enum urbi::USystemExternalMessage
Enumerator:
UEM_EVALFUNCTION
UEM_ASSIGNVALUE
UEM_EMITEVENT
UEM_ENDEVENT
UEM_NEW
UEM_DELETE
UEM_INIT
UEM_TIMER
UEM_NORTP
Definition at line 37 of file uexternal.hh.
enum urbi::UTransmitFormat
Format in which image requested with syncGetSound are transmitted
Enumerator:
URBI_TRANSMIT_JPEG
Transmit images compressed in JPEG.
URBI_TRANSMIT_YCbCr
Transmit raw YCbCr images.
Definition at line 30 of file usyncclient.hh.
Function Documentation
UCallbackWrapper& urbi::callback (UCallback cb) [inline]
Generate a callback wrapper used by UAbstractClient::setCallback().
You can pass to this function:
A function pointer, with signature UCallbackAction(*)(const UMessage&)
 setCallback(callback(&myFunction), "tag");
A reference to a class instance and a pointer to a member function.
 setCallback(callback(*this, &MyClass::myMemberFunction));
Definition at line 656 of file uabstractclient.hh.
Referenced by connect_plugin(), initialize(), and urbi::impl::RemoteUContextImpl::RemoteUContextImpl().
UCallbackWrapper& urbi::callback (UCustomCallback cb, void * data) [inline]
Definition at line 660 of file uabstractclient.hh.
template<class C > UCallbackWrapper& urbi::callback (C & ref, UCallbackAction(C::*)(const UMessage &) func)
Definition at line 667 of file uabstractclient.hh.
template<class C , class P1 > UCallbackWrapper& urbi::callback (C & ref, UCallbackAction(C::*)(P1, const UMessage &) func, P1 p1)
Definition at line 673 of file uabstractclient.hh.
template<class C , class P1 , class P2 > UCallbackWrapper& urbi::callback (C & ref, UCallbackAction(C::*)(P1, P2, const UMessage &) func, P1 p1, P2 p2)
Definition at line 679 of file uabstractclient.hh.
template<class C , class P1 , class P2 , class P3 > UCallbackWrapper& urbi::callback (C & ref, UCallbackAction(C::*)(P1, P2, P3, const UMessage &) func, P1 p1, P2 p2, P3 p3)
Definition at line 686 of file uabstractclient.hh.
template<class C , class P1 , class P2 , class P3 , class P4 > UCallbackWrapper& urbi::callback (C & ref, UCallbackAction(C::*)(P1, P2, P3, P4, const UMessage &) func, P1 p1, P2 p2, P3 p3, P4 p4)
Definition at line 693 of file uabstractclient.hh.
UAbstractClient* urbi::client_get (std::ostream & o)
Definition at line 1172 of file uabstractclient.cc.
URBI_SDK_API UClient & urbi::connect (const std::string & host)
Create a new UClient object.
Referenced by urbi::UClient::connect_().
URBI_SDK_API int urbi::convert (const UImage & src, UImage & dest)
Convert the image src to the image dest.
The image format of the destination has to be initialized. If other fields are empty, they are supposed to be identical to the source image.
The destination image can only have one of the following type rgb, ppm, YCbCr or jpeg.
Referenced by urbi::USyncClient::syncGetSound().
URBI_SDK_API int urbi::convert (const USound & source, USound & dest)
Conversion between various sound formats.
Supported sound formats are RAW format and WAV format. The dest sound must have its sound format defined and any other zero properties (channel, sampleSize, rate, sampleFormat) are copied from the source sound.
The function handles memory reallocation of the destination data if the size is to small to contains the converted sound.
int urbi::convert_jpeg_to (const byte * source, size_t sourcelen, UImageFormat dest_format, byte ** dest, size_t & size, size_t & w, size_t & h)
Convert a buffer source, which contains a JPEG image, to a buffer for the dest, which will contain a RGB/YCrCb image (depending on dest_format).
The source buffer is expected to be a pointer to a valid memory area of size equal to sourcelen.
If dest buffer pointer is nul, then it will be changed to target the allocated RGB/YCrCb image of size size. Otherwise a part of the RGB/YCrCb image will be copied in the buffer in the limit of the size argument.
The property w and h respectively correspond to the width and the height that are retrieved during the convertion of the convertion of the data.
Returns:
1 on success.
Definition at line 166 of file uconversion.cc.
References IMAGE_RGB, and IMAGE_YCbCr.
URBI_SDK_API int urbi::convertJPEGtoRGB (const byte * source, size_t sourcelen, byte ** dest, size_t & size, size_t & w, size_t & h)
Referenced by urbi::USyncClient::syncGetImage().
URBI_SDK_API int urbi::convertJPEGtoYCrCb (const byte * source, size_t sourcelen, byte ** dest, size_t & size, size_t & w, size_t & h)
Referenced by urbi::USyncClient::syncGetImage().
URBI_SDK_API int urbi::convertRGBtoJPEG (const byte * source, size_t w, size_t h, byte * dest, size_t & size, int quality)
Convert a buffer source, which contains an RGB image, to a buffer for the dest, which will contain a JPEG image.
The source and dest are expected to be pointers to a valid memory area of size equal to size. The size argument is modified to represent the size of the JPEG data inside the dest buffer.
Arguments w, h and quality are used to respectively define the width, the height and the quality of the compressed image.
URBI_SDK_API int urbi::convertRGBtoYCrCb (const byte * sourceImage, size_t bufferSize, byte * destinationImage)
Convert a buffer sourceImage, which contains an RGB image, to a buffer for the destinationImage, which will contain a YCrCb image.
The sourceImage and destinationImage are expected to be pointers to a valid memory area of size equal to bufferSize.
URBI_SDK_API int urbi::convertYCrCbtoJPEG (const byte * source, size_t w, size_t h, byte * dest, size_t & size, int quality)
Convert a buffer source, which contains an YCrCb image, to a buffer for the dest, which will contain a JPEG image.
The source and dest are expected to be pointers to a valid memory area of size equal to size. The size argument is modified to represent the size of the JPEG data inside the dest buffer.
Arguments w, h and quality are used to respectively define the width, the height and the quality of the compressed image.
URBI_SDK_API int urbi::convertYCrCbtoRGB (const byte * sourceImage, size_t bufferSize, byte * destinationImage)
Convert a buffer sourceImage, which contains an YCrCb, image to a buffer for the destinationImage, which will contain a RGB image.
The sourceImage and destinationImage are expected to be pointers to a valid memory area of size equal to bufferSize.
Referenced by urbi::USyncClient::syncGetImage().
URBI_SDK_API int urbi::convertYCrCbtoYCbCr (const byte * sourceImage, size_t bufferSize, byte * destinationImage)
Convert a buffer sourceImage, which contains an YCrCb, image to a buffer for the destinationImage, which will contain a YCbCr image.
Image format conversion functions.
This function is its own reverse operation and can be used to convert YCbCr image into YCrCb.
The sourceImage and destinationImage are expected to be pointers to a valid memory area of size equal to bufferSize.
template<class S , class D > void urbi::copy (S * src, D * dst, int sc, int dc, int sr, int dr, int count, bool sf, bool df)
Definition at line 731 of file uconversion.cc.
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 , class P9 > UGenericCallback* urbi::createUCallback (UObject & owner, UVar * target, const std::string & type, R(*)(P1, P2, P3, P4, P5, P6, P7, P8, P9) fun, const std::string & funname, impl::UContextImpl * ctx)
Definition at line 1951 of file ucallbacks.hh.
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 , class P9 , class P10 > UGenericCallback* urbi::createUCallback (UObject & owner, UVar * target, const std::string & type, R(*)(P1, P2, P3, P4, P5, P6, P7, P8, P9, P10) fun, const std::string & funname, impl::UContextImpl * ctx)
Definition at line 2135 of file ucallbacks.hh.
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 , class P9 , class P10 , class P11 > UGenericCallback* urbi::createUCallback (UObject & owner, UVar * target, const std::string & type, R(*)(P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11) fun, const std::string & funname, impl::UContextImpl * ctx)
Definition at line 2319 of file ucallbacks.hh.
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 , class P9 , class P10 , class P11 , class P12 > UGenericCallback* urbi::createUCallback (UObject & owner, UVar * target, const std::string & type, R(*)(P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12) fun, const std::string & funname, impl::UContextImpl * ctx)
Definition at line 2503 of file ucallbacks.hh.
template<class R > UGenericCallback* urbi::createUCallback (UObject & owner, UVar * target, const std::string & type, R(*)() fun, const std::string & funname, impl::UContextImpl * ctx)
Definition at line 295 of file ucallbacks.hh.
Referenced by urbi::impl::RemoteUObjectImpl::initialize().
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 , class P9 , class P10 , class P11 , class P12 , class P13 > UGenericCallback* urbi::createUCallback (UObject & owner, UVar * target, const std::string & type, R(*)(P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13) fun, const std::string & funname, impl::UContextImpl * ctx)
Definition at line 2687 of file ucallbacks.hh.
template<class R , class P1 > UGenericCallback* urbi::createUCallback (UObject & owner, UVar * target, const std::string & type, R(*)(P1) fun, const std::string & funname, impl::UContextImpl * ctx)
Definition at line 479 of file ucallbacks.hh.
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 , class P9 , class P10 , class P11 , class P12 , class P13 , class P14 > UGenericCallback* urbi::createUCallback (UObject & owner, UVar * target, const std::string & type, R(*)(P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14) fun, const std::string & funname, impl::UContextImpl * ctx)
Definition at line 2871 of file ucallbacks.hh.
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 , class P9 , class P10 , class P11 , class P12 , class P13 , class P14 , class P15 > UGenericCallback* urbi::createUCallback (UObject & owner, UVar * target, const std::string & type, R(*)(P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15) fun, const std::string & funname, impl::UContextImpl * ctx)
Definition at line 3055 of file ucallbacks.hh.
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 , class P9 , class P10 , class P11 , class P12 , class P13 , class P14 , class P15 , class P16 > UGenericCallback* urbi::createUCallback (UObject & owner, UVar * target, const std::string & type, R(*)(P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15, P16) fun, const std::string & funname, impl::UContextImpl * ctx)
Definition at line 3239 of file ucallbacks.hh.
template<class R , class P1 , class P2 > UGenericCallback* urbi::createUCallback (UObject & owner, UVar * target, const std::string & type, R(*)(P1, P2) fun, const std::string & funname, impl::UContextImpl * ctx)
Definition at line 663 of file ucallbacks.hh.
template<class R > UGenericCallback* urbi::createUCallback (UObject & owner, UVar * target, const std::string & type, boost::function0< R > fun, const std::string & funname, impl::UContextImpl * ctx)
Definition at line 3327 of file ucallbacks.hh.
template<class R , class P1 > UGenericCallback* urbi::createUCallback (UObject & owner, UVar * target, const std::string & type, boost::function1< R, P1 > fun, const std::string & funname, impl::UContextImpl * ctx)
Definition at line 3384 of file ucallbacks.hh.
template<class R , class P1 , class P2 > UGenericCallback* urbi::createUCallback (UObject & owner, UVar * target, const std::string & type, boost::function2< R, P1, P2 > fun, const std::string & funname, impl::UContextImpl * ctx)
Definition at line 3441 of file ucallbacks.hh.
template<class R , class P1 , class P2 , class P3 > UGenericCallback* urbi::createUCallback (UObject & owner, UVar * target, const std::string & type, boost::function3< R, P1, P2, P3 > fun, const std::string & funname, impl::UContextImpl * ctx)
Definition at line 3498 of file ucallbacks.hh.
template<class R , class P1 , class P2 , class P3 , class P4 > UGenericCallback* urbi::createUCallback (UObject & owner, UVar * target, const std::string & type, boost::function4< R, P1, P2, P3, P4 > fun, const std::string & funname, impl::UContextImpl * ctx)
Definition at line 3555 of file ucallbacks.hh.
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 > UGenericCallback* urbi::createUCallback (UObject & owner, UVar * target, const std::string & type, boost::function5< R, P1, P2, P3, P4, P5 > fun, const std::string & funname, impl::UContextImpl * ctx)
Definition at line 3612 of file ucallbacks.hh.
template<class R , class P1 , class P2 , class P3 > UGenericCallback* urbi::createUCallback (UObject & owner, UVar * target, const std::string & type, R(*)(P1, P2, P3) fun, const std::string & funname, impl::UContextImpl * ctx)
Definition at line 847 of file ucallbacks.hh.
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > UGenericCallback* urbi::createUCallback (UObject & owner, UVar * target, const std::string & type, boost::function6< R, P1, P2, P3, P4, P5, P6 > fun, const std::string & funname, impl::UContextImpl * ctx)
Definition at line 3669 of file ucallbacks.hh.
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 > UGenericCallback* urbi::createUCallback (UObject & owner, UVar * target, const std::string & type, boost::function7< R, P1, P2, P3, P4, P5, P6, P7 > fun, const std::string & funname, impl::UContextImpl * ctx)
Definition at line 3726 of file ucallbacks.hh.
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 > UGenericCallback* urbi::createUCallback (UObject & owner, UVar * target, const std::string & type, boost::function8< R, P1, P2, P3, P4, P5, P6, P7, P8 > fun, const std::string & funname, impl::UContextImpl * ctx)
Definition at line 3783 of file ucallbacks.hh.
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 , class P9 > UGenericCallback* urbi::createUCallback (UObject & owner, UVar * target, const std::string & type, boost::function9< R, P1, P2, P3, P4, P5, P6, P7, P8, P9 > fun, const std::string & funname, impl::UContextImpl * ctx)
Definition at line 3840 of file ucallbacks.hh.
template<class R , class P1 , class P2 , class P3 , class P4 > UGenericCallback* urbi::createUCallback (UObject & owner, UVar * target, const std::string & type, R(*)(P1, P2, P3, P4) fun, const std::string & funname, impl::UContextImpl * ctx)
Definition at line 1031 of file ucallbacks.hh.
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 , class P9 , class P10 > UGenericCallback* urbi::createUCallback (UObject & owner, UVar * target, const std::string & type, boost::function10< R, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 > fun, const std::string & funname, impl::UContextImpl * ctx)
Definition at line 3897 of file ucallbacks.hh.
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 > UGenericCallback* urbi::createUCallback (UObject & owner, UVar * target, const std::string & type, R(*)(P1, P2, P3, P4, P5) fun, const std::string & funname, impl::UContextImpl * ctx)
Definition at line 1215 of file ucallbacks.hh.
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > UGenericCallback* urbi::createUCallback (UObject & owner, UVar * target, const std::string & type, R(*)(P1, P2, P3, P4, P5, P6) fun, const std::string & funname, impl::UContextImpl * ctx)
Definition at line 1399 of file ucallbacks.hh.
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 > UGenericCallback* urbi::createUCallback (UObject & owner, UVar * target, const std::string & type, R(*)(P1, P2, P3, P4, P5, P6, P7) fun, const std::string & funname, impl::UContextImpl * ctx)
Definition at line 1583 of file ucallbacks.hh.
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 > UGenericCallback* urbi::createUCallback (UObject & owner, UVar * target, const std::string & type, R(*)(P1, P2, P3, P4, P5, P6, P7, P8) fun, const std::string & funname, impl::UContextImpl * ctx)
Definition at line 1767 of file ucallbacks.hh.
template<class R > UGenericCallback* urbi::createUCallbackStd (UObject & owner, UVar * target, const std::string & type, R(ATTRIBUTE_STDCALL *fun)() , const std::string & funname, impl::UContextImpl * ctx)
Definition at line 3340 of file ucallbacks.hh.
template<class R , class P1 > UGenericCallback* urbi::createUCallbackStd (UObject & owner, UVar * target, const std::string & type, R(ATTRIBUTE_STDCALL *fun)(P1) , const std::string & funname, impl::UContextImpl * ctx)
Definition at line 3397 of file ucallbacks.hh.
template<class R , class P1 , class P2 > UGenericCallback* urbi::createUCallbackStd (UObject & owner, UVar * target, const std::string & type, R(ATTRIBUTE_STDCALL *fun)(P1, P2) , const std::string & funname, impl::UContextImpl * ctx)
Definition at line 3454 of file ucallbacks.hh.
template<class R , class P1 , class P2 , class P3 > UGenericCallback* urbi::createUCallbackStd (UObject & owner, UVar * target, const std::string & type, R(ATTRIBUTE_STDCALL *fun)(P1, P2, P3) , const std::string & funname, impl::UContextImpl * ctx)
Definition at line 3511 of file ucallbacks.hh.
template<class R , class P1 , class P2 , class P3 , class P4 > UGenericCallback* urbi::createUCallbackStd (UObject & owner, UVar * target, const std::string & type, R(ATTRIBUTE_STDCALL *fun)(P1, P2, P3, P4) , const std::string & funname, impl::UContextImpl * ctx)
Definition at line 3568 of file ucallbacks.hh.
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 > UGenericCallback* urbi::createUCallbackStd (UObject & owner, UVar * target, const std::string & type, R(ATTRIBUTE_STDCALL *fun)(P1, P2, P3, P4, P5) , const std::string & funname, impl::UContextImpl * ctx)
Definition at line 3625 of file ucallbacks.hh.
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > UGenericCallback* urbi::createUCallbackStd (UObject & owner, UVar * target, const std::string & type, R(ATTRIBUTE_STDCALL *fun)(P1, P2, P3, P4, P5, P6) , const std::string & funname, impl::UContextImpl * ctx)
Definition at line 3682 of file ucallbacks.hh.
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 > UGenericCallback* urbi::createUCallbackStd (UObject & owner, UVar * target, const std::string & type, R(ATTRIBUTE_STDCALL *fun)(P1, P2, P3, P4, P5, P6, P7) , const std::string & funname, impl::UContextImpl * ctx)
Definition at line 3739 of file ucallbacks.hh.
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 > UGenericCallback* urbi::createUCallbackStd (UObject & owner, UVar * target, const std::string & type, R(ATTRIBUTE_STDCALL *fun)(P1, P2, P3, P4, P5, P6, P7, P8) , const std::string & funname, impl::UContextImpl * ctx)
Definition at line 3796 of file ucallbacks.hh.
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 , class P9 > UGenericCallback* urbi::createUCallbackStd (UObject & owner, UVar * target, const std::string & type, R(ATTRIBUTE_STDCALL *fun)(P1, P2, P3, P4, P5, P6, P7, P8, P9) , const std::string & funname, impl::UContextImpl * ctx)
Definition at line 3853 of file ucallbacks.hh.
template<class R , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 , class P7 , class P8 , class P9 , class P10 > UGenericCallback* urbi::createUCallbackStd (UObject & owner, UVar * target, const std::string & type, R(ATTRIBUTE_STDCALL *fun)(P1, P2, P3, P4, P5, P6, P7, P8, P9, P10) , const std::string & funname, impl::UContextImpl * ctx)
Definition at line 3910 of file ucallbacks.hh.
UCallbackAction urbi::debug (const UMessage & msg)
Definition at line 47 of file main.cc.
Referenced by initialize().
URBI_SDK_API std::ostream & urbi::default_stream ()
Return a stream for error, preferrably the one the defaultClient.
static void urbi::destroySocket (libport::Socket * s) [static]
Definition at line 587 of file usyncclient.cc.
Referenced by urbi::USyncClient::listen().
URBI_SDK_API void urbi::disconnect (UClient & client)
Destroy an UClient object Be careful: don't use client after called this function.
void urbi::dup (byte * dst, byte * src, int count)
Definition at line 713 of file uconversion.cc.
void urbi::dup (unsigned short * dst, unsigned short * src, int count)
Definition at line 703 of file uconversion.cc.
URBI_SDK_API void urbi::echo (const char * format, ...)
echo method
Referenced by urbi::impl::RemoteUGenericCallbackImpl::initialize(), urbi::UVar::invariant(), and urbi::USystem::USystem().
static boolean urbi::empty_output_buffer (j_compress_ptr) [static]
Definition at line 322 of file uconversion.cc.
static UCallbackAction urbi::endProgram (const UMessage & msg) [static]
Definition at line 55 of file main.cc.
References exit().
Referenced by initialize().
URBI_SDK_API void urbi::execute ()
Must be called at the last line of your main() function.
URBI_SDK_API void urbi::exit (int code)
Terminate your URBI program.
Referenced by connect_plugin(), urbi::impl::RemoteUContextImpl::dispatcher(), endProgram(), initialize(), onDone(), urbi_launch(), usage(), usage(), version(), and version().
URBI_SDK_API const char * urbi::format_string (UImageFormat f)
URBI_SDK_API const char * urbi::format_string (USoundFormat f)
Conversion to string.
URBI_SDK_API UClient & urbi::get_default_client ()
Same as getDefaultClient(), but as a reference.
URBI_SDK_API std::string urbi::getClientConnectionID (const UAbstractClient * cli)
URBI_SDK_API impl::UContextImpl * urbi::getCurrentContext ()
Will be used if no context is explicitly passed.
Referenced by urbi::UGenericCallback::fetchContext(), urbi::UVar::init(), urbi::UEvent::init(), urbi::uvalue_caster< UVar >::operator()(), and urbi::UObjectSocket::~UObjectSocket().
URBI_SDK_API UClient * urbi::getDefaultClient ()
Return the first UClient created by the program.
Referenced by initialize(), and urbi::UAbstractClient::~UAbstractClient().
URBI_SDK_API std::string urbi::getFilteredHostname ()
Return current hostname mangled to fit into an urbiscript variable name.
Referenced by urbi::impl::rtp_id().
UObjectMode urbi::getRunningMode () [inline]
UObject * urbi::getUObject (const std::string & n) [inline]
Referenced by urbi::uvalue_caster< UObject * >::operator()(), and urbi::impl::RemoteUVarImpl::set().
UObjectHub * urbi::getUObjectHub (const std::string & n) [inline]
template<typename T > int urbi::getValue (UMessage * m, T & val) [inline]
Set val to the value of m.
Returns:
1 on success, 0 on failure. An error message is printed on error.
Definition at line 21 of file umessage.hxx.
References MESSAGE_DATA, urbi::UMessage::type, and urbi::UMessage::value.
Referenced by urbi::USyncClient::syncGetDevice(), urbi::USyncClient::syncGetNormalizedDevice(), urbi::USyncClient::syncGetResult(), and urbi::USyncClient::syncGetValue().
template<> int urbi::getValue< double > (UMessage * m, double & val) [inline]
static void urbi::init_destination (j_compress_ptr) [static]
Definition at line 318 of file uconversion.cc.
int URBI_SDK_API urbi::initialize (const std::string & host, int port, size_t buflen, bool exitOnDisconnect, bool server = false)
Initialisation method, for remote mode only, that returns.
Parameters:
host the host to connect to.
port the port number to connect to (you can use the constant UAbstractClient::URBI_PORT).
buflen receive and send buffer size (you can use the constant UAbstractClient::URBI_BUFLEN).
exitOnDisconnect call exit() if we get disconnected from server.
server whether listens instead of connecting.
Returns:
0 if no error occured.
int urbi::initialize (const std::string & host, int port, size_t buflen, bool exitOnDisconnect, bool server, const files_type & files, bool useSyncClient)
Definition at line 98 of file main.cc.
References callback(), debug(), defaultContext, endProgram(), exit(), externalModuleTag, getDefaultClient(), urbi::UAbstractClient::notifyCallbacks(), package_info(), urbi::UAbstractClient::sendFile(), urbi::UAbstractClient::setClientErrorCallback(), setDefaultClient(), urbi::UAbstractClient::setErrorCallback(), and urbi::UAbstractClient::setWildcardCallback().
bool urbi::is_blendtype (int i) [inline]
Definition at line 64 of file ublend-type.hh.
References UNORMAL.
Referenced by ublendtype().
bool urbi::is_propertytype (int i) [inline]
Definition at line 51 of file uproperty.hh.
References PROP_CONSTANT, and PROP_RANGEMAX.
Referenced by uproperty().
bool urbi::isPluginMode () [inline]
bool urbi::isRemoteMode () [inline]
URBI_SDK_API int urbi::kernelMajor ()
Referenced by urbi::UAbstractClient::setVersion().
URBI_SDK_API int & urbi::kernelMajor (std::ostream & o)
If a kernel version was associated to this stream, its value.
URBI_SDK_API int urbi::kernelMinor ()
URBI_SDK_API const std::string & urbi::kernelVersion ()
URBI_SDK_API int urbi::main (const libport::cli_args_type & args, UrbiRoot & root, bool block = true, bool errors = false)
Initialisation method.
Both plugin and remote libraries include a main function whose only effect is to call urbi::main. If you need to write your own main, call urbi::main(argc, argv) after your work is done. This function returns if block is set to false.
URBI_SDK_API int urbi::main (int argc, const char * argv[], UrbiRoot & urbi_root, bool block, bool errors)
Initialisation method using C style arguments.
Referenced by urbi_main(), and urbi_main_args().
urbi::MKCreateUCallBackEnd0 ()
urbi::MKCreateUCallBackEnd0 (const)
urbi::MKCreateUCallBackEnd0 (const , const)
urbi::MKCreateUCallBackEnd1 ()
urbi::MKCreateUCallBackEnd1 (const)
urbi::MKCreateUCallBackEnd1 (const , const)
urbi::MKCreateUCallBackEnd10 ()
urbi::MKCreateUCallBackEnd10 (const)
urbi::MKCreateUCallBackEnd10 (const , const)
urbi::MKCreateUCallBackEnd11 ()
urbi::MKCreateUCallBackEnd11 (const)
urbi::MKCreateUCallBackEnd11 (const , const)
urbi::MKCreateUCallBackEnd12 ()
urbi::MKCreateUCallBackEnd12 (const)
urbi::MKCreateUCallBackEnd12 (const , const)
urbi::MKCreateUCallBackEnd13 (const)
urbi::MKCreateUCallBackEnd13 ()
urbi::MKCreateUCallBackEnd13 (const , const)
urbi::MKCreateUCallBackEnd14 ()
urbi::MKCreateUCallBackEnd14 (const , const)
urbi::MKCreateUCallBackEnd14 (const)
urbi::MKCreateUCallBackEnd15 (const)
urbi::MKCreateUCallBackEnd15 ()
urbi::MKCreateUCallBackEnd15 (const , const)
urbi::MKCreateUCallBackEnd16 ()
urbi::MKCreateUCallBackEnd16 (const , const)
urbi::MKCreateUCallBackEnd16 (const)
urbi::MKCreateUCallBackEnd2 ()
urbi::MKCreateUCallBackEnd2 (const)
urbi::MKCreateUCallBackEnd2 (const , const)
urbi::MKCreateUCallBackEnd3 (const)
urbi::MKCreateUCallBackEnd3 ()
urbi::MKCreateUCallBackEnd3 (const , const)
urbi::MKCreateUCallBackEnd4 ()
urbi::MKCreateUCallBackEnd4 (const)
urbi::MKCreateUCallBackEnd4 (const , const)
urbi::MKCreateUCallBackEnd5 ()
urbi::MKCreateUCallBackEnd5 (const)
urbi::MKCreateUCallBackEnd5 (const , const)
urbi::MKCreateUCallBackEnd6 ()
urbi::MKCreateUCallBackEnd6 (const)
urbi::MKCreateUCallBackEnd6 (const , const)
urbi::MKCreateUCallBackEnd7 ()
urbi::MKCreateUCallBackEnd7 (const)
urbi::MKCreateUCallBackEnd7 (const , const)
urbi::MKCreateUCallBackEnd8 ()
urbi::MKCreateUCallBackEnd8 (const)
urbi::MKCreateUCallBackEnd8 (const , const)
urbi::MKCreateUCallBackEnd9 ()
urbi::MKCreateUCallBackEnd9 (const)
urbi::MKCreateUCallBackEnd9 (const , const)
urbi::MKUCreateCallBack0 ()
urbi::MKUCreateCallBack0 (const)
urbi::MKUCreateCallBack1 (const)
urbi::MKUCreateCallBack1 ()
urbi::MKUCreateCallBack10 ()
urbi::MKUCreateCallBack10 (const)
urbi::MKUCreateCallBack11 ()
urbi::MKUCreateCallBack11 (const)
urbi::MKUCreateCallBack12 ()
urbi::MKUCreateCallBack12 (const)
urbi::MKUCreateCallBack13 ()
urbi::MKUCreateCallBack13 (const)
urbi::MKUCreateCallBack14 (const)
urbi::MKUCreateCallBack14 ()
urbi::MKUCreateCallBack15 ()
urbi::MKUCreateCallBack15 (const)
urbi::MKUCreateCallBack16 ()
urbi::MKUCreateCallBack16 (const)
urbi::MKUCreateCallBack2 ()
urbi::MKUCreateCallBack2 (const)
urbi::MKUCreateCallBack3 ()
urbi::MKUCreateCallBack3 (const)
urbi::MKUCreateCallBack4 (const)
urbi::MKUCreateCallBack4 ()
urbi::MKUCreateCallBack5 (const)
urbi::MKUCreateCallBack5 ()
urbi::MKUCreateCallBack6 (const)
urbi::MKUCreateCallBack6 ()
urbi::MKUCreateCallBack7 ()
urbi::MKUCreateCallBack7 (const)
urbi::MKUCreateCallBack8 (const)
urbi::MKUCreateCallBack8 ()
urbi::MKUCreateCallBack9 ()
urbi::MKUCreateCallBack9 (const)
const char* urbi::name (UProperty u) [inline]
Definition at line 60 of file uproperty.hh.
const char* urbi::name (UBlendType u) [inline]
Definition at line 72 of file ublend-type.hh.
Referenced by urbi::UEvent::emit(), urbi::impl::RemoteUVarImpl::getProp(), urbi::UVar::init(), urbi::UEvent::init(), urbi::impl::RemoteUVarImpl::initialize(), urbi::UVar::invariant(), urbi::impl::RemoteUContextImpl::localCall(), urbi::UObjectStruct::operator[](), urbi::impl::RemoteUVarImpl::request(), urbi::impl::RemoteUVarImpl::set(), urbi::impl::RemoteUVarImpl::setProp(), urbi::impl::RemoteUVarImpl::sync(), urbi::impl::RemoteUVarImpl::unnotify(), and urbi::impl::RemoteUVarImpl::useRTP().
static void urbi::noop (impl::UContextImpl *) [static]
Definition at line 42 of file uobject-common.cc.
template<typename V > UValue& urbi::operator, (UValue & v, const boost::unordered_map< std::string, V > & d) [inline]
Definition at line 343 of file uvalue.hxx.
References urbi::UValue::clear(), urbi::UValue::dictionary, and urbi::UValue::type.
UValue & urbi::operator, (UValue & a, const UObject * b) [inline]
Definition at line 121 of file uobject.hxx.
References urbi::UObject::__name, and urbi::UValue::type.
std::ostream& urbi::operator<< (std::ostream & o, const UVar & u)
Report u on o for debugging.
Definition at line 122 of file uvar-common.cc.
URBI_SDK_API std::ostream & urbi::operator<< (std::ostream & o, const UList & t)
std::ostream & urbi::operator<< (std::ostream & s, const UMessage & m) [inline]
Definition at line 50 of file umessage.hxx.
References urbi::UMessage::print().
std::ostream& urbi::operator<< (std::ostream & o, USoundSampleFormat f)
Definition at line 75 of file usound.cc.
References SAMPLE_SIGNED, and SAMPLE_UNSIGNED.
std::ostream & urbi::operator<< (std::ostream & s, const urbi::UDictionary & d) [inline]
URBI_SDK_API std::ostream & urbi::operator<< (std::ostream & o, const UObjectStruct & t)
URBI_SDK_API std::ostream & urbi::operator<< (std::ostream & o, const UBinary & t)
std::ostream & urbi::operator<< (std::ostream & s, const UValue & v) [inline]
Definition at line 208 of file uvalue.hxx.
References urbi::UValue::print().
std::ostream & urbi::operator<< (std::ostream & o, const USound & s)
std::istream & urbi::operator>> (std::istream & is, USoundSampleFormat & f)
URBI_SDK_API const libport::PackageInfo & urbi::package_info ()
Package information about liburbi and UObjects.
Referenced by initialize(), version(), and version().
URBI_SDK_API UImageFormat urbi::parse_image_format (const std::string & s)
Referenced by urbi::UBinary::parse().
URBI_SDK_API USoundFormat urbi::parse_sound_format (const std::string & s)
Parse a sound format string.
Referenced by urbi::UBinary::parse().
template<typename D > void urbi::pud (D * dst, D * src, int count)
Definition at line 725 of file uconversion.cc.
URBI_SDK_API UObjectMode urbi::running_mode ()
void urbi::send (const char * str) [inline]
Referenced by urbi::impl::RemoteUVarImpl::unnotify(), and urbi::impl::RemoteUVarImpl::useRTP().
void urbi::send (const std::string & str) [inline]
void urbi::send (const void * buf, size_t size) [inline]
Send buf to the connection hosting the UObject.
static UCallbackAction urbi::sendSound_ (void * cb, const UMessage & msg) [static]
TODO: make this constant modifiable
Definition at line 519 of file uabstractclient.cc.
References urbi::wavheader::datalength, urbi::wavheader::length, SOUND_WAV, and urbi::UMessage::tag.
Referenced by urbi::UAbstractClient::sendSound().
URBI_SDK_API void urbi::setCurrentContext (impl::UContextImpl * impl)
Referenced by urbi::impl::RemoteUContextImpl::dispatcher(), urbi::impl::UContextImpl::init(), urbi::URBIStarterHub< T >::instanciate(), and urbi::URBIStarter< T >::instanciate().
URBI_SDK_API void urbi::setDefaultClient (UClient * cl)
Redefine the default client.
Referenced by initialize(), and urbi::UAbstractClient::~UAbstractClient().
URBI_SDK_API void urbi::setThreadLimit (size_t nThreads)
Set maximum number of threads to use for threaded calls (0=unlimited).
static void urbi::term_destination (j_compress_ptr) [static]
Definition at line 327 of file uconversion.cc.
UBlendType urbi::ublendtype (const char * cp) [inline]
Definition at line 79 of file ublend-type.hh.
References is_blendtype().
urbi::UCLIENT_OPTION_IMPL (USyncClient , USyncClient::connect_callback_type , connectCallback)
urbi::UCLIENT_OPTION_IMPL (USyncClient , bool , startCallbackThread)
URBI_SDK_API std::ostream & urbi::unarmorAndSend (const char * a, UAbstractClient * where)
Send a possibly armored string to the default client.
Referenced by urbi::impl::RemoteUContextImpl::uobject_unarmorAndSend().
void urbi::uobject_unarmorAndSend (const char * str) [inline]
Send Urbi code (ghost connection in plugin mode, default connection in remote mode).
UProperty urbi::uproperty (const char * cp) [inline]
Definition at line 67 of file uproperty.hh.
References is_propertytype().
urbi::urbi_jpeg_error_exit (j_common_ptr cinfo)
Definition at line 299 of file uconversion.cc.
static void urbi::usage () [static]
Definition at line 64 of file main.cc.
References urbi::UAbstractClient::default_host(), exit(), urbi::UAbstractClient::URBI_BUFLEN, and urbi::UAbstractClient::URBI_PORT.
template<typename Type > uvar_ref_traits< typename uvalue_cast_return_type< Type >::type >::type urbi::uvalue_cast (UValue & v)
Definition at line 226 of file uvalue.hxx.
Referenced by urbi::UVar::as(), urbi::UVar::fill(), urbi::uvalue_caster< boost::unordered_map< std::string, V > >::operator()(), urbi::UVar::operator==(), and uvar_uvalue_cast().
urbi::UVALUE_CASTER_DECLARE (UDictionary)
urbi::UVALUE_CASTER_DECLARE (UBinary)
urbi::UVALUE_CASTER_DECLARE (UObjectStruct)
urbi::UVALUE_CASTER_DECLARE (UList)
urbi::UVALUE_CASTER_DECLARE (const char *)
urbi::UVALUE_CASTER_DEFINE (USound)
urbi::UVALUE_CASTER_DEFINE (std::string)
urbi::UVALUE_CASTER_DEFINE (UValue &)
urbi::UVALUE_CASTER_DEFINE (const UValue &)
urbi::UVALUE_CASTER_DEFINE (bool)
urbi::UVALUE_CASTER_DEFINE (UImage)
urbi::UVALUE_CASTER_DEFINE (const UValue)
urbi::UVALUE_CONTAINER_CASTER_DECLARE (std::list)
urbi::UVALUE_CONTAINER_CASTER_DECLARE (std::vector)
urbi::UVALUE_OPERATORS (const UDictionary & d, DATA_DICTIONARY , dictionary , new UDictionaryd)
urbi::UVALUE_OPERATORS (const UObjectStruct & v, DATA_OBJECT , object , new UObjectStructv)
Definition at line 466 of file uvalue-common.cc.
References urbi::UValue::binary, DATA_BINARY, DATA_DOUBLE, DATA_LIST, DATA_SLOTNAME, DATA_VOID, urbi::UValue::list, and urbi::UValue::type.
template<typename T > uvar_ref_traits<typename uvalue_cast_return_type<T>::type>::type urbi::uvar_uvalue_cast (UValue & v) [inline]
Definition at line 140 of file ucallbacks.hh.
References DATA_VOID, urbi::UValue::storage, urbi::UValue::type, uvalue_cast(), and urbi::UVar::val().
Referenced by urbi::UFCallback16< R, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15, P16 >::__evalcall(), urbi::UCallback16< OBJ, R, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15, P16 >::__evalcall(), urbi::UFCallback15< R, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >::__evalcall(), urbi::UCallback15< OBJ, R, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14, P15 >::__evalcall(), urbi::UFCallback14< R, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >::__evalcall(), urbi::UCallback14< OBJ, R, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14 >::__evalcall(), urbi::UFCallback13< R, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >::__evalcall(), urbi::UCallback13< OBJ, R, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13 >::__evalcall(), urbi::UFCallback12< R, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >::__evalcall(), urbi::UCallback12< OBJ, R, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12 >::__evalcall(), urbi::UFCallback11< R, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >::__evalcall(), urbi::UCallback11< OBJ, R, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, P11 >::__evalcall(), urbi::UFCallback10< R, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >::__evalcall(), urbi::UCallback10< OBJ, R, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10 >::__evalcall(), urbi::UFCallback9< R, P1, P2, P3, P4, P5, P6, P7, P8, P9 >::__evalcall(), urbi::UCallback9< OBJ, R, P1, P2, P3, P4, P5, P6, P7, P8, P9 >::__evalcall(), urbi::UFCallback8< R, P1, P2, P3, P4, P5, P6, P7, P8 >::__evalcall(), urbi::UCallback8< OBJ, R, P1, P2, P3, P4, P5, P6, P7, P8 >::__evalcall(), urbi::UFCallback7< R, P1, P2, P3, P4, P5, P6, P7 >::__evalcall(), urbi::UCallback7< OBJ, R, P1, P2, P3, P4, P5, P6, P7 >::__evalcall(), urbi::UFCallback6< R, P1, P2, P3, P4, P5, P6 >::__evalcall(), urbi::UCallback6< OBJ, R, P1, P2, P3, P4, P5, P6 >::__evalcall(), urbi::UFCallback5< R, P1, P2, P3, P4, P5 >::__evalcall(), urbi::UCallback5< OBJ, R, P1, P2, P3, P4, P5 >::__evalcall(), urbi::UFCallback4< R, P1, P2, P3, P4 >::__evalcall(), urbi::UCallback4< OBJ, R, P1, P2, P3, P4 >::__evalcall(), urbi::UFCallback3< R, P1, P2, P3 >::__evalcall(), urbi::UCallback3< OBJ, R, P1, P2, P3 >::__evalcall(), urbi::UFCallback2< R, P1, P2 >::__evalcall(), urbi::UCallback2< OBJ, R, P1, P2 >::__evalcall(), urbi::UFCallback1< R, P1 >::__evalcall(), and urbi::UCallback1< OBJ, R, P1 >::__evalcall().
template<> UVar& urbi::uvar_uvalue_cast< UVar & > (UValue & v) [inline]
static void urbi::version () [static]
Definition at line 90 of file main.cc.
References exit(), and package_info().
Variable Documentation
const char urbi::comma = ',' [static]
Definition at line 779 of file uabstractclient.hh.
const char * urbi::connectionTimeoutTag = "connection_timeout"
Definition at line 16 of file utag.cc.
Referenced by urbi::UClient::pongTimeout().
impl::UContextImpl* urbi::default_context = 0 [static]
Definition at line 47 of file uobject-common.cc.
URBI_SDK_API UClient * urbi::defaultClient = 0
Definition at line 1185 of file uabstractclient.cc.
Referenced by urbi::USyncClient::USyncClient().
impl::RemoteUContextImpl* urbi::defaultContext [static]
Definition at line 44 of file main.cc.
Referenced by initialize().
const std::string urbi::externalModuleTag = "__ExternalMessage__" [static]
Definition at line 50 of file uexternal.hh.
Referenced by initialize(), urbi::impl::RemoteUContextImpl::onTimer(), urbi::impl::RemoteUObjectImpl::onUpdate(), urbi::impl::RemoteUContextImpl::RemoteUContextImpl(), and urbi::impl::RemoteUVarImpl::request().
static const char * urbi::formats [static]
Initial value:
  {
    "image_unknown",
    "rgb",
    "YCbCr",
    "jpeg",
    "ppm",
    "YUV422",
    "grey8",
    "grey4",
      "yuv411_planar",
  }
Definition at line 28 of file uimage.cc.
Referenced by urbi::UValue::format_string().
const char * urbi::internalPongTag = "internal_pong"
Definition at line 17 of file utag.cc.
Referenced by urbi::UClient::onConnect(), and urbi::UClient::sendPing().
UCallbackID urbi::nextId [static]
Definition at line 71 of file uabstractclient.cc.
Referenced by urbi::UAbstractClient::addCallback().
boost::thread_specific_ptr<impl::UContextImpl> current_context& urbi::noop [static]
Definition at line 46 of file uobject-common.cc.
const char urbi::parallel = '&' [static]
Definition at line 778 of file uabstractclient.hh.
const char urbi::pipe = '|' [static]
Definition at line 777 of file uabstractclient.hh.
const char urbi::semicolon = ';' [static]
Definition at line 776 of file uabstractclient.hh.
const char* urbi::tag_error = "[error]"
Fake tag to treat error message with tags.
Definition at line 48 of file uabstractclient.cc.
Referenced by urbi::UAbstractClient::notifyCallbacks(), urbi::UAbstractClient::process_recv_buffer_text_(), and urbi::UAbstractClient::setErrorCallback().
const char* urbi::tag_wildcard = "[wildcard]"
Fake tag to catch all the messages.
Definition at line 50 of file uabstractclient.cc.
Referenced by urbi::UAbstractClient::notifyCallbacks(), and urbi::UAbstractClient::setWildcardCallback().