Urbi SDK Remote: umain.hh File Reference
umain.hh File Reference
#include <libport/cli.hh>
#include <urbi/exit.hh>
#include <urbi/uobject.hh>
#include <urbi/urbi-root.hh>
Namespaces
namespace urbi
Global definition of the starterlist.
Defines
#define UMAIN_URBIROOT_STATIC false
#define UMAIN()
Functions
URBI_SDK_API int urbi_main (int argc, const char *argv[], UrbiRoot &root, bool block, bool errors)
Bouncer to urbi::main() for easier access through dlsym().
URBI_SDK_API int urbi_main_args (const libport::cli_args_type &args, UrbiRoot &root, bool block, bool errors)
Bouncer to urbi::main() for easier access through dlsym().
URBI_SDK_API int urbi::main (const libport::cli_args_type &args, UrbiRoot &root, bool block=true, bool errors=false)
Initialisation method.
int urbi::main (int argc, const char *argv[], UrbiRoot &root, bool block=true, bool errors=false)
Initialisation method using C style arguments.
int URBI_SDK_API urbi::initialize (const std::string &host, int port, size_t buflen, bool exitOnDisconnect, bool server=false)
Initialisation method, for remote mode only, that returns.
Detailed Description
Definition in file umain.hh.
Define Documentation
#define UMAIN ()
Value:
\
  int                                                           \
  main(int argc, const char** argv)                             \
  {                                                             \
    UrbiRoot urbi_root(argv[0], UMAIN_URBIROOT_STATIC);         \
    std::vector<std::string> args(argv, argv + argc);           \
    return urbi_root.urbi_main(args, true, true);               \
  }                                                             \
                                                                \
  int                                                           \
  main_args(const libport::cli_args_type& args)                 \
  {                                                             \
    size_t argc = args.size();                                  \
    const char** argv = new const char*[argc];                  \
    for (unsigned i = 0; i < argc; ++i)                         \
      argv[i] = args[i].c_str();                                \
    int res = main(argc, argv);                                 \
    delete [] argv;                                             \
    return res;                                                 \
  }                                                             \
Definition at line 27 of file umain.hh.
#define UMAIN_URBIROOT_STATIC false
Definition at line 24 of file umain.hh.
Function Documentation
URBI_SDK_API int urbi_main (int argc, const char * argv[], UrbiRoot & root, bool block, bool errors)
Bouncer to urbi::main() for easier access through dlsym().
Definition at line 20 of file urbi-main.cc.
References urbi::main().
URBI_SDK_API int urbi_main_args (const libport::cli_args_type & args, UrbiRoot & root, bool block, bool errors)
Bouncer to urbi::main() for easier access through dlsym().
Definition at line 28 of file urbi-main.cc.
References urbi::main().
Referenced by UrbiRoot::urbi_main().