Urbi SDK Remote: urbi-main.cc File Reference
urbi-main.cc File Reference
#include <libport/cli.hh>
#include <libport/containers.hh>
#include <urbi/umain.hh>
#include <urbi/urbi-root.hh>
Namespaces
namespace urbi
Global definition of the starterlist.
Functions
int urbi_main (int argc, const char *argv[], UrbiRoot &urbi_root, bool block, bool errors)
Bouncer to urbi::main() for easier access through dlsym().
int urbi_main_args (const libport::cli_args_type &args, UrbiRoot &urbi_root, bool block, bool errors)
Bouncer to urbi::main() for easier access through dlsym().
int urbi::main (int argc, const char *argv[], UrbiRoot &root, bool block=true, bool errors=false)
Initialisation method using C style arguments.
Detailed Description
Definition in file urbi-main.cc.
Function Documentation
int urbi_main (int argc, const char * argv[], UrbiRoot & root, bool block, bool errors)
Bouncer to urbi::main() for easier access through dlsym().
Definition at line 20 of file urbi-main.cc.
References urbi::main().
int urbi_main_args (const libport::cli_args_type & args, UrbiRoot & root, bool block, bool errors)
Bouncer to urbi::main() for easier access through dlsym().
Definition at line 28 of file urbi-main.cc.
References urbi::main().
Referenced by UrbiRoot::urbi_main().